package org.rnd.jmagic.engine;

public abstract class SpecialActionFactory
{
	/**
	 * @param state The state to create the actions are in
	 * @param source The object these actions are coming from
	 * @param actor The player who can perform the actions
	 * @return The actions generated by this object
	 */
	public abstract java.util.Set<PlayerAction> getActions(GameState state, GameObject source, Player actor);
}
