package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Alliances")
public final class Alliances extends SimpleExpansion
{
	public Alliances()
	{
		super();

		this.addCards(Rarity.COMMON, "Aesthir Glider", "Aesthir Glider", "Agent of Stromgald", "Agent of Stromgald", "Arcane Denial", "Arcane Denial", "Astrolabe", "Astrolabe", "Awesome Presence", "Awesome Presence", "Balduvian War-Makers", "Balduvian War-Makers", "Benthic Explorers", "Benthic Explorers", "Bestial Fury", "Bestial Fury", "Carrier Pigeons", "Carrier Pigeons", "Casting of Bones", "Casting of Bones", "Deadly Insect", "Deadly Insect", "Elvish Ranger", "Elvish Ranger", "Enslaved Scout", "Enslaved Scout", "Errand of Duty", "Errand of Duty", "False Demise", "False Demise", "Feast or Famine", "Feast or Famine", "Fevered Strength", "Fevered Strength", "Foresight", "Foresight", "Fyndhorn Druid", "Fyndhorn Druid", "Gift of the Woods", "Gift of the Woods", "Gorilla Berserkers", "Gorilla Berserkers", "Gorilla Chieftain", "Gorilla Chieftain", "Gorilla Shaman", "Gorilla Shaman", "Gorilla War Cry", "Gorilla War Cry", "Guerrilla Tactics", "Guerrilla Tactics", "Insidious Bookworms", "Insidious Bookworms", "Kjeldoran Escort", "Kjeldoran Escort", "Kjeldoran Pride", "Kjeldoran Pride", "Lat-Nam's Legacy", "Lat-Nam's Legacy", "Lim-Dûl's High Guard", "Lim-Dûl's High Guard", "Martyrdom", "Martyrdom", "Noble Steeds", "Noble Steeds", "Phantasmal Fiend", "Phantasmal Fiend", "Phyrexian Boon", "Phyrexian Boon", "Phyrexian War Beast", "Phyrexian War Beast", "Reinforcements", "Reinforcements", "Reprisal", "Reprisal", "Royal Herbalist", "Royal Herbalist", "Soldevi Adnate", "Soldevi Adnate", "Soldevi Heretic", "Soldevi Heretic", "Soldevi Sage", "Soldevi Sage", "Soldevi Sentry", "Soldevi Sentry", "Soldevi Steam Beast", "Soldevi Steam Beast", "Stench of Decay", "Stench of Decay", "Storm Crow", "Storm Crow", "Storm Shaman", "Storm Shaman", "Swamp Mosquito", "Swamp Mosquito", "Taste of Paradise", "Taste of Paradise", "Undergrowth", "Undergrowth", "Varchild's Crusader", "Varchild's Crusader", "Veteran's Voice", "Veteran's Voice", "Viscerid Armor", "Viscerid Armor", "Whip Vine", "Whip Vine", "Wild Aesthir", "Wild Aesthir", "Yavimaya Ancients", "Yavimaya Ancients");
		this.addCards(Rarity.UNCOMMON, "Balduvian Dead", "Bounty of the Hunt", "Browse", "Burnout", "Contagion", "Death Spark", "Diseased Vermin", "Elvish Bard", "Elvish Spirit Guide", "Energy Arc", "Force of Will", "Hail Storm", "Inheritance", "Juniper Order Advocate", "Kjeldoran Home Guard", "Krovikan Plague", "Lim-Dûl's Paladin", "Lim-Dûl's Vault", "Mishra's Groundbreaker", "Misinformation", "Mystic Compass", "Nature's Blessing", "Nature's Chosen", "Pillage", "Primitive Justice", "Pyrokinesis", "Scarab of the Unseen", "Scars of the Veteran", "School of the Unseen", "Seasoned Tactician", "Shield Sphere", "Sol Grail", "Soldier of Fortune", "Spiny Starfish", "Storm Elemental", "Stromgald Spy", "Suffocation", "Surge of Strength", "Unlikely Alliance", "Urza's Engine", "Viscerid Drone", "Whirling Catapult", "Yavimaya Ants");
		this.addCards(Rarity.RARE, "Ashnod's Cylix", "Balduvian Horde", "Balduvian Trading Post", "Chaos Harlequin", "Diminishing Returns", "Dystopia", "Exile", "Fatal Lore", "Floodwater Dam", "Gargantuan Gorilla", "Gustha's Scepter", "Heart of Yavimaya", "Helm of Obedience", "Ivory Gargoyle", "Kaysa", "Keeper of Tresserhorn", "Kjeldoran Outpost", "Krovikan Horror", "Lake of the Dead", "Library of Lat-Nam", "Lodestone Bauble", "Lord of Tresserhorn", "Misfortune", "Nature's Wrath", "Omen of Fire", "Phantasmal Sphere", "Phelddagrif", "Phyrexian Devourer", "Phyrexian Portal", "Ritual of the Machine", "Rogue Skycaptain", "Royal Decree", "Sheltered Valley", "Soldevi Digger", "Soldevi Excavations", "Splintering Wind", "Storm Cauldron", "Sustaining Spirit", "Sworn Defender", "Thawing Glaciers", "Thought Lash", "Tidal Control", "Tornado", "Varchild's War-Riders", "Wandering Mage", "Winter's Night");
	}
}
