package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Archenemy")
public final class Archenemy extends SimpleExpansion
{
	public Archenemy()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "A Display of My Dark Power", "AEther Spellbomb", "Agony Warp", "All Shall Smolder in My Wake", "All in Good Time", "Approach My Molten Realm", "Architects of Will", "Armadillo Cloak", "Azorius Signet", "Barren Moor", "Battering Craghorn", "Behold the Power of Destruction", "Bog Witch", "Branching Bolt", "Chandra's Outrage", "Choose Your Champion", "Colossal Might", "Dance, Pathetic Marionette", "Dimir Signet", "Dragon Breath", "Dragon Fodder", "Dregscape Zombie", "Embrace My Diabolical Vision", "Ethersworn Shieldmage", "Every Hope Shall Vanish", "Every Last Vestige Shall Rot", "Evil Comes to Fruition", "Feed the Machine", "Fertilid", "Festering Goblin", "Fieldmist Borderpost", "Fierce Empath", "Fog", "Gathan Raiders", "Gleeful Sabotage", "Gruul Signet", "I Bask in Your Silent Awe", "I Call on the Ancient Magics", "I Delight in Your Convulsions", "I Know All, I See All", "Ignite the Cloneforge!", "Infectious Horror", "Into the Earthen Maw", "Introductions Are in Order", "Khalni Garden", "Know Naught but Fire", "Krosan Tusker", "Leaf Gilder", "Look Skyward and Despair", "May Civilization Collapse", "Mistvein Borderpost", "Mortal Flesh Is Weak", "My Crushing Masterstroke", "My Genius Knows No Bounds", "My Undead Horde Awakens", "My Wish Is Your Command", "Nature Demands an Offering", "Nature Shields Its Own", "Nothing Can Stop Me Now", "Obelisk of Esper", "Oblivion Ring", "Only Blood Ends Your Nightmares", "Pale Recluse", "Plummet", "Rakdos Carnarium", "Rakdos Signet", "Rancor", "Realms Befitting My Majesty", "Roots of All Evil", "Rotted Ones, Lay Siege", "Sakura-Tribe Elder", "Sanctum Gargoyle", "Secluded Steppe", "Seething Song", "Shinen of Life's Roar", "Sign in Blood", "Skirk Commando", "Skirk Marauder", "Spider Umbra", "Surrender Your Thoughts", "Terminate", "Terramorphic Expanse", "The Dead Shall Serve", "The Fate of the Flammable", "The Iron Guardian Stirs", "The Pieces Are Coming Together", "The Very Soil Shall Shake", "Tooth, Claw, and Tail", "Tranquil Thicket", "Twisted Abomination", "Unmake", "Urborg Syphon-Mage", "Wall of Roots", "Which of You Burns Brightest?", "Wickerbough Elder", "Your Fate Is Thrice Sealed", "Your Puny Minds Cannot Fathom", "Your Will Is Not Your Own");
		this.addCards(Rarity.UNCOMMON, "Artisan of Kozilek", "Batwing Brume", "Bituminous Blast", "Breath of Darigaaz", "Corpse Connoisseur", "Dragon Whelp", "Dragonspeaker Shaman", "Dreamstone Hedron", "Everflowing Chalice", "Fireball", "Fires of Yavimaya", "Furnace Whelp", "Graypelt Refuge", "Harmonize", "Heroes' Reunion", "Hunting Moa", "Incremental Blight", "Inferno Trap", "Infest", "Juggernaut", "Kazandu Refuge", "Krosan Verge", "Lightning Greaves", "Llanowar Reborn", "Makeshift Mannequin", "Metallurgeon", "Nantuko Monastery", "Path to Exile", "Rakdos Guildmage", "Reanimate", "Reassembling Skeleton", "Savage Twister", "Selesnya Guildmage", "Shriekmaw", "Skullcage", "Sorcerer's Strongbox", "Spin into Myth", "Sun Droplet", "Synod Centurion", "Synod Sanctum", "Thran Dynamo", "Thunderstaff", "Torrent of Souls", "Unbender Tine", "Vitu-Ghazi, the City-Tree", "Volcanic Fallout", "Watchwolf", "Wax // Wane", "Yavimaya Dryad", "Zombie Infestation", "Zombify");
		this.addCards(Rarity.RARE, "Avatar of Discord", "Avatar of Woe", "Beacon of Unrest", "Cemetery Reaper", "Chameleon Colossus", "Duplicant", "Extractor Demon", "Feral Hydra", "Flameblast Dragon", "Forgotten Ancient", "Hellkite Charger", "Imperial Hellkite", "Kaervek the Merciless", "Kamahl, Fist of Krosa", "Kilnmouth Dragon", "Leonin Abunas", "Lodestone Golem", "Magister Sphinx", "March of the Machines", "Master Transmuter", "Memnarch", "Molimo, Maro-Sorcerer", "Mosswort Bridge", "Primal Command", "Ryusei, the Falling Star", "Scion of Darkness", "Sundering Titan", "Taurean Mauler", "Thelonite Hermit", "Two-Headed Dragon", "Vampiric Dragon", "Verdeloth the Ancient");
	}
}
