package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Avacyn Restored")
public final class AvacynRestored extends SimpleExpansion
{
	public AvacynRestored()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "Abundant Growth", "Alchemist's Apprentice", "Amass the Components", "Angel's Mercy", "Angelic Wall", "Banners Raised", "Battle Hymn", "Bladed Bracers", "Bloodflow Connoisseur", "Bone Splinters", "Borderland Ranger", "Butcher Ghoul", "Call to Serve", "Cathedral Sanctifier", "Cloudshift", "Crippling Chill", "Crypt Creeper", "Cursebreak", "Dangerous Wager", "Death Wind", "Defang", "Demolish", "Diregraf Escort", "Dreadwaters", "Driver of the Dead", "Elgaud Shieldmate", "Essence Harvest", "Farbog Explorer", "Fervent Cathar", "Fleeting Distraction", "Flowering Lumberknot", "Galvanic Alchemist", "Geist Snatch", "Geist Trappers", "Ghostform", "Ghostly Flicker", "Ghoulflesh", "Grave Exchange", "Grounded", "Gryff Vanguard", "Guise of Fire", "Hanweir Lancer", "Havengul Skaab", "Heirs of Stromkirk", "Hunted Ghoul", "Joint Assault", "Kruin Striker", "Lair Delve", "Leap of Faith", "Mad Prophet", "Malicious Intent", "Mental Agony", "Midnight Duelist", "Midvast Protector", "Mist Raven", "Moonlight Geist", "Moorland Inquisitor", "Narstad Scrapper", "Natural End", "Necrobite", "Nettle Swine", "Nightshade Peddler", "Outwit", "Pathbreaker Wurm", "Peel from Reality", "Pillar of Flame", "Polluted Dead", "Predator's Gambit", "Raging Poltergeist", "Renegade Demon", "Righteous Blow", "Riot Ringleader", "Rotcrown Ghoul", "Scalding Devil", "Scrapskin Drake", "Scroll of Avacyn", "Scroll of Griselbrand", "Searchlight Geist", "Seraph Sanctuary", "Seraph of Dawn", "Sheltering Word", "Snare the Skies", "Somberwald Vigilante", "Soulcage Fiend", "Spectral Gateguards", "Spectral Prison", "Terrifying Presence", "Thatcher Revolt", "Thraben Valiant", "Thunderbolt", "Timberland Guide", "Trusted Forcemage", "Uncanny Speed", "Undead Executioner", "Unhallowed Pact", "Vanguard's Shield", "Voice of the Provinces", "Wandering Wolf", "Wildwood Geist", "Wingcrafter", "Zealous Strike");
		this.addCards(Rarity.UNCOMMON, "Aggravate", "Angel's Tomb", "Angelic Armaments", "Appetite for Brains", "Archangel", "Banishing Stroke", "Barter in Blood", "Blessings of Nature", "Blood Artist", "Bower Passage", "Builder's Blessing", "Commander's Authority", "Corpse Traders", "Defy Death", "Demonic Taskmaster", "Devout Chaplain", "Druid's Familiar", "Eaten by Spiders", "Emancipation Angel", "Evernight Shade", "Falkenrath Exterminator", "Favorable Winds", "Fettergeist", "Gang of Devils", "Ghostly Touch", "Gloomwidow", "Goldnight Commander", "Goldnight Redeemer", "Haunted Guardian", "Havengul Vampire", "Holy Justiciar", "Homicidal Seclusion", "Howlgeist", "Human Frailty", "Into the Void", "Kessig Malcontents", "Latch Seeker", "Lightning Mauler", "Lightning Prowess", "Maalfeld Twins", "Marrow Bats", "Mass Appeal", "Nearheath Pilgrim", "Nephalia Smuggler", "Rain of Thorns", "Rush of Blood", "Second Guess", "Stern Mentor", "Stonewright", "Tandem Lookout", "Thunderous Wrath", "Tormentor's Trident", "Triumph of Cruelty", "Triumph of Ferocity", "Vanishment", "Vessel of Endless Rest", "Vigilante Justice", "Vorstclaw", "Wolfir Avenger", "Yew Spirit");
		this.addCards(Rarity.RARE, "Alchemist's Refuge", "Angel of Glory's Rise", "Angel of Jubilation", "Arcane Melee", "Archwing Dragon", "Burn at the Stake", "Captain of the Mists", "Cathars' Crusade", "Cavern of Souls", "Champion of Lambholt", "Conjurer's Closet", "Dark Impostor", "Deadeye Navigator", "Demonic Rising", "Demonlord of Ashmouth", "Descendants' Path", "Desolate Lighthouse", "Devastation Tide", "Divine Deflection", "Dread Slaver", "Druids' Repository", "Dual Casting", "Exquisite Blood", "Gallows at Willow Hill", "Gloom Surgeon", "Harvester of Souls", "Herald of War", "Hound of Griselbrand", "Infinite Reflection", "Killing Wave", "Lone Revenant", "Lunar Mystic", "Moonsilver Spear", "Otherworld Atlas", "Reforge the Soul", "Restoration Angel", "Revenge of the Hunted", "Riders of Gavony", "Rite of Ruin", "Silverblade Paladin", "Slayers' Stronghold", "Somberwald Sage", "Soul of the Harvest", "Spirit Away", "Stolen Goods", "Terminus", "Treacherous Pit-Dweller", "Tyrant of Discord", "Ulvenwald Tracker", "Vexing Devil", "Wild Defiance", "Wolfir Silverheart", "Zealous Conscripts");
		this.addCards(Rarity.MYTHIC, "Avacyn, Angel of Hope", "Bonfire of the Damned", "Bruna, Light of Alabaster", "Craterhoof Behemoth", "Descent into Madness", "Entreat the Angels", "Gisela, Blade of Goldnight", "Griselbrand", "Malignus", "Misthollow Griffin", "Primal Surge", "Sigarda, Host of Herons", "Tamiyo, the Moon Sage", "Temporal Mastery", "Tibalt, the Fiend-Blooded");
	}
}
