package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Betrayers of Kamigawa")
public final class BetrayersOfKamigawa extends SimpleExpansion
{
	public BetrayersOfKamigawa()
	{
		super();

		this.addCards(Rarity.COMMON, "Akki Blizzard-Herder", "Bile Urchin", "Blademane Baku", "Blessing of Leeches", "Call for Blood", "Child of Thorns", "Crack the Earth", "Crawling Filth", "First Volley", "Floodbringer", "Frost Ogre", "Frostling", "Gnarled Mass", "Goblin Cohort", "Harbinger of Spring", "Heart of Light", "Horobi's Whisper", "Hundred-Talon Strike", "Ire of Kaminari", "Kami of False Hope", "Kami of Tattered Shoji", "Kumano's Blessing", "Matsu-Tribe Sniper", "Mending Hands", "Minamo's Meddling", "Mistblade Shinobi", "Moonlit Strider", "Ninja of the Deep Hours", "Okiba-Gang Shinobi", "Petalmane Baku", "Phantom Wings", "Psychic Spear", "Quillmane Baku", "Ribbons of the Reikai", "Roar of Jukai", "Sakura-Tribe Springcaller", "Scaled Hulk", "Shimmering Glasskite", "Shinka Gatekeeper", "Silverstorm Samurai", "Skullmane Baku", "Skullsnatcher", "Split-Tail Miko", "Stir the Grave", "Takeno's Cavalry", "Takenuma Bleeder", "Teardrop Kami", "Terashi's Grasp", "Toils of Night and Day", "Torrent of Stone", "Traproot Kami", "Uproot", "Veil of Secrecy", "Vital Surge", "Waxmane Baku");
		this.addCards(Rarity.UNCOMMON, "Akki Raider", "Ashen Monstrosity", "Aura Barbs", "Blinding Powder", "Body of Jukai", "Budoka Pupil", "Callow Jushi", "Cunning Bandit", "Empty-Shrine Kannushi", "Eradicate", "Faithful Squire", "Flames of the Blood Hand", "Forked-Branch Garami", "Genju of the Cedars", "Genju of the Falls", "Genju of the Fens", "Genju of the Fields", "Genju of the Spires", "Gods' Eye, Gate to the Reikai", "Heed the Mists", "Hired Muscle", "Indebted Samurai", "Jetting Glasskite", "Kaijin of the Vanishing Touch", "Kami of the Honored Dead", "Kitsune Palliator", "Lifespinner", "Loam Dweller", "Mark of Sakiko", "Mark of the Oni", "Minamo Sightbender", "Nezumi Shadow-Watcher", "Ogre Marauder", "Ogre Recluse", "Overblaze", "Pus Kami", "Quash", "Ronin Cliffrider", "Ronin Warclub", "Scour", "Scourge of Numai", "Shuko", "Shuriken", "Soratami Mindsweeper", "Sosuke's Summons", "Sowing Salt", "Splinter", "Stream of Consciousness", "Tallowisp", "Terashi's Verdict", "Three Tragedies", "Throat Slitter", "Unchecked Growth", "Walker of Secret Ways", "Ward of Piety");
		this.addCards(Rarity.RARE, "Baku Altar", "Blazing Shoal", "Chisei, Heart of Oceans", "Clash of Realities", "Day of Destiny", "Disrupting Shoal", "Enshrined Memories", "Final Judgment", "Fumiko the Lowblood", "Genju of the Realm", "Goryo's Vengeance", "Heartless Hidetsugu", "Hero's Demise", "Higure, the Still Wind", "Hokori, Dust Drinker", "In the Web of War", "Ink-Eyes, Servant of Oni", "Isao, Enlightened Bushi", "Ishi-Ishi, Akki Crackshot", "Iwamori of the Open Fist", "Kentaro, the Smiling Cat", "Kira, Great Glass-Spinner", "Kodama of the Center Tree", "Kyoki, Sanity's Eclipse", "Lifegift", "Mannichi, the Fevered Dream", "Mirror Gallery", "Neko-Te", "Nourishing Shoal", "Opal-Eye, Konda's Yojimbo", "Orb of Dreams", "Ornate Kanzashi", "Oyobi, Who Split the Heavens", "Patron of the Akki", "Patron of the Kitsune", "Patron of the Moon", "Patron of the Nezumi", "Patron of the Orochi", "Reduce to Dreams", "Sakiko, Mother of Summer", "Shining Shoal", "Shirei, Shizo's Caretaker", "Shizuko, Caller of Autumn", "Sickening Shoal", "Slumbering Tora", "Sway of the Stars", "Tendo Ice Bridge", "That Which Was Taken", "Threads of Disloyalty", "Tomorrow, Azami's Familiar", "Toshiro Umezawa", "Twist Allegiance", "Umezawa's Jitte", "Yomiji, Who Bars the Way", "Yukora, the Prisoner");
	}
}
