package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Born of the Gods")
public final class BornOfTheGods extends SimpleExpansion
{
	public BornOfTheGods()
	{
		super();

		this.addCards(Rarity.COMMON, "Akroan Skyguard", "Aspect of Hydra", "Asphyxiate", "Bolt of Keranos", "Charging Badger", "Chorus of the Tides", "Claim of Erebos", "Crypsis", "Culling Mark", "Cyclops of One-Eyed Pass", "Deepwater Hypnotist", "Divination", "Elite Skirmisher", "Ephara's Radiance", "Epiphany Storm", "Evanescent Intellect", "Excoriate", "Eye Gouge", "Fall of the Hammer", "Fearsome Temper", "Felhide Brawler", "Floodtide Serpent", "Forsaken Drifters", "Great Hart", "Griffin Dreamfinder", "Grisly Transformation", "Hold at Bay", "Impetuous Sunchaser", "Karametra's Favor", "Kragma Butcher", "Loyal Pegasus", "Marshmist Titan", "Mortal's Ardor", "Mortal's Resolve", "Necrobite", "Nullify", "Nyxborn Eidolon", "Nyxborn Rollicker", "Nyxborn Shieldmate", "Nyxborn Triton", "Nyxborn Wolf", "Oreskos Sun Guide", "Pharagax Giant", "Pheres-Band Tromper", "Reckless Reveler", "Retraction Helix", "Revoke Existence", "Rise to the Challenge", "Satyr Wayfinder", "Scouring Sands", "Servant of Tymaret", "Setessan Oathsworn", "Setessan Starbreaker", "Snake of the Golden Grove", "Sphinx's Disciple", "Stratus Walk", "Sudden Storm", "Swordwise Centaur", "Warchanter of Mogis", "Weight of the Underworld");
		this.addCards(Rarity.UNCOMMON, "Acolyte's Reward", "Aerie Worshippers", "Akroan Conscriptor", "Akroan Phalanx", "Archetype of Aggression", "Archetype of Courage", "Archetype of Endurance", "Archetype of Finality", "Archetype of Imagination", "Ashiok's Adept", "Bile Blight", "Black Oak of Odunos", "Dawn to Dusk", "Drown in Sorrow", "Ephara's Enlightenment", "Eternity Snare", "Everflame Eidolon", "Fanatic of Xenagos", "Flitterstep Eidolon", "Forlorn Pseudamma", "Ghostblade Eidolon", "Glimpse the Sun God", "God-Favored General", "Gorgon's Head", "Graverobber Spider", "Kiora's Follower", "Kraken of the Straits", "Lightning Volley", "Meletis Astronomer", "Mischief and Mayhem", "Nessian Demolok", "Noble Quarry", "Odunos River Trawler", "Oracle's Insight", "Ornitharch", "Peregrination", "Pheres-Band Raiders", "Pillar of War", "Pinnacle of Rage", "Ragemonger", "Raised by Wolves", "Reap What Is Sown", "Sanguimancy", "Satyr Nyx-Smith", "Searing Blood", "Shrike Harpy", "Siren Song Lyre", "Siren of the Fanged Coast", "Siren of the Silent Song", "Skyreaping", "Spiteful Returned", "Springleaf Drum", "Stormcaller of Keranos", "Sunbond", "Thassa's Rebuff", "Thunder Brute", "Thunderous Might", "Unravel the AEther", "Vanguard of Brimaz", "Vortex Elemental");
		this.addCards(Rarity.RARE, "Arbiter of the Ideal", "Astral Cornucopia", "Courser of Kruphix", "Eater of Hope", "Eidolon of Countless Battles", "Fate Unraveler", "Fated Conflagration", "Fated Infatuation", "Fated Intervention", "Fated Retribution", "Fated Return", "Felhide Spiritbinder", "Forgestoker Dragon", "Gild", "Herald of Torment", "Hero of Iroas", "Hero of Leina Tower", "Heroes' Podium", "Hunter's Prowess", "Mindreaver", "Nessian Wilds Ravager", "Oracle of Bones", "Pain Seer", "Perplexing Chimera", "Plea for Guidance", "Satyr Firedancer", "Scourge of Skola Vale", "Silent Sentinel", "Spirit of the Labyrinth", "Temple of Enlightenment", "Temple of Malice", "Temple of Plenty", "Tromokratis", "Whelming Wave", "Whims of the Fates");
		this.addCards(Rarity.MYTHIC, "Brimaz, King of Oreskos", "Champion of Stray Souls", "Chromanticore", "Ephara, God of the Polis", "Flame-Wreathed Phoenix", "Karametra, God of Harvests", "Kiora, the Crashing Wave", "Mogis, God of Slaughter", "Phenax, God of Deception", "Xenagos, God of Revels");
	}
}
