package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Champions of Kamigawa")
public final class ChampionsOfKamigawa extends SimpleExpansion
{
	public ChampionsOfKamigawa()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Akki Avalanchers", "Akki Rockspeaker", "Ashen-Skin Zubera", "Battle-Mad Ronin", "Befoul", "Blessed Breath", "Brutal Deceiver", "Burr Grafter", "Cage of Hands", "Call to Glory", "Callous Deceiver", "Commune with Nature", "Consuming Vortex", "Counsel of the Soratami", "Cruel Deceiver", "Crushing Pain", "Cursed Ronin", "Deathcurse Ogre", "Desperate Ritual", "Devoted Retainer", "Devouring Greed", "Devouring Rage", "Distress", "Dripping-Tongue Zubera", "Ember-Fist Zubera", "Ethereal Haze", "Eye of Nowhere", "Feral Deceiver", "Field of Reality", "Floating-Dream Zubera", "Frostwielder", "Gibbering Kami", "Glacial Ray", "Harsh Deceiver", "Hearth Kami", "Hisoka's Defiance", "Hisoka's Guard", "Humble Budoka", "Hundred-Talon Kami", "Indomitable Will", "Joyous Respite", "Jukai Messenger", "Kabuto Moth", "Kami of Ancient Law", "Kami of Fire's Roar", "Kami of Twisted Reflection", "Kami of the Hunt", "Kami of the Painted Road", "Kami of the Waning Moon", "Kashi-Tribe Warriors", "Kitsune Blademaster", "Kitsune Diviner", "Kitsune Healer", "Kitsune Riftwalker", "Kodama's Might", "Kodama's Reach", "Lantern Kami", "Lava Spike", "Lifted by Clouds", "Matsu-Tribe Decoy", "Midnight Covenant", "Moss Kami", "Mothrider Samurai", "Mystic Restraints", "Nezumi Cutthroat", "Nezumi Ronin", "Order of the Sacred Bell", "Orochi Leafcaller", "Orochi Ranger", "Orochi Sustainer", "Peer Through Depths", "Pious Kitsune", "Psychic Puppetry", "Pull Under", "Quiet Purity", "Rag Dealer", "Ragged Veins", "Reach Through Mists", "Rend Flesh", "Rend Spirit", "River Kaijin", "Ronin Houndmaster", "Sakura-Tribe Elder", "Scuttling Death", "Serpent Skin", "Sift Through Sands", "Silent-Chant Zubera", "Sokenzan Bruiser", "Soratami Cloudskater", "Soratami Mirror-Guard", "Soratami Rainshaper", "Soul of Magma", "Soulless Revival", "Stone Rain", "Teller of Tales", "Terashi's Cry", "Thoughtbind", "Uncontrollable Anger", "Unearthly Blizzard", "Unnatural Speed", "Venerable Kumo", "Vigilance", "Villainous Ogre", "Vine Kami", "Waking Nightmare", "Wandering Ones", "Wear Away", "Wicked Akuba", "Yamabushi's Flame", "Yamabushi's Storm");
		this.addCards(Rarity.UNCOMMON, "Akki Coalflinger", "Akki Underminer", "Aura of Dominion", "Blind with Anger", "Blood Rites", "Blood Speaker", "Bloodthirsty Ogre", "Brothers Yamazaki", "Brothers Yamazaki", "Bushi Tenderfoot", "Candles' Glow", "Cleanfall", "Cloudcrest Lake", "Cut the Tethers", "Dampen Thought", "Dance of Shadows", "Earthshaker", "Eerie Procession", "Feast of Worms", "Gale Force", "Ghostly Prison", "Graceful Adept", "Guardian of Solitude", "Gutwrencher Oni", "Hana Kami", "Hanabi Blast", "Hankyu", "Hideous Laughter", "Hinder", "Honden of Cleansing Fire", "Honden of Infinite Rage", "Honden of Life's Web", "Honden of Night's Reach", "Honden of Seeing Winds", "Honor-Worn Shaku", "Horizon Seed", "Initiate of Blood", "Innocence Kami", "Jade Idol", "Kami of Lunacy", "Kami of Old Stone", "Kami of the Palace Fields", "Kashi-Tribe Reaver", "Konda's Hatamoto", "Kumano's Pupils", "Lantern-Lit Graveyard", "Lure", "Mana Seism", "Nagao, Bound by Honor", "Nezumi Bone-Reader", "Nezumi Graverobber", "Nine-Ringed Bo", "No-Dachi", "Numai Outcast", "Oni Possession", "Orbweaver Kumo", "Ore Gorger", "Orochi Eggwatcher", "Otherworldly Journey", "Pain Kami", "Painwracker Oni", "Petals of Insight", "Pinecrest Ridge", "Reciprocate", "Reito Lantern", "Rootrunner", "Sachi, Daughter of Seshiro", "Samurai Enforcers", "Samurai of the Pale Curtain", "Sensei's Divining Top", "Sideswipe", "Sire of the Storm", "Soilshaper", "Soratami Mirror-Mage", "Soratami Savant", "Soratami Seer", "Sosuke, Son of Seshiro", "Squelch", "Strange Inversion", "Strength of Cedars", "Struggle for Sanity", "Student of Elements", "Swallowing Plague", "Tenza, Godo's Maul", "Thief of Hope", "Thousand-legged Kami", "Time of Need", "Tranquil Garden", "Waterveil Cavern");
		this.addCards(Rarity.RARE, "Akki Lavarunner", "Azami, Lady of Scrolls", "Azusa, Lost but Seeking", "Ben-Ben, Akki Hermit", "Boseiju, Who Shelters All", "Budoka Gardener", "Cranial Extraction", "Dosan the Falling Leaf", "Eiganjo Castle", "Eight-and-a-Half-Tails", "Forbidden Orchard", "General's Kabuto", "Gifts Ungiven", "Glimpse of Nature", "Godo, Bandit Warlord", "Hair-Strung Koto", "Hall of the Bandit Lord", "He Who Hungers", "Heartbeat of Spring", "Hikari, Twilight Guardian", "Hisoka, Minamo Sensei", "Hold the Line", "Horobi, Death's Wail", "Imi Statue", "Iname, Death Aspect", "Iname, Life Aspect", "Isamaru, Hound of Konda", "Journeyer's Kite", "Jugan, the Rising Star", "Junkyo Bell", "Jushi Apprentice", "Keiga, the Tide Star", "Kiki-Jiki, Mirror Breaker", "Kiku, Night's Flower", "Kitsune Mystic", "Kodama of the North Tree", "Kodama of the South Tree", "Kokusho, the Evening Star", "Konda's Banner", "Konda, Lord of Eiganjo", "Kumano, Master Yamabushi", "Kuro, Pitlord", "Kusari-Gama", "Long-Forgotten Gohei", "Marrow-Gnawer", "Masako the Humorless", "Meloku the Clouded Mirror", "Minamo, School at Water's Edge", "Mindblaze", "Moonring Mirror", "Myojin of Cleansing Fire", "Myojin of Infinite Rage", "Myojin of Life's Web", "Myojin of Night's Reach", "Myojin of Seeing Winds", "Nature's Will", "Nezumi Shortfang", "Night Dealings", "Night of Souls' Betrayal", "Oathkeeper, Takeno's Daisho", "Okina, Temple to the Grandfathers", "Orochi Hatchery", "Part the Veil", "Reverse the Sands", "Reweave", "Ryusei, the Falling Star", "Seizan, Perverter of Truth", "Sensei Golden-Tail", "Seshiro the Anointed", "Shell of the Last Kappa", "Shimatsu the Bloodcloaked", "Shinka, the Bloodsoaked Keep", "Shisato, Whispering Hunter", "Shizo, Death's Storehouse", "Soulblast", "Swirl the Mists", "Takeno, Samurai General", "Tatsumasa, the Dragon's Fang", "The Unspeakable", "Through the Breach", "Tide of War", "Time Stop", "Uba Mask", "Untaidake, the Cloud Keeper", "Uyo, Silent Prophet", "Vassal's Duty", "Yosei, the Morning Star", "Zo-Zu the Punisher");
	}
}
