package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Classic Sixth Edition")
public final class ClassicSixthEdition extends SimpleExpansion
{
	public ClassicSixthEdition()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Anaba Bodyguard", "Anaba Shaman", "Armored Pegasus", "Balduvian Barbarians", "Blood Pet", "Bog Imp", "Bog Rats", "Boomerang", "Cat Warriors", "Circle of Protection: Black", "Circle of Protection: Blue", "Circle of Protection: Green", "Circle of Protection: Red", "Circle of Protection: White", "Coercion", "Counterspell", "D'Avenant Archer", "Disenchant", "Dream Cache", "Drudge Skeletons", "Dry Spell", "Ekundu Griffin", "Elven Cache", "Enfeeblement", "Fatal Blow", "Fear", "Feast of the Unicorn", "Feral Shadow", "Firebreathing", "Fit of Rage", "Flame Spirit", "Flight", "Fog", "Fog Elemental", "Fyndhorn Brownie", "Gaseous Form", "Giant Growth", "Giant Spider", "Giant Strength", "Goblin Digging Team", "Goblin Elite Infantry", "Goblin Hero", "Gorilla Chieftain", "Gravedigger", "Grizzly Bears", "Healing Salve", "Hero's Resolve", "Horned Turtle", "Howl from Beyond", "Infantry Veteran", "Inspiration", "Kjeldoran Dead", "Lightning Blast", "Llanowar Elves", "Lost Soul", "Memory Lapse", "Merfolk of the Pearl Trident", "Mesa Falcon", "Mountain Goat", "Pacifism", "Painful Memories", "Panther Warriors", "Phantasmal Terrain", "Pradesh Gypsies", "Prodigal Sorcerer", "Psychic Venom", "Pyrotechnics", "Python", "Raging Goblin", "Raise Dead", "Rampant Growth", "Razortooth Rats", "Redwood Treefolk", "Regal Unicorn", "Regeneration", "Remedy", "Remove Soul", "Resistance Fighter", "Sabretooth Tiger", "Sage Owl", "Samite Healer", "Scaled Wurm", "Scathe Zombies", "Sea Monster", "Shanodin Dryads", "Shatter", "Shock", "Spell Blast", "Spitting Earth", "Stalking Tiger", "Standing Troops", "Stone Rain", "Storm Crow", "Stream of Life", "Syphon Soul", "Talruum Minotaur", "Terror", "Tidal Surge", "Trained Armodon", "Tranquility", "Tremor", "Tundra Wolves", "Unsummon", "Venerable Monk", "Viashino Warrior", "Vitalize", "Vodalian Soldiers", "Warrior's Honor", "Wild Growth", "Wind Drake");
		this.addCards(Rarity.UNCOMMON, "AEther Flash", "Abduction", "Abyssal Specter", "Agonizing Memories", "Air Elemental", "Ardent Militia", "Ashnod's Altar", "Blaze", "Blight", "Blighted Shaman", "Bog Wraith", "Boil", "Browse", "Burrowing", "Castle", "Charcoal Diamond", "Chill", "Conquer", "Creeping Mold", "Crystal Rod", "Crystal Vein", "Daraja Griffin", "Divine Transformation", "Dragon Mask", "Dread of Night", "Dwarven Ruins", "Ebon Stronghold", "Elven Riders", "Enlightened Tutor", "Evil Eye of Orms-by-Gore", "Fallow Earth", "Familiar Ground", "Femeref Archers", "Fire Diamond", "Fire Elemental", "Flashfires", "Fountain of Youth", "Fyndhorn Elder", "Glacial Wall", "Glasses of Urza", "Goblin Recruiter", "Gravebane Zombie", "Harmattan Efreet", "Havenwood Battleground", "Heavy Ballista", "Hidden Horror", "Hulking Cyclops", "Insight", "Iron Star", "Ivory Cup", "Kismet", "Lead Golem", "Leshrac's Rite", "Light of Day", "Longbow Archer", "Lure", "Mana Prism", "Marble Diamond", "Mind Warp", "Mischievous Poltergeist", "Moss Diamond", "Mystic Compass", "Mystical Tutor", "Obsianus Golem", "Orcish Artillery", "Orcish Oriflamme", "Ornithopter", "Patagia Golem", "Perish", "Pestilence", "Phantom Warrior", "Phyrexian Vault", "Pillage", "Power Sink", "Prosperity", "Radjan Spirit", "Relearn", "Reprisal", "River Boa", "Rod of Ruin", "Ruins of Trokair", "Segovian Leviathan", "Serra's Blessing", "Skull Catapult", "Sky Diamond", "Soldevi Sage", "Soul Net", "Spirit Link", "Spitting Drake", "Staunch Defenders", "Strands of Night", "Stupor", "Summer Bloom", "Svyelunite Temple", "Thicket Basilisk", "Throne of Bone", "Uktabi Orangutan", "Unseen Walker", "Untamed Wilds", "Unyaro Griffin", "Vertigo", "Volcanic Geyser", "Wall of Air", "Wall of Fire", "Wall of Swords", "Warmth", "Warthog", "Wind Spirit", "Wooden Sphere", "Worldly Tutor");
		this.addCards(Rarity.RARE, "Abyssal Hunter", "Adarkar Wastes", "Aladdin's Ring", "Amber Prison", "Ancestral Memories", "Animate Wall", "Ankh of Mishra", "Archangel", "Armageddon", "Ashen Powder", "Balduvian Horde", "Birds of Paradise", "Bottle of Suleiman", "Brushland", "Call of the Wild", "Celestial Dawn", "City of Brass", "Crimson Hellkite", "Crusade", "Cursed Totem", "Dancing Scimitar", "Daring Apprentice", "Deflection", "Dense Foliage", "Derelor", "Desertion", "Diminishing Returns", "Dingus Egg", "Disrupting Scepter", "Doomsday", "Dragon Engine", "Early Harvest", "Earthquake", "Elder Druid", "Elvish Archers", "Ethereal Champion", "Exile", "Fallen Angel", "Fervor", "Final Fortune", "Flash", "Flying Carpet", "Forbidden Crypt", "Forget", "Goblin King", "Goblin Warrens", "Greed", "Grinning Totem", "Hammer of Bogardan", "Hecatomb", "Howling Mine", "Hurricane", "Icatian Town", "Illicit Auction", "Infernal Contract", "Inferno", "Jade Monolith", "Jalum Tome", "Jayemdae Tome", "Jokulhaups", "Juxtapose", "Karplusan Forest", "Kjeldoran Royal Guard", "Library of Lat-Nam", "Living Lands", "Lord of Atlantis", "Mana Short", "Manabarbs", "Maro", "Meekstone", "Millstone", "Nature's Resurgence", "Necrosavant", "Nightmare", "Order of the Sacred Torch", "Pearl Dragon", "Pentagram of the Ages", "Polymorph", "Primal Clay", "Psychic Transfer", "Rag Man", "Recall", "Reckless Embermage", "Relentless Assault", "Reverse Damage", "Rowen", "Sengir Autocrat", "Serenity", "Shatterstorm", "Sibilant Spirit", "Snake Basket", "Storm Cauldron", "Stromgald Cabal", "Sulfurous Springs", "Sunweb", "Tariff", "Teferi's Puzzle Box", "The Hive", "Tranquil Grove", "Uktabi Wildcats", "Underground River", "Vampiric Tutor", "Verduran Enchantress", "Volcanic Dragon", "Waiting in the Weeds", "Wand of Denial", "Wrath of God", "Wyluli Wolf", "Zombie Master", "Zur's Weirding");
	}
}
