package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Commander 2013 Edition")
public final class Commander2013Edition extends SimpleExpansion
{
	public Commander2013Edition()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "Arcane Denial", "Armillary Sphere", "Azorius Chancery", "Azorius Guildgate", "Bant Panorama", "Barren Moor", "Bojuka Bog", "Boros Garrison", "Boros Guildgate", "Command Tower", "Cultivate", "Deep Analysis", "Dimir Guildgate", "Dirge of Dread", "Drifting Meadow", "Elvish Skysweeper", "Esper Panorama", "Evolving Wilds", "Farhaven Elf", "Fissure Vent", "Forgotten Cave", "Golgari Guildgate", "Golgari Rot Farm", "Grazing Gladehart", "Grixis Panorama", "Gruul Guildgate", "Hull Breach", "Izzet Boilerworks", "Izzet Guildgate", "Jund Panorama", "Khalni Garden", "Krosan Tusker", "Lonely Sandbar", "Mnemonic Wall", "Mold Shambler", "Naya Panorama", "Night Soil", "Nightscape Familiar", "Nihil Spellbomb", "Obelisk of Esper", "Obelisk of Grixis", "Obelisk of Jund", "Opal Palace", "Orzhov Basilica", "Orzhov Guildgate", "Pilgrim's Eye", "Presence of Gond", "Pristine Talisman", "Quagmire Druid", "Rakdos Carnarium", "Rakdos Guildgate", "Rakeclaw Gargantuan", "Rupture Spire", "Sakura-Tribe Elder", "Secluded Steppe", "Selesnya Guildgate", "Selesnya Sanctuary", "Selesnya Signet", "Simic Guildgate", "Simic Signet", "Slippery Karst", "Smoldering Crater", "Soul Manipulation", "Sprouting Vines", "Terramorphic Expanse", "Thornwind Faeries", "Tidehollow Strix", "Tranquil Thicket", "Transguild Promenade", "Valley Rannet", "Viscera Seer", "Vision Skeins", "Wayfarer's Bauble", "Winged Coatl");
		this.addCards(Rarity.UNCOMMON, "Acidic Slime", "Aerie Mystics", "Ajani's Pridemate", "Akoum Refuge", "Annihilate", "Arcane Sanctum", "Archangel", "Augur of Bolas", "Azorius Herald", "Azorius Keyrune", "Baleful Strix", "Baloth Woodcrasher", "Basalt Monolith", "Behemoth Sledge", "Blood Rites", "Boros Charm", "Borrowing 100,000 Arrows", "Brilliant Plan", "Carnage Altar", "Control Magic", "Crosis's Charm", "Crumbling Necropolis", "Curse of Chaos", "Curse of Inertia", "Curse of Predation", "Curse of Shallow Graves", "Curse of the Forsaken", "Darksteel Ingot", "Darksteel Mutation", "Deadwood Treefolk", "Deceiver Exarch", "Deepfire Elemental", "Disciple of Griselbrand", "Dismiss", "Diviner Spirit", "Dromar's Charm", "Drumhunter", "Faerie Conclave", "Famine", "Fecundity", "Fiend Hunter", "Fireball", "Fires of Yavimaya", "Flickerwisp", "Fog Bank", "Furnace Celebration", "Goblin Bombardment", "Golgari Guildmage", "Grixis Charm", "Guard Gomazoa", "Guttersnipe", "Hada Spy Patrol", "Harmonize", "Hooded Horror", "Infest", "Jade Mage", "Jund Charm", "Jungle Shrine", "Jwar Isle Refuge", "Kazandu Refuge", "Krosan Grip", "Krosan Warchief", "Leafdrake Roost", "Leonin Bladetrap", "Lim-Dûl's Vault", "Llanowar Reborn", "Marrow Bats", "Mistmeadow Witch", "Molten Slagheap", "Naya Charm", "New Benalia", "Nivix Guildmage", "One Dozen Eyes", "Opportunity", "Phthisis", "Phyrexian Gargantua", "Phyrexian Reclamation", "Propaganda", "Prosperity", "Rain of Thorns", "Raven Familiar", "Razor Hippogriff", "Reckless Spite", "Reincarnation", "Restore", "Rough // Tumble", "Saltcrusted Steppe", "Savage Lands", "Savage Twister", "Scarland Thrinax", "Seaside Citadel", "Sejiri Refuge", "Selesnya Charm", "Selesnya Guildmage", "Skyscribing", "Skyward Eye Prophets", "Slice and Dice", "Slice in Twain", "Sol Ring", "Spitebellows", "Spoils of Victory", "Sprouting Thrinax", "Stonecloaker", "Stormscape Battlemage", "Strategic Planning", "Street Spasm", "Sun Droplet", "Survival Cache", "Swiftfoot Boots", "Temple of the False God", "Terra Ravager", "Thopter Foundry", "Thunderstaff", "Tower Gargoyle", "Urza's Factory", "Vampire Nighthawk", "Vile Requiem", "Viseling", "Vitu-Ghazi, the City-Tree", "Vivid Crag", "Vivid Creek", "Vivid Grove", "Vivid Marsh", "Vizkopa Guildmage", "Walker of the Grove", "War Cadence", "Wash Out", "Wight of Precinct Six", "Wonder");
		this.addCards(Rarity.RARE, "AEthermage's Touch", "Act of Authority", "Angel of Finality", "Arcane Melee", "Augury Adept", "Azami, Lady of Scrolls", "Baleful Force", "Bane of Progress", "Blue Sun's Zenith", "Brooding Saurian", "Capricious Efreet", "Charmbreaker Devils", "Charnelhoard Wurm", "Conjurer's Closet", "Contested Cliffs", "Cradle of Vitality", "Crater Hellion", "Crawlspace", "Cruel Ultimatum", "Death Grasp", "Deathbringer Thoctar", "Decree of Pain", "Divinity of Pride", "Djinn of Infinite Deceits", "Druidic Satchel", "Dungeon Geists", "Echo Mage", "Endless Cockroaches", "Endrek Sahr, Master Breeder", "Eternal Dragon", "Eye of Doom", "Fell Shepherd", "Fiery Justice", "Filigree Angel", "Flickerform", "Foster", "From the Ashes", "Goblin Sharpshooter", "Greed", "Grim Backwoods", "Homeward Path", "Hua Tuo, Honored Physician", "Hunted Troll", "Illusionist's Gambit", "Incendiary Command", "Jace's Archivist", "Jar of Eyeballs", "Karmic Guide", "Kazandu Tuskcaller", "Kher Keep", "Kirtar's Wrath", "Kongming, \"Sleeping Dragon\"", "Lu Xun, Scholar General", "Magus of the Arena", "Mass Mutiny", "Mirari", "Mirror Entity", "Molten Disaster", "Mosswort Bridge", "Murkfiend Liege", "Myr Battlesphere", "Mystic Barrier", "Naya Soulbeast", "Nevinyrral's Disk", "Ophiomancer", "Order of Succession", "Phantom Nantuko", "Phyrexian Delver", "Plague Boiler", "Price of Knowledge", "Primal Vigor", "Ravenous Baloth", "Rubinia Soulsinger", "Sanguine Bond", "Seer's Sundial", "Sek'Kuar, Deathkeeper", "Serene Master", "Sharding Sphinx", "Silklash Spider", "Spawning Grounds", "Spellbreaker Behemoth", "Spinal Embrace", "Spine of Ish Sah", "Spiteful Visions", "Springjack Pasture", "Stalking Vengeance", "Starstorm", "Stronghold Assassin", "Sudden Demise", "Sudden Spoiling", "Surveyor's Scope", "Sword of the Paruns", "Temple Bell", "Tempt with Discovery", "Tempt with Glory", "Tempt with Immortality", "Tempt with Reflections", "Tempt with Vengeance", "Thousand-Year Elixir", "Tidal Force", "Tooth and Claw", "Tower of Fortunes", "Toxic Deluge", "True-Name Nemesis", "Unexpectedly Absent", "Uyo, Silent Prophet", "Wall of Reverence", "Warstorm Surge", "Well of Lost Dreams", "Where Ancients Tread", "Widespread Panic", "Wild Ricochet", "Witch Hunt", "Wrath of God");
		this.addCards(Rarity.MYTHIC, "Army of the Damned", "Avenger of Zendikar", "Derevi, Empyrial Tactician", "Gahiji, Honored One", "Inferno Titan", "Jeleva, Nephalia's Scourge", "Marath, Will of the Wild", "Mayael the Anima", "Nekusar, the Mindrazer", "Oloro, Ageless Ascetic", "Prossh, Skyraider of Kher", "Rampaging Baloths", "Roon of the Hidden Realm", "Serra Avatar", "Sharuum the Hegemon", "Shattergang Brothers", "Sphinx of the Steel Wind", "Sydri, Galvanic Genius", "Thraximundar");
	}
}
