package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Darksteel")
public final class Darksteel extends SimpleExpansion
{
	public Darksteel()
	{
		super();

		this.addCards(Rarity.COMMON, "Arcane Spyglass", "Arcbound Bruiser", "Arcbound Hybrid", "Arcbound Stinger", "Arcbound Worker", "Auriok Glaivemaster", "Barbed Lightning", "Burden of Greed", "Chittering Rats", "Crazed Goblin", "Darksteel Citadel", "Darksteel Ingot", "Darksteel Pendant", "Drill-Skimmer", "Drooling Ogre", "Dross Golem", "Echoing Calm", "Echoing Courage", "Echoing Decay", "Echoing Ruin", "Echoing Truth", "Essence Drain", "Grimclaw Bats", "Hallow", "Hunger of the Nim", "Inflame", "Krark-Clan Stoker", "Leonin Bola", "Loxodon Mystic", "Machinate", "Magnetic Flux", "Metal Fatigue", "Myr Landshaper", "Myr Moonvessel", "Neurok Prodigy", "Nourish", "Oxidda Golem", "Pteron Ghost", "Quicksilver Behemoth", "Razor Golem", "Reap and Sow", "Ritual of Restoration", "Scavenging Scarab", "Spire Golem", "Tangle Golem", "Tangle Spider", "Tel-Jilad Outrider", "Tel-Jilad Wolf", "Unforge", "Ur-Golem's Eye", "Vedalken Engineer", "Vex", "Viridian Acolyte", "Vulshok Morningstar", "Whispersilk Cloak");
		this.addCards(Rarity.UNCOMMON, "AEther Vial", "Angel's Feather", "Arcbound Crusher", "Arcbound Fiend", "Arcbound Lancer", "Arcbound Slith", "Auriok Siege Sled", "Carry Away", "Chimeric Egg", "Coretapper", "Darksteel Brute", "Darksteel Gargoyle", "Death-Mask Duplicant", "Demon's Horn", "Dismantle", "Dragon's Claw", "Emissary of Despair", "Emissary of Hope", "Fireball", "Genesis Chamber", "Geth's Grimoire", "Goblin Archaeologist", "Hoverguard Observer", "Infested Roothold", "Juggernaut", "Karstoderm", "Kraken's Eye", "Leonin Battlemage", "Mirrodin's Core", "Murderous Spoils", "Nemesis Mask", "Neurok Transmuter", "Nim Abomination", "Oxidize", "Psychic Overload", "Purge", "Screams from Within", "Scrounge", "Second Sight", "Skullclamp", "Spawning Pit", "Specter's Shroud", "Spincrusher", "Stand Together", "Stir the Pride", "Surestrike Trident", "Talon of Pain", "Tanglewalker", "Tears of Rage", "Test of Faith", "Thunderstaff", "Voltaic Construct", "Vulshok War Boar", "Wirefly Hive", "Wurm's Tooth");
		this.addCards(Rarity.RARE, "AEther Snap", "Ageless Entity", "Arcbound Overseer", "Arcbound Ravager", "Arcbound Reclaimer", "Blinkmoth Nexus", "Chromescale Drake", "Darksteel Colossus", "Darksteel Forge", "Darksteel Reactor", "Death Cloud", "Eater of Days", "Fangren Firstborn", "Flamebreak", "Furnace Dragon", "Gemini Engine", "Greater Harvester", "Heartseeker", "Last Word", "Leonin Shikari", "Lich's Tomb", "Memnarch", "Mephitic Ooze", "Mycosynth Lattice", "Myr Matrix", "Panoptic Mirror", "Pristine Angel", "Pulse of the Dross", "Pulse of the Fields", "Pulse of the Forge", "Pulse of the Grid", "Pulse of the Tangle", "Rebuking Ceremony", "Reshape", "Retract", "Roaring Slagwurm", "Savage Beating", "Serum Powder", "Shield of Kaldra", "Shriveling Rot", "Shunt", "Slobad, Goblin Tinkerer", "Soulscour", "Spellbinder", "Steelshaper Apprentice", "Sundering Titan", "Sword of Fire and Ice", "Sword of Light and Shadow", "Synod Artificer", "Thought Dissector", "Trinisphere", "Turn the Tables", "Viridian Zealot", "Wand of the Elements", "Well of Lost Dreams");
	}
}
