package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Dark Ascension")
public final class DarkAscension extends SimpleExpansion
{
	public DarkAscension()
	{
		super();

		this.addCards(Rarity.COMMON, "Artful Dodge", "Bar the Door", "Black Cat", "Bone to Ash", "Break of Day", "Burden of Guilt", "Chant of the Skifsang", "Chosen of Markov", "Clinging Mists", "Crushing Vines", "Dawntreader Elk", "Death's Caress", "Divination", "Elgaud Inquisitor", "Erdwal Ripper", "Evolving Wilds", "Executioner's Hood", "Faithless Looting", "Falkenrath Torturer", "Favor of the Woods", "Fires of Undeath", "Fling", "Forge Devil", "Gather the Townsfolk", "Gravepurge", "Griptide", "Gruesome Discovery", "Haunted Fengraf", "Headless Skaab", "Heavy Mattock", "Highborn Ghoul", "Hinterland Hermit", "Hollowhenge Beast", "Hunger of the Howlpack", "Kessig Recluse", "Loyal Cathar", "Midnight Guard", "Nearheath Stalker", "Nephalia Seakite", "Niblis of the Mist", "Ray of Revelation", "Reap the Seagraf", "Russet Wolves", "Sanctuary Cat", "Saving Grasp", "Scorch the Fields", "Scorned Villager", "Screeching Skaab", "Shriekgeist", "Sightless Ghoul", "Silverclaw Griffin", "Skillful Lunge", "Somberwald Dryad", "Spiteful Shadows", "Stormbound Geist", "Talons of Falkenrath", "Thought Scour", "Torch Fiend", "Tragic Slip", "Ulvenwald Bear", "Undying Evil", "Wild Hunger", "Wrack with Madness", "Young Wolf");
		this.addCards(Rarity.UNCOMMON, "Afflicted Deserter", "Altar of the Lost", "Avacyn's Collar", "Blood Feud", "Briarpack Alpha", "Burning Oil", "Chalice of Life", "Chill of Foreboding", "Curse of Exhaustion", "Curse of Thirst", "Deadly Allure", "Diregraf Captain", "Drogskol Captain", "Faith's Shield", "Farbog Boneflinger", "Gavony Ironwright", "Gravetiller Wurm", "Grim Flowering", "Harrowing Journey", "Heckling Fiends", "Hollowhenge Spirit", "Immerwolf", "Lambholt Elder", "Lingering Souls", "Markov Warlord", "Mystic Retrieval", "Niblis of the Breath", "Niblis of the Urn", "Pyreheart Wolf", "Relentless Skaabs", "Secrets of the Dead", "Shattered Perception", "Skirsdag Flayer", "Soul Seizer", "Strangleroot Geist", "Stromkirk Captain", "Thraben Heretic", "Tower Geist", "Tracker's Instincts", "Vengeful Vampire", "Village Survivors", "Wakedancer", "Warden of the Wall", "Wolfhunter's Quiver");
		this.addCards(Rarity.RARE, "Alpha Brawl", "Call to the Kindred", "Counterlash", "Curse of Bloodletting", "Curse of Echoes", "Curse of Misfortunes", "Deranged Outcast", "Dungeon Geists", "Feed the Pack", "Fiend of the Shadows", "Flayer of the Hatebound", "Geralf's Messenger", "Geralf's Mindcrusher", "Ghoultree", "Grafdigger's Cage", "Gravecrawler", "Grim Backwoods", "Havengul Runebinder", "Hellrider", "Increasing Ambition", "Increasing Confusion", "Increasing Devotion", "Increasing Savagery", "Increasing Vengeance", "Jar of Eyeballs", "Lost in the Woods", "Markov Blademaster", "Mondronen Shaman", "Predator Ooze", "Ravenous Demon", "Requiem Angel", "Seance", "Sudden Disappearance", "Thalia, Guardian of Thraben", "Thraben Doomsayer", "Vault of the Archangel", "Wolfbitten Captive", "Zombie Apocalypse");
		this.addCards(Rarity.MYTHIC, "Archangel's Light", "Beguiler of Wills", "Drogskol Reaver", "Elbrus, the Binding Blade", "Falkenrath Aristocrat", "Havengul Lich", "Helvault", "Huntmaster of the Fells", "Mikaeus, the Unhallowed", "Moonveil Dragon", "Sorin, Lord of Innistrad", "Vorapede");
	}
}
