package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Dissension")
public final class Dissension extends SimpleExpansion
{
	public Dissension()
	{
		super();

		this.addCards(Rarity.COMMON, "Aquastrand Spider", "Assault Zeppelid", "Aurora Eidolon", "Azorius Chancery", "Azorius First-Wing", "Azorius Signet", "Beacon Hawk", "Cackling Flames", "Carom", "Coiling Oracle", "Cytospawn Shambler", "Delirium Skeins", "Demon's Jester", "Enemy of the Guildpact", "Enigma Eidolon", "Entropic Eidolon", "Freewind Equenaut", "Gobhobbler Rats", "Guardian of the Guildpact", "Haazda Exonerator", "Helium Squirter", "Kill-Suit Cultist", "Macabre Waltz", "Minister of Impediments", "Nettling Curse", "Ocular Halo", "Ogre Gatecrasher", "Overrule", "Plumes of Peace", "Psychotic Fury", "Rakdos Carnarium", "Rakdos Ickspitter", "Rakdos Signet", "Riot Spikes", "Sandstorm Eidolon", "Seal of Doom", "Seal of Fire", "Shielding Plax", "Silkwing Scout", "Simic Growth Chamber", "Simic Initiate", "Simic Ragworm", "Simic Signet", "Slaughterhouse Bouncer", "Soulsworn Jury", "Sporeback Troll", "Steeling Stance", "Street Savvy", "Taste for Mayhem", "Thrive", "Utopia Sprawl", "Utvara Scalper", "Valor Made Real", "Verdant Eidolon", "Vesper Ghoul", "Vigean Hydropon", "Vision Skeins", "Whiptail Moloch", "Wrecking Ball", "Writ of Passage");
		this.addCards(Rarity.UNCOMMON, "Azorius AEthermage", "Azorius Guildmage", "Azorius Herald", "Azorius Ploy", "Blessing of the Nephilim", "Bond of Agony", "Brace for Impact", "Brain Pry", "Condemn", "Court Hussar", "Crypt Champion", "Drekavac", "Fertile Imagination", "Flame-Kin War Scout", "Flaring Flame-Kin", "Flash Foliage", "Ghost Quarter", "Gnat Alley Creeper", "Hellhole Rats", "Hit // Run", "Ignorant Bliss", "Indrik Stomphowler", "Jagged Poppet", "Kindle the Carnage", "Leafdrake Roost", "Magewright's Stone", "Might of the Nephilim", "Mistral Charger", "Nightcreep", "Novijen, Heart of Progress", "Pain Magnification", "Paladin of Prahv", "Palliation Accord", "Patagia Viper", "Plaxcaster Frogling", "Plaxmanta", "Prahv, Spires of Order", "Pure // Simple", "Ragamuffyn", "Rakdos Guildmage", "Rise // Fall", "Rix Maadi, Dungeon Palace", "Simic Basilisk", "Simic Guildmage", "Skullmead Cauldron", "Sky Hussar", "Skyscribing", "Slithering Shade", "Spell Snare", "Squealing Devil", "Stoic Ephemera", "Stomp and Howl", "Supply // Demand", "Transguild Courier", "Trial // Error", "Trygon Predator", "Twinstrike", "Vigean Graftmage", "Vigean Intuition", "Weight of Spires");
		this.addCards(Rarity.RARE, "AEthermage's Touch", "Anthem of Rakdos", "Avatar of Discord", "Biomantic Mastery", "Blood Crypt", "Bound // Determined", "Breeding Pool", "Bronze Bombshell", "Celestial Ancient", "Crime // Punishment", "Cytoplast Manipulator", "Cytoplast Root-Kin", "Cytoshape", "Demonfire", "Dovescape", "Dread Slag", "Elemental Resonance", "Evolution Vat", "Experiment Kraj", "Govern the Guildless", "Grand Arbiter Augustin IV", "Haazda Shield Mate", "Hallowed Fountain", "Hide // Seek", "Infernal Tutor", "Isperia the Inscrutable", "Loaming Shaman", "Lyzolda, the Blood Witch", "Momir Vig, Simic Visionary", "Muse Vessel", "Nihilistic Glee", "Novijen Sages", "Odds // Ends", "Omnibian", "Pillar of the Paruns", "Pride of the Clouds", "Proclamation of Rebirth", "Proper Burial", "Protean Hulk", "Psychic Possession", "Rain of Gore", "Rakdos Augermage", "Rakdos Pit Dragon", "Rakdos Riteknife", "Rakdos the Defiler", "Ratcatcher", "Research // Development", "Simic Sky Swallower", "Sprouting Phytohydra", "Stalking Vengeance", "Stormscale Anarch", "Swift Silence", "Tidespout Tyrant", "Unliving Psychopath", "Voidslime", "Wakestone Gargoyle", "Walking Archive", "War's Toll", "Windreaver", "Wit's End");
	}
}
