package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Eighth Edition")
public final class EighthEdition extends SimpleExpansion
{
	public EighthEdition()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Anaba Shaman", "Angelic Page", "Aven Cloudchaser", "Aven Fisher", "Aven Flock", "Balduvian Barbarians", "Bog Imp", "Boomerang", "Canopy Spider", "Canyon Wildcat", "Catalog", "Cinder Wall", "Coastal Hornclaw", "Coercion", "Coral Eel", "Craw Wurm", "Crossbow Infantry", "Dark Banishing", "Deepwood Ghoul", "Dehydration", "Demystify", "Diving Griffin", "Drudge Skeletons", "Dusk Imp", "Eager Cadet", "Elvish Pioneer", "Fear", "Fertile Ground", "Flash Counter", "Flight", "Fugitive Wizard", "Giant Badger", "Giant Cockroach", "Giant Growth", "Giant Octopus", "Giant Spider", "Glory Seeker", "Goblin Chariot", "Goblin Raider", "Gravedigger", "Grizzly Bears", "Healing Salve", "Hill Giant", "Holy Day", "Holy Strength", "Honor Guard", "Horned Troll", "Horned Turtle", "Index", "Inspiration", "Lava Axe", "Lightning Elemental", "Lone Wolf", "Looming Shade", "Maggot Carrier", "Mana Leak", "Master Decoy", "Merchant of Secrets", "Mind Rot", "Monstrous Growth", "Moss Monster", "Nantuko Disciple", "Naturalize", "Nausea", "Norwood Ranger", "Orcish Spy", "Pacifism", "Panic Attack", "Plague Beetle", "Raging Goblin", "Raise Dead", "Rampant Growth", "Ravenous Rats", "Razorfoot Griffin", "Redeem", "Reflexes", "Regeneration", "Remove Soul", "Ridgeline Rager", "Rushwood Dryad", "Sabretooth Tiger", "Sacred Nectar", "Sage Owl", "Samite Healer", "Scathe Zombies", "Sea Eagle", "Sea Monster", "Serpent Warrior", "Severed Legion", "Shatter", "Shock", "Shock Troops", "Sizzle", "Sneaky Homunculus", "Solidarity", "Spined Wurm", "Spineless Thug", "Standing Troops", "Stone Rain", "Storm Crow", "Suntail Hawk", "Trained Armodon", "Tremor", "Tundra Wolves", "Twiddle", "Unholy Strength", "Unsummon", "Venerable Monk", "Vicious Hunger", "Vine Trellis", "Volcanic Hammer", "Wind Drake", "Wood Elves");
		this.addCards(Rarity.UNCOMMON, "Abyssal Specter", "Air Elemental", "Ambition's Cost", "Angel of Mercy", "Ardent Militia", "Blanchwood Armor", "Blaze", "Bog Wraith", "Boil", "Carrion Wall", "Chastise", "Choke", "Circle of Protection: Black", "Circle of Protection: Blue", "Circle of Protection: Green", "Circle of Protection: Red", "Circle of Protection: White", "Coastal Tower", "Concentrate", "Confiscate", "Creeping Mold", "Crystal Rod", "Curiosity", "Deathgazer", "Demolish", "Diabolic Tutor", "Dwarven Demolition Team", "Elfhame Palace", "Elite Javelineer", "Elvish Lyrist", "Elvish Scrapper", "Enormous Baloth", "Enrage", "Execute", "Fecundity", "Fighting Drake", "Flashfires", "Fodder Cannon", "Foratog", "Fyndhorn Elder", "Gluttonous Zombie", "Goblin Glider", "Guerrilla Tactics", "Hibernation", "Hulking Cyclops", "Hunted Wumpus", "Invisibility", "Iron Star", "Ivory Cup", "Karma", "Lesser Gargadon", "Lightning Blast", "Living Terrain", "Llanowar Behemoth", "Lure", "Megrim", "Merchant Scroll", "Mind Slash", "Mind Sludge", "Nekrataal", "Ogre Taskmaster", "Orcish Artillery", "Patagia Golem", "Peach Garden Oath", "Phantom Warrior", "Phyrexian Hulk", "Primeval Shambler", "Puppeteer", "Pyroclasm", "Pyrotechnics", "Rain of Blades", "Revive", "Rewind", "Rod of Ruin", "Salt Marsh", "Sanctimony", "Seasoned Marshal", "Sever Soul", "Shivan Oasis", "Silverback Ape", "Slay", "Soul Feast", "Spellbook", "Spiketail Hatchling", "Spirit Link", "Spitting Spider", "Spreading Algae", "Star Compass", "Staunch Defenders", "Steal Artifact", "Stream of Life", "Sudden Impact", "Swarm of Rats", "Sword Dancer", "Telepathy", "Thieving Magpie", "Throne of Bone", "Treasure Trove", "Urborg Volcano", "Urza's Mine", "Urza's Power Plant", "Urza's Tower", "Vengeance", "Viashino Sandstalker", "Wall of Air", "Wall of Spears", "Wall of Stone", "Wall of Swords", "Wing Snare", "Wooden Sphere", "Wrath of Marit Lage", "Yavimaya Enchantress", "Zombify");
		this.addCards(Rarity.RARE, "Aladdin's Ring", "Archivist", "Avatar of Hope", "Balance of Power", "Beast of Burden", "Birds of Paradise", "Blessed Reversal", "Blinding Angel", "Blood Moon", "Bloodshot Cyclops", "Brass Herald", "Bribery", "Call of the Wild", "City of Brass", "Coastal Piracy", "Coat of Arms", "Collective Unconscious", "Cowardice", "Daring Apprentice", "Death Pit Offering", "Death Pits of Rath", "Defense Grid", "Deflection", "Dingus Egg", "Disrupting Scepter", "Distorting Lens", "Eastern Paladin", "Elite Archers", "Elvish Champion", "Elvish Piper", "Emperor Crocodile", "Ensnaring Bridge", "Evacuation", "Fallen Angel", "Fleeting Image", "Flying Carpet", "Fungusaur", "Furnace of Rath", "Gaea's Herald", "Glorious Anthem", "Goblin King", "Grave Pact", "Hammer of Bogardan", "Howling Mine", "Inferno", "Intrepid Hero", "Intruder Alarm", "Ivory Mask", "Jayemdae Tome", "Larceny", "Lava Hounds", "Lhurgoyf", "Lord of the Undead", "Mahamoti Djinn", "Mana Clash", "Maro", "Master Healer", "Might of Oaks", "Millstone", "Mind Bend", "Mogg Sentry", "Murderous Betrayal", "Natural Affinity", "Nightmare", "Noble Purpose", "Obliterate", "Okk", "Oracle's Attendants", "Persecute", "Phyrexian Arena", "Phyrexian Colossus", "Phyrexian Plaguelord", "Plague Wind", "Planar Portal", "Plow Under", "Primeval Force", "Relentless Assault", "Rhox", "Rolling Stones", "Royal Assassin", "Rukh Egg", "Sacred Ground", "Sage of Lat-Nam", "Savannah Lions", "Searing Wind", "Seismic Assault", "Serra Angel", "Shifting Sky", "Shivan Dragon", "Skull of Orm", "Story Circle", "Sunweb", "Teferi's Puzzle Box", "Temporal Adept", "Thieves' Auction", "Thorn Elemental", "Tidal Kraken", "Trade Routes", "Two-Headed Dragon", "Underworld Dreams", "Urza's Armor", "Vampiric Spirit", "Verduran Enchantress", "Vernal Bloom", "Vexing Arcanix", "Vizzerdrix", "Warped Devotion", "Western Paladin", "Worship", "Wrath of God", "Zur's Weirding");
	}
}
