package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Eventide")
public final class Eventide extends SimpleExpansion
{
	public Eventide()
	{
		super();

		this.addCards(Rarity.COMMON, "Aerie Ouphes", "Antler Skulkin", "Ballynock Trapper", "Banishing Knack", "Battlegate Mimic", "Beckon Apparition", "Cenn's Enlistment", "Cinder Pyromancer", "Clout of the Dominus", "Desecrator Hag", "Double Cleave", "Drain the Well", "Dream Thief", "Duergar Assailant", "Edge of the Divinity", "Fang Skulkin", "Favor of the Overbeing", "Fire at Will", "Flame Jab", "Gift of the Deity", "Grazing Kelpie", "Harvest Gwyllion", "Heartlash Cinder", "Hobgoblin Dragoon", "Hoof Skulkin", "Hotheaded Giant", "Inside Out", "Jawbone Skulkin", "Kithkin Spellduster", "Kithkin Zealot", "Merrow Bonegnawer", "Merrow Levitator", "Monstrify", "Nettle Sentinel", "Nightsky Mimic", "Nip Gwyllion", "Noggle Bandit", "Noggle Bridgebreaker", "Odious Trow", "Oona's Grace", "Puncture Blast", "Raven's Crime", "Recumbent Bliss", "Rendclaw Trow", "Riverfall Mimic", "Scourge of the Nobilis", "Shell Skulkin", "Shorecrasher Mimic", "Slippery Bogle", "Smoldering Butcher", "Snakeform", "Soul Reap", "Stream Hopper", "Talara's Bane", "Tilling Treefolk", "Trapjaw Kelpie", "Unmake", "Wickerbough Elder", "Wilderness Hypnotist", "Woodlurker Mimic");
		this.addCards(Rarity.UNCOMMON, "Batwing Brume", "Belligerent Hatchling", "Bloodied Ghost", "Cache Raiders", "Canker Abomination", "Cankerous Thirst", "Cauldron Haze", "Chaotic Backlash", "Crag Puca", "Creakwood Ghoul", "Crumbling Ashes", "Dream Fracture", "Duergar Cave-Guard", "Duergar Hedge-Mage", "Duergar Mine-Captain", "Duskdale Wurm", "Endure", "Flickerwisp", "Gilder Bairn", "Groundling Pouncer", "Gwyllion Hedge-Mage", "Hag Hedge-Mage", "Hatchet Bully", "Hearthfire Hobgoblin", "Idle Thoughts", "Impelled Giant", "Indigo Faerie", "Invert the Skies", "Lingering Tormentor", "Loyal Gyrfalcon", "Marshdrinker Giant", "Moonhold", "Noggle Hedge-Mage", "Noggle Ransacker", "Noxious Hatchling", "Nucklavee", "Outrage Shaman", "Patrol Signaler", "Phosphorescent Feast", "Quillspike", "Razorfin Abolisher", "Restless Apparition", "Savage Conception", "Selkie Hedge-Mage", "Shrewd Hatchling", "Soot Imp", "Soul Snuffers", "Spitemare", "Springjack Shepherd", "Stalker Hag", "Sturdy Hatchling", "Suture Spirit", "Swirling Spriggan", "Syphon Life", "Talonrend", "Twinblade Slasher", "Unnerving Assault", "Unwilling Recruit", "Voracious Hatchling", "Wistful Selkie");
		this.addCards(Rarity.RARE, "Altar Golem", "Archon of Justice", "Ashling, the Extinguisher", "Balefire Liege", "Bloom Tender", "Call the Skybreaker", "Cascade Bluffs", "Cold-Eyed Selkie", "Crackleburr", "Creakwood Liege", "Deathbringer Liege", "Deity of Scars", "Divinity of Pride", "Dominus of Fealty", "Doomgape", "Endless Horizons", "Evershrike", "Fable of Wolf and Owl", "Fetid Heath", "Fiery Bombardment", "Figure of Destiny", "Flooded Grove", "Glamerdye", "Glen Elendra Archmage", "Hallowed Burial", "Hateflayer", "Helix Pinnacle", "Inundate", "Leering Emblem", "Light from Within", "Mindwrack Liege", "Mirror Sheen", "Murkfiend Liege", "Necroskitter", "Needle Specter", "Nightmare Incursion", "Nobilis of War", "Overbeing of Myth", "Primalcrux", "Pyrrhic Revival", "Regal Force", "Rekindled Flame", "Rise of the Hobgoblins", "Rugged Prairie", "Sanity Grinding", "Sapling of Colfenor", "Scarecrone", "Spirit of the Hearth", "Spitting Image", "Springjack Pasture", "Stigma Lasher", "Stillmoon Cavalier", "Talara's Battalion", "Thunderblust", "Twilight Mire", "Umbra Stalker", "Wake Thrasher", "Ward of Bones", "Waves of Aggression", "Worm Harvest");
	}
}
