package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Fallen Empires")
public final class FallenEmpires extends SimpleExpansion
{
	public FallenEmpires()
	{
		super();

		this.addCards(Rarity.COMMON, "Armor Thrull", "Armor Thrull", "Armor Thrull", "Armor Thrull", "Basal Thrull", "Basal Thrull", "Basal Thrull", "Basal Thrull", "Brassclaw Orcs", "Brassclaw Orcs", "Brassclaw Orcs", "Brassclaw Orcs", "Combat Medic", "Combat Medic", "Combat Medic", "Combat Medic", "Delif's Cone", "Dwarven Soldier", "Dwarven Soldier", "Dwarven Soldier", "Elven Fortress", "Elven Fortress", "Elven Fortress", "Elven Fortress", "Elvish Hunter", "Elvish Hunter", "Elvish Hunter", "Elvish Scout", "Elvish Scout", "Elvish Scout", "Farrel's Zealot", "Farrel's Zealot", "Farrel's Zealot", "Goblin Chirurgeon", "Goblin Chirurgeon", "Goblin Chirurgeon", "Goblin Grenade", "Goblin Grenade", "Goblin Grenade", "Goblin War Drums", "Goblin War Drums", "Goblin War Drums", "Goblin War Drums", "High Tide", "High Tide", "High Tide", "Homarid", "Homarid", "Homarid", "Homarid", "Homarid Warrior", "Homarid Warrior", "Homarid Warrior", "Hymn to Tourach", "Hymn to Tourach", "Hymn to Tourach", "Hymn to Tourach", "Icatian Infantry", "Icatian Infantry", "Icatian Infantry", "Icatian Infantry", "Icatian Javelineers", "Icatian Javelineers", "Icatian Javelineers", "Icatian Moneychanger", "Icatian Moneychanger", "Icatian Moneychanger", "Icatian Scout", "Icatian Scout", "Icatian Scout", "Icatian Scout", "Initiates of the Ebon Hand", "Initiates of the Ebon Hand", "Initiates of the Ebon Hand", "Merseine", "Merseine", "Merseine", "Merseine", "Mindstab Thrull", "Mindstab Thrull", "Mindstab Thrull", "Necrite", "Necrite", "Necrite", "Night Soil", "Night Soil", "Night Soil", "Orcish Spy", "Orcish Spy", "Orcish Spy", "Orcish Veteran", "Orcish Veteran", "Orcish Veteran", "Orcish Veteran", "Order of Leitbur", "Order of Leitbur", "Order of Leitbur", "Order of the Ebon Hand", "Order of the Ebon Hand", "Order of the Ebon Hand", "Spore Cloud", "Spore Cloud", "Spore Cloud", "Thallid", "Thallid", "Thallid", "Thallid", "Thorn Thallid", "Thorn Thallid", "Thorn Thallid", "Thorn Thallid", "Tidal Flats", "Tidal Flats", "Tidal Flats", "Vodalian Mage", "Vodalian Mage", "Vodalian Mage", "Vodalian Soldiers", "Vodalian Soldiers", "Vodalian Soldiers", "Vodalian Soldiers");
		this.addCards(Rarity.UNCOMMON, "Breeding Pit", "Deep Spawn", "Dwarven Catapult", "Dwarven Lieutenant", "Dwarven Ruins", "Ebon Stronghold", "Farrel's Mantle", "Farrelite Priest", "Feral Thallid", "Goblin Kites", "Havenwood Battleground", "Heroism", "Homarid Spawning Bed", "Icatian Phalanx", "Icatian Priest", "Orcish Captain", "Raiding Party", "Ruins of Trokair", "Seasinger", "Soul Exchange", "Spore Flower", "Svyelunite Priest", "Svyelunite Temple", "Thallid Devourer", "Thelon's Chant", "Thelonite Druid", "Thrull Retainer", "Thrull Wizard", "Tidal Influence", "Tourach's Chant");
		this.addCards(Rarity.RARE, "Aeolipile", "Balm of Restoration", "Bottomless Vault", "Conch Horn", "Delif's Cube", "Derelor", "Draconian Cylix", "Dwarven Armorer", "Dwarven Hold", "Ebon Praetor", "Elven Lyre", "Elvish Farmer", "Fungal Bloom", "Goblin Flotilla", "Goblin Warrens", "Hand of Justice", "Hollow Trees", "Homarid Shaman", "Icatian Lieutenant", "Icatian Skirmishers", "Icatian Store", "Icatian Town", "Implements of Sacrifice", "Orgg", "Rainbow Vale", "Ring of Renewal", "River Merfolk", "Sand Silos", "Spirit Shield", "Thelon's Curse", "Thelonite Monk", "Thrull Champion", "Tourach's Gate", "Vodalian Knights", "Vodalian War Machine", "Zelyon Sword");
	}
}
