package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Fifth Edition")
public final class FifthEdition extends SimpleExpansion
{
	public FifthEdition()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "Alabaster Potion", "Ambush Party", "Amulet of Kroog", "Armor of Faith", "Ashnod's Transmogrant", "Aurochs", "Aysen Bureaucrats", "Barbed Sextant", "Battering Ram", "Benalish Hero", "Bird Maiden", "Blessed Wine", "Blood Lust", "Bog Imp", "Bog Rats", "Boomerang", "Brainstorm", "Brainwash", "Brassclaw Orcs", "Brothers of Fire", "Carapace", "Cat Warriors", "Chub Toad", "Circle of Protection: Black", "Circle of Protection: Blue", "Circle of Protection: Green", "Circle of Protection: Red", "Circle of Protection: White", "Clay Statue", "Cloak of Confusion", "Counterspell", "Craw Wurm", "D'Avenant Archer", "Dandân", "Dark Maze", "Dark Ritual", "Death Speakers", "Death Ward", "Disenchant", "Disintegrate", "Divine Offering", "Drain Life", "Drudge Skeletons", "Durkwood Boars", "Dwarven Soldier", "Dwarven Warriors", "Enervate", "Erg Raiders", "Errantry", "Eternal Warrior", "Fear", "Fireball", "Firebreathing", "Flare", "Flight", "Flood", "Fog", "Force Spike", "Foxfire", "Frozen Shade", "Funeral March", "Gaseous Form", "Ghazbán Ogre", "Giant Growth", "Giant Spider", "Giant Strength", "Goblin Digging Team", "Goblin Hero", "Goblin War Drums", "Grapeshot Catapult", "Grizzly Bears", "Heal", "Healing Salve", "Hill Giant", "Hipparion", "Holy Strength", "Homarid Warrior", "Howl from Beyond", "Hungry Mist", "Hurloon Minotaur", "Icatian Scout", "Imposing Visage", "Incinerate", "Initiates of the Ebon Hand", "Ironclaw Orcs", "Ironroot Treefolk", "Kjeldoran Dead", "Krovikan Fetish", "Krovikan Sorcerer", "Labyrinth Minotaur", "Ley Druid", "Llanowar Elves", "Lost Soul", "Marsh Viper", "Memory Lapse", "Merfolk of the Pearl Trident", "Mesa Falcon", "Mesa Pegasus", "Mind Ravel", "Mindstab Thrull", "Mons's Goblin Raiders", "Mountain Goat", "Murk Dwellers", "Nature's Lore", "Necrite", "Orcish Conscripts", "Orcish Farmer", "Panic", "Paralyze", "Pearled Unicorn", "Pestilence", "Phantasmal Terrain", "Pikemen", "Pit Scorpion", "Plague Rats", "Portent", "Pradesh Gypsies", "Prismatic Ward", "Prodigal Sorcerer", "Psychic Venom", "Raise Dead", "Ray of Command", "Reef Pirates", "Regeneration", "Remove Soul", "Repentant Blacksmith", "Sabretooth Tiger", "Samite Healer", "Scaled Wurm", "Scathe Zombies", "Scavenger Folk", "Scryb Sprites", "Sea Serpent", "Shanodin Dryads", "Shatter", "Shield Bearer", "Shield Wall", "Shrink", "Soul Barrier", "Spell Blast", "Stone Rain", "Stream of Life", "Tarpan", "Terror", "The Brute", "Torture", "Touch of Death", "Tranquility", "Tundra Wolves", "Twiddle", "Unholy Strength", "Unstable Mutation", "Unsummon", "Updraft", "Urza's Mine", "Urza's Power Plant", "Urza's Tower", "Vampire Bats", "Venom", "Vodalian Soldiers", "Wall of Spears", "War Mammoth", "Weakness", "Wild Growth", "Zephyr Falcon");
		this.addCards(Rarity.UNCOMMON, "AEther Storm", "Abbey Gargoyles", "Abyssal Specter", "Air Elemental", "Angry Mob", "Animate Dead", "Anti-Magic Aura", "Arenson's Aura", "Ashes to Ashes", "Ashnod's Altar", "Atog", "Azure Drake", "Binding Grasp", "Black Knight", "Blight", "Bog Wraith", "Breeding Pit", "Carrion Ants", "Castle", "Cave People", "Circle of Protection: Artifacts", "Clockwork Steed", "Conquer", "Craw Giant", "Crumble", "Crystal Rod", "Cursed Land", "Deathgrip", "Desert Twister", "Detonate", "Diabolic Machine", "Divine Transformation", "Dust to Dust", "Dwarven Catapult", "Dwarven Ruins", "Ebon Stronghold", "Elven Riders", "Energy Flux", "Evil Eye of Orms-by-Gore", "Evil Presence", "Fallen Angel", "Feedback", "Feldon's Cane", "Fellwar Stone", "Fire Drake", "Flame Spirit", "Flashfires", "Fountain of Youth", "Fyndhorn Elder", "Glacial Wall", "Glasses of Urza", "Gloom", "Greater Realm of Preservation", "Greater Werewolf", "Havenwood Battleground", "Hurricane", "Hydroblast", "Icatian Phalanx", "Ice Floe", "Instill Energy", "Iron Star", "Ivory Cup", "Ivory Guardians", "Johtull Wurm", "Joven's Tools", "Justice", "Karma", "Keldon Warlord", "Killer Bees", "Kismet", "Kjeldoran Skycaptain", "Knight of Stromgald", "Leshrac's Rite", "Library of Leng", "Lifeforce", "Lifetap", "Lure", "Mind Bomb", "Mind Warp", "Mole Worms", "Orcish Artillery", "Orcish Captain", "Orcish Oriflamme", "Order of the White Shield", "Ornithopter", "Phantasmal Forces", "Phantom Monster", "Power Sink", "Primordial Ooze", "Pyroblast", "Pyrotechnics", "Rabid Wombat", "Radjan Spirit", "Rod of Ruin", "Ruins of Trokair", "Sacred Boon", "Sea Spirit", "Sea Sprite", "Seasinger", "Segovian Leviathan", "Serra Bestiary", "Serra Paladin", "Shapeshifter", "Shatterstorm", "Skull Catapult", "Soul Net", "Spirit Link", "Steal Artifact", "Stone Giant", "Stone Spirit", "Svyelunite Temple", "Tawnos's Weaponry", "Thicket Basilisk", "Throne of Bone", "Thrull Retainer", "Tsunami", "Untamed Wilds", "Urza's Bauble", "Wall of Air", "Wall of Bone", "Wall of Brambles", "Wall of Fire", "Wall of Stone", "Wall of Swords", "Wanderlust", "Whirling Dervish", "White Knight", "Wind Spirit", "Winter Blast", "Wolverine Pack", "Wooden Sphere", "Word of Blasting");
		this.addCards(Rarity.RARE, "Adarkar Wastes", "Akron Legionnaire", "Aladdin's Ring", "An-Havva Constable", "Animate Wall", "Ankh of Mishra", "Armageddon", "Aspect of Wolf", "Bad Moon", "Ball Lightning", "Barl's Cage", "Birds of Paradise", "Blinking Spirit", "Bottle of Suleiman", "Bottomless Vault", "Broken Visage", "Brushland", "Caribou Range", "City of Brass", "Clockwork Beast", "Cockatrice", "Colossus of Sardia", "Coral Helm", "Crimson Manticore", "Crown of the Ages", "Crusade", "Dance of Many", "Dancing Scimitar", "Deflection", "Derelor", "Dingus Egg", "Disrupting Scepter", "Dragon Engine", "Drain Power", "Dwarven Hold", "Earthquake", "Elder Druid", "Elkin Bottle", "Elvish Archers", "Eye for an Eye", "Feroz's Ban", "Flying Carpet", "Force of Nature", "Forget", "Fungusaur", "Game of Chaos", "Gauntlets of Chaos", "Goblin King", "Goblin Warrens", "Hecatomb", "Helm of Chatzuk", "Hollow Trees", "Howling Mine", "Hurkyl's Recall", "Icatian Store", "Icatian Town", "Inferno", "Infinite Hourglass", "Ironclaw Curse", "Island Sanctuary", "Jade Monolith", "Jalum Tome", "Jandor's Saddlebags", "Jayemdae Tome", "Jester's Cap", "Jokulhaups", "Juxtapose", "Karplusan Forest", "Kjeldoran Royal Guard", "Leviathan", "Lhurgoyf", "Living Artifact", "Living Lands", "Lord of Atlantis", "Lord of the Pit", "Magical Hack", "Magus of the Unseen", "Mana Clash", "Mana Flare", "Mana Vault", "Manabarbs", "Meekstone", "Millstone", "Necropotence", "Nether Shadow", "Nevinyrral's Disk", "Nightmare", "Obelisk of Undoing", "Orcish Squatters", "Order of the Sacred Torch", "Orgg", "Pentagram of the Ages", "Personal Incarnation", "Pirate Ship", "Pox", "Primal Clay", "Primal Order", "Rag Man", "Recall", "Reverse Damage", "Righteousness", "Sand Silos", "Sengir Autocrat", "Seraph", "Serpent Generator", "Shivan Dragon", "Sibilant Spirit", "Sleight of Mind", "Smoke", "Sorceress Queen", "Stampede", "Stasis", "Stromgald Cabal", "Sulfurous Springs", "Sylvan Library", "The Hive", "The Wretched", "Time Bomb", "Time Elemental", "Titania's Song", "Truce", "Underground River", "Urza's Avenger", "Verduran Enchantress", "Warp Artifact", "Winds of Change", "Winter Orb", "Wrath of God", "Wyluli Wolf", "Xenic Poltergeist", "Zombie Master", "Zur's Weirding");
	}
}
