package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Fifth Dawn")
public final class FifthDawn extends SimpleExpansion
{
	public FifthDawn()
	{
		super();

		this.addCards(Rarity.COMMON, "Abuna's Chant", "Advanced Hoverguard", "Anodet Lurker", "Armed Response", "Baton of Courage", "Battered Golem", "Blind Creeper", "Cackling Imp", "Condescend", "Conjurer's Bauble", "Cranial Plating", "Dawn's Reflection", "Dross Crocodile", "Early Frost", "Ferocious Charge", "Fill with Fright", "Fleshgrafter", "Goblin Brawler", "Healer's Headdress", "Heliophial", "Horned Helm", "Into Thin Air", "Krark-Clan Ogre", "Leonin Squire", "Lose Hope", "Loxodon Anchorite", "Mana Geyser", "Myr Quadropod", "Myr Servitor", "Neurok Stealthsuit", "Opaline Bracers", "Pentad Prism", "Rain of Rust", "Razorgrass Screen", "Sawtooth Thresher", "Screaming Fury", "Serum Visions", "Skyhunter Prowler", "Skyreach Manta", "Spark Elemental", "Sparring Collar", "Stand Firm", "Stasis Cocoon", "Suntouched Myr", "Sylvok Explorer", "Tangle Asp", "Tel-Jilad Lifebreather", "Thermal Navigator", "Thought Courier", "Trinket Mage", "Tyrranax", "Vicious Betrayal", "Viridian Scout", "Vulshok Sorcerer", "Wayfarer's Bauble");
		this.addCards(Rarity.UNCOMMON, "Arachnoid", "Arcbound Wanderer", "Auriok Salvagers", "Avarice Totem", "Blasting Station", "Channel the Suns", "Chimeric Coils", "Circle of Protection: Artifacts", "Clock of Omens", "Composite Golem", "Devour in Shadow", "Disruption Aura", "Ebon Drake", "Energy Chamber", "Ensouled Scimitar", "Etched Oracle", "Eternal Witness", "Eyes of the Watcher", "Fangren Pathcutter", "Feedback Bolt", "Ferropede", "Fold into AEther", "Furnace Whelp", "Gemstone Array", "Goblin Cannon", "Grafted Wargear", "Grinding Station", "Guardian Idol", "Infused Arrows", "Iron-Barb Hellion", "Krark-Clan Engineers", "Krark-Clan Ironworks", "Lantern of Insight", "Loxodon Stalwart", "Lunar Avenger", "Magma Jet", "Magnetic Theft", "Night's Whisper", "Nim Grotesque", "Ouphe Vandals", "Paradise Mantle", "Plasma Elemental", "Qumulox", "Relentless Rats", "Relic Barrier", "Shattered Dreams", "Skullcage", "Skyhunter Skirmisher", "Spinal Parasite", "Steelshaper's Gift", "Synod Centurion", "Tel-Jilad Justice", "Vanquish", "Vedalken Mastermind", "Viridian Lorebearers");
		this.addCards(Rarity.RARE, "Acquire", "All Suns' Dawn", "Artificer's Intuition", "Auriok Champion", "Auriok Windwalker", "Beacon of Creation", "Beacon of Destruction", "Beacon of Immortality", "Beacon of Tomorrows", "Beacon of Unrest", "Blinkmoth Infusion", "Bringer of the Black Dawn", "Bringer of the Blue Dawn", "Bringer of the Green Dawn", "Bringer of the Red Dawn", "Bringer of the White Dawn", "Clearwater Goblet", "Cosmic Larva", "Crucible of Worlds", "Desecration Elemental", "Door to Nothingness", "Doubling Cube", "Endless Whispers", "Engineered Explosives", "Eon Hub", "Fist of Suns", "Granulate", "Helm of Kaldra", "Hoverguard Sweepers", "Ion Storm", "Joiner Adept", "Magma Giant", "Mephidross Vampire", "Moriok Rigger", "Mycosynth Golem", "Plunge into Darkness", "Possessed Portal", "Raksha Golden Cub", "Razormane Masticore", "Retaliate", "Reversal of Fortune", "Rite of Passage", "Roar of Reclamation", "Rude Awakening", "Salvaging Station", "Silent Arbiter", "Solarion", "Spectral Shift", "Staff of Domination", "Summoner's Egg", "Summoning Station", "Suncrusher", "Tornado Elemental", "Vedalken Orrery", "Vedalken Shackles");
	}
}
