package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Fourth Edition")
public final class FourthEdition extends SimpleExpansion
{
	public FourthEdition()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "Alabaster Potion", "Amrou Kithkin", "Amulet of Kroog", "Apprentice Wizard", "Battering Ram", "Benalish Hero", "Bird Maiden", "Blood Lust", "Blue Elemental Blast", "Bog Imp", "Brainwash", "Brothers of Fire", "Carnivorous Plant", "Circle of Protection: Black", "Circle of Protection: Blue", "Circle of Protection: Green", "Circle of Protection: Red", "Circle of Protection: White", "Clay Statue", "Craw Wurm", "Creature Bond", "Cyclopean Mummy", "Dark Ritual", "Death Ward", "Disenchant", "Disintegrate", "Drain Life", "Drudge Skeletons", "Durkwood Boars", "Dwarven Warriors", "Energy Tap", "Erg Raiders", "Erosion", "Eternal Warrior", "Fear", "Fireball", "Firebreathing", "Fissure", "Flight", "Flood", "Fog", "Fortified Area", "Frozen Shade", "Gaseous Form", "Giant Growth", "Giant Spider", "Giant Strength", "Giant Tortoise", "Goblin Rock Sled", "Grapeshot Catapult", "Gray Ogre", "Grizzly Bears", "Healing Salve", "Hill Giant", "Holy Armor", "Holy Strength", "Howl from Beyond", "Hurloon Minotaur", "Immolation", "Ironclaw Orcs", "Ironroot Treefolk", "Jump", "Land Leeches", "Lightning Bolt", "Llanowar Elves", "Lost Soul", "Marsh Gas", "Marsh Viper", "Merfolk of the Pearl Trident", "Mesa Pegasus", "Mons's Goblin Raiders", "Morale", "Murk Dwellers", "Nafs Asp", "Paralyze", "Pearled Unicorn", "Pestilence", "Phantasmal Terrain", "Piety", "Pikemen", "Pit Scorpion", "Plague Rats", "Power Leak", "Power Sink", "Pradesh Gypsies", "Prodigal Sorcerer", "Psychic Venom", "Raise Dead", "Red Elemental Blast", "Regeneration", "Samite Healer", "Sandstorm", "Scathe Zombies", "Scryb Sprites", "Sea Serpent", "Seeker", "Shanodin Dryads", "Shatter", "Sisters of the Flame", "Spell Blast", "Stone Rain", "Stream of Life", "Sunken City", "Terror", "The Brute", "Tranquility", "Tundra Wolves", "Twiddle", "Unholy Strength", "Unstable Mutation", "Unsummon", "Vampire Bats", "Venom", "Wall of Spears", "Wall of Wood", "War Mammoth", "Weakness", "Wild Growth", "Word of Binding", "Yotian Soldier", "Zephyr Falcon");
		this.addCards(Rarity.UNCOMMON, "Abomination", "Air Elemental", "Ali Baba", "Angry Mob", "Animate Artifact", "Animate Dead", "Ashes to Ashes", "Ashnod's Battle Gear", "Backfire", "Black Knight", "Black Vise", "Black Ward", "Blight", "Blue Ward", "Bog Wraith", "Brass Man", "Burrowing", "Carrion Ants", "Castle", "Cave People", "Celestial Prism", "Channel", "Circle of Protection: Artifacts", "Conservator", "Control Magic", "Conversion", "Counterspell", "Crumble", "Crystal Rod", "Cursed Land", "Cursed Rack", "Deathgrip", "Desert Twister", "Detonate", "Diabolic Machine", "Divine Transformation", "Dragon Whelp", "Earth Elemental", "Elven Riders", "Energy Flux", "Evil Presence", "Feedback", "Fellwar Stone", "Fire Elemental", "Flashfires", "Ghost Ship", "Glasses of Urza", "Gloom", "Goblin Balloon Brigade", "Green Ward", "Hurricane", "Hypnotic Specter", "Instill Energy", "Iron Star", "Ivory Cup", "Junún Efreet", "Karma", "Keldon Warlord", "Killer Bees", "Kismet", "Ley Druid", "Library of Leng", "Lifeforce", "Lifetap", "Lure", "Mind Bomb", "Mishra's Factory", "Oasis", "Obsianus Golem", "Orcish Artillery", "Orcish Oriflamme", "Ornithopter", "Osai Vultures", "Phantasmal Forces", "Phantom Monster", "Pyrotechnics", "Radjan Spirit", "Red Ward", "Rod of Ruin", "Scavenging Ghoul", "Segovian Leviathan", "Sengir Vampire", "Serra Angel", "Shapeshifter", "Simulacrum", "Sindbad", "Siren's Call", "Soul Net", "Spirit Link", "Spirit Shackle", "Steal Artifact", "Stone Giant", "Strip Mine", "Swords to Plowshares", "Tawnos's Wand", "Tawnos's Weaponry", "The Rack", "Thicket Basilisk", "Throne of Bone", "Tsunami", "Tunnel", "Uncle Istvan", "Untamed Wilds", "Uthden Troll", "Visions", "Wall of Air", "Wall of Bone", "Wall of Brambles", "Wall of Dust", "Wall of Fire", "Wall of Ice", "Wall of Stone", "Wall of Swords", "Wall of Water", "Wanderlust", "Water Elemental", "Whirling Dervish", "White Knight", "White Ward", "Winter Blast", "Wooden Sphere");
		this.addCards(Rarity.RARE, "Aladdin's Lamp", "Aladdin's Ring", "Animate Wall", "Ankh of Mishra", "Armageddon", "Armageddon Clock", "Aspect of Wolf", "Bad Moon", "Balance", "Ball Lightning", "Birds of Paradise", "Black Mana Battery", "Blessing", "Blue Mana Battery", "Bottle of Suleiman", "Bronze Tablet", "Chaoslace", "Clockwork Avian", "Clockwork Beast", "Cockatrice", "Colossus of Sardia", "Coral Helm", "Cosmic Horror", "Crimson Manticore", "Crusade", "Dancing Scimitar", "Deathlace", "Dingus Egg", "Disrupting Scepter", "Dragon Engine", "Drain Power", "Earthquake", "Ebony Horse", "El-Hajjâj", "Elder Land Wurm", "Elvish Archers", "Eye for an Eye", "Flying Carpet", "Force of Nature", "Fungusaur", "Gaea's Liege", "Goblin King", "Greed", "Green Mana Battery", "Helm of Chatzuk", "Howling Mine", "Hurkyl's Recall", "Hurr Jackal", "Inferno", "Island Fish Jasconius", "Island Sanctuary", "Ivory Tower", "Jade Monolith", "Jandor's Saddlebags", "Jayemdae Tome", "Kormus Bell", "Land Tax", "Leviathan", "Lifelace", "Living Artifact", "Living Lands", "Lord of Atlantis", "Lord of the Pit", "Magical Hack", "Magnetic Mountain", "Mahamoti Djinn", "Mana Clash", "Mana Flare", "Mana Short", "Mana Vault", "Manabarbs", "Meekstone", "Millstone", "Mind Twist", "Mishra's War Machine", "Nether Shadow", "Nevinyrral's Disk", "Nightmare", "Northern Paladin", "Onulet", "Personal Incarnation", "Pirate Ship", "Power Surge", "Primal Clay", "Psionic Entity", "Purelace", "Rag Man", "Rebirth", "Red Mana Battery", "Relic Bind", "Reverse Damage", "Righteousness", "Royal Assassin", "Savannah Lions", "Shivan Dragon", "Sleight of Mind", "Smoke", "Sorceress Queen", "Stasis", "Sunglasses of Urza", "Sylvan Library", "Tempest Efreet", "Tetravus", "The Hive", "Thoughtlace", "Timber Wolves", "Time Elemental", "Titania's Song", "Triskelion", "Urza's Avenger", "Verduran Enchantress", "Volcanic Eruption", "Warp Artifact", "Web", "White Mana Battery", "Will-o'-the-Wisp", "Winds of Change", "Winter Orb", "Wrath of God", "Xenic Poltergeist", "Zombie Master");
	}
}
