package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Future Sight")
public final class FutureSight extends SimpleExpansion
{
	public FutureSight()
	{
		super();

		this.addCards(Rarity.COMMON, "Augur il-Vec", "Augur of Skulls", "Aven Augur", "Blade of the Sixth Pride", "Blind Phantasm", "Bogardan Lancer", "Cutthroat il-Dal", "Death Rattle", "Deepcavern Imp", "Edge of Autumn", "Emberwilde Augur", "Fatal Attraction", "Flowstone Embrace", "Fomori Nomad", "Foresee", "Frenzy Sliver", "Gathan Raiders", "Ghostfire", "Gift of Granite", "Grave Peril", "Grave Scrabbler", "Grinning Ignus", "Henchfiend of Ukor", "Homing Sliver", "Ichor Slick", "Infiltrator il-Kor", "Judge Unworthy", "Kavu Primarch", "Knight of Sursi", "Leaden Fists", "Llanowar Augur", "Llanowar Empath", "Logic Knot", "Lost Hours", "Lucent Liminid", "Lumithread Field", "Lymph Sliver", "Marshaling Cry", "Mass of Ghouls", "Mesmeric Sliver", "Nessian Courser", "Oblivion Crown", "Patrician's Scorn", "Petrified Plating", "Putrid Cyclops", "Quiet Disrepair", "Riddle of Lightning", "Rift Elemental", "Saltskitter", "Samite Censer-Bearer", "Sarcomite Myr", "Sporoloth Ancient", "Sprout Swarm", "Thornweald Archer", "Unblinking Bleb", "Vedalken AEthermage", "Venser's Diffusion", "Virulent Sliver", "Whip-Spine Drake", "Wrap in Vigor");
		this.addCards(Rarity.UNCOMMON, "Arc Blade", "Arcanum Wings", "Aven Mindcensor", "Bloodshot Trainee", "Boldwyr Intimidator", "Bonded Fetch", "Bound in Silence", "Centaur Omenreader", "Char-Rumbler", "Chronomantic Escape", "Cloudseeder", "Cryptic Annelid", "Cyclical Evolution", "Dakmor Salvage", "Delay", "Dryad Arbor", "Dust of Moments", "Emblem of the Warmind", "Even the Odds", "Festering March", "Fleshwrither", "Goldmeadow Lookout", "Haze of Rage", "Imperiosaur", "Keldon Megaliths", "Llanowar Mentor", "Llanowar Reborn", "Lost Auramancers", "Minions' Murmurs", "Mistmeadow Skulk", "Mystic Speculation", "Nacatl War-Pride", "Narcomoeba", "New Benalia", "Phosphorescent Feast", "Pooling Venom", "Ramosian Revivalist", "Ravaging Riftwurm", "Reality Strobe", "Riftsweeper", "Second Wind", "Shivan Sand-Mage", "Skirk Ridge Exhumer", "Skizzik Surger", "Sliversmith", "Snake Cult Initiation", "Soultether Golem", "Sparkspitter", "Spellwild Ouphe", "Spin into Myth", "Spirit en-Dal", "Storm Entity", "Street Wraith", "Stronghold Rats", "Sword of the Meek", "Tolaria West", "Utopia Mycon", "Witch's Mist", "Yixlid Jailer", "Zoetic Cavern");
		this.addCards(Rarity.RARE, "Akroma's Memorial", "Angel of Salvation", "Barren Glory", "Baru, Fist of Krosa", "Bitter Ordeal", "Bridge from Below", "Cloud Key", "Coalition Relic", "Darksteel Garrison", "Daybreak Coronet", "Epochrasite", "Force of Savagery", "Gibbering Descent", "Glittering Wish", "Graven Cairns", "Grove of the Burnwillows", "Heartwood Storyteller", "Horizon Canopy", "Imperial Mask", "Intervention Pact", "Jhoira of the Ghitu", "Korlash, Heir to Blackblade", "Linessa, Zephyr Mage", "Maelstrom Djinn", "Magus of the Abyss", "Magus of the Future", "Magus of the Moat", "Magus of the Moon", "Magus of the Vineyard", "Molten Disaster", "Muraganda Petroglyphs", "Nihilith", "Nimbus Maze", "Nix", "Oriss, Samite Guardian", "Pact of Negation", "Pact of the Titan", "Pyromancer's Swath", "Quagnoth", "Rites of Flourishing", "River of Tears", "Scourge of Kher Ridges", "Scout's Warning", "Seht's Tiger", "Shah of Naar Isle", "Shapeshifter's Marrow", "Shimian Specter", "Slaughter Pact", "Sliver Legion", "Spellweaver Volute", "Steamflogger Boss", "Summoner's Pact", "Take Possession", "Tarmogoyf", "Tarox Bladewing", "Thunderblade Charge", "Tombstalker", "Veilstone Amulet", "Venser, Shaper Savant", "Whetwheel");
	}
}
