package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Gatecrash")
public final class Gatecrash extends SimpleExpansion
{
	public Gatecrash()
	{
		super();

		this.addCards(Rarity.COMMON, "Act of Treason", "Adaptive Snapjaw", "Aerial Maneuver", "Angelic Edict", "Armored Transport", "Assault Griffin", "Balustrade Spy", "Basilica Guards", "Basilica Screecher", "Beckon Apparition", "Bioshift", "Bomber Corps", "Boros Guildgate", "Burst of Strength", "Clinging Anemones", "Cloudfin Raptor", "Contaminated Ground", "Corpse Blockade", "Court Street Denizen", "Crocanura", "Daring Skyjek", "Death's Approach", "Deathcult Rogue", "Devour Flesh", "Dimir Guildgate", "Disciple of the Old Ways", "Drakewing Krasis", "Dutiful Thrull", "Ember Beast", "Executioner's Swing", "Forced Adaptation", "Foundry Street Denizen", "Frilled Oculus", "Furious Resistance", "Greenside Watcher", "Grisly Spectacle", "Gruul Guildgate", "Guildscorn Ward", "Gutter Skulk", "Hands of Binding", "Horror of the Dim", "Hydroform", "Ivy Lane Denizen", "Keymaster Rogue", "Kingpin's Pet", "Knight Watch", "Last Thoughts", "Leyline Phantom", "Madcap Skills", "Martial Glory", "Massive Raid", "Metropolis Sprite", "Midnight Recovery", "Millennial Gargoyle", "Mortus Strider", "Mugging", "Naturalize", "Nav Squad Commandos", "Orzhov Guildgate", "Paranoid Delusions", "Pit Fight", "Predator's Rapport", "Primal Visitation", "Prophetic Prism", "Psychic Strike", "Purge the Profane", "Razortip Whip", "Riot Gear", "Ruination Wurm", "Sage's Row Denizen", "Scab-Clan Charger", "Scatter Arc", "Scorchwalker", "Shadow Alley Denizen", "Shadow Slice", "Shambleshark", "Shattering Blow", "Shielded Passage", "Simic Guildgate", "Skinbrand Goblin", "Skyblinder Staff", "Skygames", "Skyknight Legionnaire", "Slate Street Ruffian", "Slaughterhorn", "Smite", "Spell Rupture", "Spire Tracer", "Structural Collapse", "Syndic of Tithes", "Syndicate Enforcer", "Tin Street Market", "Totally Lost", "Towering Thunderfist", "Verdant Haven", "Warmind Infantry", "Way of the Thief", "Wildwood Rebirth", "Wojek Halberdiers", "Zarichi Tiger", "Zhur-Taa Swine");
		this.addCards(Rarity.UNCOMMON, "AEtherize", "Agoraphobia", "Alpha Authority", "Arrows of Justice", "Bane Alley Broker", "Boros Charm", "Boros Elite", "Boros Keyrune", "Burning-Tree Emissary", "Call of the Nightwing", "Cartel Aristocrat", "Cinder Elemental", "Coerced Confession", "Crackling Perimeter", "Crowned Ceratok", "Debtor's Pulpit", "Dimir Charm", "Dimir Keyrune", "Dinrova Horror", "Duskmantle Guildmage", "Dying Wish", "Elusive Krasis", "Experiment One", "Firefist Striker", "Fortress Cyclops", "Frenzied Tilling", "Gateway Shade", "Ghor-Clan Rampager", "Gift of Orzhova", "Gridlock", "Ground Assault", "Gruul Charm", "Gruul Keyrune", "Guardian of the Gateless", "Hellraiser Goblin", "Hindervines", "Hold the Gates", "Holy Mantle", "Homing Lightning", "Illness in the Ranks", "Incursion Specialist", "Killing Glare", "Knight of Obligation", "Mark for Death", "Mental Vapors", "Merfolk of the Depths", "Miming Slime", "Mindeye Drake", "Murder Investigation", "Nimbus Swimmer", "One Thousand Lashes", "Ordruun Veteran", "Orzhov Charm", "Orzhov Keyrune", "Rapid Hybridization", "Righteous Charge", "Ripscale Predator", "Rust Scarab", "Sapphire Drake", "Serene Remembrance", "Simic Charm", "Simic Fluxmage", "Simic Keyrune", "Skarrg Guildmage", "Skullcrack", "Smog Elemental", "Sunhome Guildmage", "Thrull Parasite", "Tower Defense", "Truefire Paladin", "Undercity Informer", "Urban Evolution", "Urbis Protector", "Viashino Shanktail", "Vizkopa Confessor", "Vizkopa Guildmage", "Voidwalk", "Wasteland Viper", "Wight of Precinct Six", "Zameck Guildmage");
		this.addCards(Rarity.RARE, "Alms Beast", "Angelic Skirmisher", "Assemble the Legion", "Biomass Mutation", "Biovisionary", "Blind Obedience", "Boros Reckoner", "Breeding Pool", "Clan Defiance", "Consuming Aberration", "Crypt Ghast", "Diluvian Primordial", "Fathom Mage", "Firemane Avenger", "Five-Alarm Fire", "Foundry Champion", "Frontline Medic", "Glaring Spotlight", "Godless Shrine", "Gruul Ragebeast", "Gyre Sage", "High Priest of Penance", "Illusionist's Bracers", "Immortal Servitude", "Legion Loyalist", "Luminate Primordial", "Merciless Eviction", "Mind Grind", "Molten Primordial", "Mystic Genesis", "Nightveil Specter", "Ogre Slumlord", "Ooze Flux", "Realmwright", "Rubblebelt Raiders", "Rubblehulk", "Sacred Foundry", "Sepulchral Primordial", "Signal the Clans", "Simic Manipulator", "Skarrg Goliath", "Soul Ransom", "Spark Trooper", "Stolen Identity", "Stomping Ground", "Sylvan Primordial", "Thespian's Stage", "Treasury Thrull", "Undercity Plague", "Unexpected Results", "Watery Grave", "Whispering Madness", "Wrecking Ogre");
		this.addCards(Rarity.MYTHIC, "Aurelia's Fury", "Aurelia, the Warleader", "Borborygmos Enraged", "Deathpact Angel", "Domri Rade", "Duskmantle Seer", "Enter the Infinite", "Giant Adephage", "Gideon, Champion of Justice", "Hellkite Tyrant", "Lazav, Dimir Mastermind", "Lord of the Void", "Master Biomancer", "Obzedat, Ghost Council", "Prime Speaker Zegana");
	}
}
