package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Guildpact")
public final class Guildpact extends SimpleExpansion
{
	public Guildpact()
	{
		super();

		this.addCards(Rarity.COMMON, "Absolver Thrull", "Beastmaster's Magemark", "Benediction of Moons", "Blind Hunter", "Bloodscale Prowler", "Burning-Tree Bloodscale", "Castigate", "Cremate", "Cry of Contrition", "Crystal Seer", "Douse in Gloom", "Fencer's Magemark", "Ghor-Clan Savage", "Ghost Warden", "Gigadrowse", "Gruul Nodorog", "Gruul Scrapper", "Gruul Signet", "Gruul Turf", "Guardian's Magemark", "Infiltrator's Magemark", "Izzet Boilerworks", "Izzet Chronarch", "Izzet Signet", "Leap of Flame", "Lionheart Maverick", "Mourning Thrull", "Necromancer's Magemark", "Ogre Savant", "Orzhov Basilica", "Orzhov Euthanist", "Orzhov Signet", "Ostiary Thrull", "Petrahydrox", "Pillory of the Sleepless", "Poisonbelly Ogre", "Pyromatics", "Repeal", "Restless Bones", "Runeboggle", "Scab-Clan Mauler", "Shrieking Grotesque", "Silhana Ledgewalker", "Silhana Starfletcher", "Skarrgan Pit-Skulk", "Skyrider Trainee", "Steamcore Weird", "Streetbreaker Wurm", "Tin Street Hooligan", "Torch Drake", "Train of Thought", "Wee Dragonauts", "Wild Cantor", "Wildsize", "Withstand");
		this.addCards(Rarity.UNCOMMON, "AEtherplasm", "Agent of Masks", "Battering Wurm", "Belfry Spirit", "Caustic Rain", "Conjurer's Ban", "Crash Landing", "Cryptwailing", "Daggerclaw Imp", "Droning Bureaucrats", "Drowned Rusalka", "Dryad Sophisticate", "Electrolyze", "Exhumer Thrull", "Feral Animist", "Frazzle", "Gatherer of Graces", "Gelectrode", "Ghor-Clan Bloodscale", "Goblin Flectomancer", "Gristleback", "Gruul Guildmage", "Harrier Griffin", "Hissing Miasma", "Hypervolt Grasp", "Izzet Guildmage", "Martyred Rusalka", "Mortify", "Nivix, Aerie of the Firemind", "Order of the Stars", "Orzhov Guildmage", "Orzhova, the Church of Deals", "Plagued Rusalka", "Predatory Focus", "Primeval Light", "Rabble-Rouser", "Revenant Patriarch", "Savage Twister", "Schismotivate", "Scorched Rusalka", "Shadow Lance", "Shattering Spree", "Sinstriker's Will", "Skarrg, the Rage Pits", "Skarrgan Skybreaker", "Smogsteed Rider", "Souls of the Faultless", "Starved Rusalka", "Stratozeppelid", "Thunderheads", "To Arms!", "Vacuumelt", "Vedalken Plotter", "Vertigo Spawn", "Wreak Havoc");
		this.addCards(Rarity.RARE, "Abyssal Nocturnus", "Angel of Despair", "Bioplasm", "Borborygmos", "Burning-Tree Shaman", "Cerebral Vortex", "Culling Sun", "Debtors' Knell", "Djinn Illuminatus", "Dune-Brood Nephilim", "Earth Surge", "Ghost Council of Orzhova", "Ghostway", "Giant Solifuge", "Glint-Eye Nephilim", "Godless Shrine", "Graven Dominator", "Gruul War Plow", "Hatching Plans", "Ink-Treader Nephilim", "Invoke the Firemind", "Killer Instinct", "Leyline of Lifeforce", "Leyline of Lightning", "Leyline of Singularity", "Leyline of the Meek", "Leyline of the Void", "Living Inferno", "Mimeofacture", "Mizzium Transreliquat", "Moratorium Stone", "Niv-Mizzet, the Firemind", "Orzhov Pontiff", "Parallectric Feedback", "Petrified Wood-Kin", "Quicken", "Rumbling Slum", "Sanguine Praetor", "Seize the Soul", "Siege of Towers", "Skarrgan Firebird", "Skeletal Vampire", "Sky Swallower", "Spelltithe Enforcer", "Steam Vents", "Stitch in Time", "Stomping Ground", "Storm Herd", "Sword of the Paruns", "Teysa, Orzhov Scion", "Tibor and Lumia", "Ulasht, the Hate Seed", "Witch-Maw Nephilim", "Wurmweaver Coil", "Yore-Tiller Nephilim");
	}
}
