package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Ice Age")
public final class IceAge extends SimpleExpansion
{
	public IceAge()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Snow-Covered Forest", "Snow-Covered Island", "Snow-Covered Mountain", "Snow-Covered Plains", "Snow-Covered Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Adarkar Unicorn", "Arctic Foxes", "Arenson's Aura", "Armor of Faith", "Arnjlot's Ascent", "Aurochs", "Balduvian Barbarians", "Balduvian Bears", "Balduvian Shaman", "Barbarian Guides", "Barbed Sextant", "Battle Frenzy", "Blessed Wine", "Bone Shaman", "Brainstorm", "Brine Shaman", "Brown Ouphe", "Burnt Offering", "Chub Toad", "Circle of Protection: Black", "Circle of Protection: Blue", "Circle of Protection: Green", "Circle of Protection: Red", "Circle of Protection: White", "Clairvoyance", "Cloak of Confusion", "Cooperation", "Counterspell", "Dark Banishing", "Dark Ritual", "Death Ward", "Dire Wolves", "Disenchant", "Earthlore", "Elvish Healer", "Enervate", "Errant Minion", "Errantry", "Essence Filter", "Essence Flare", "Fear", "Flare", "Folk of the Pines", "Foul Familiar", "Foxfire", "Fylgja", "Fyndhorn Brownie", "Fyndhorn Elves", "Gangrenous Zombies", "Gaze of Pain", "Giant Growth", "Goblin Sappers", "Goblin Ski Patrol", "Gorilla Pack", "Grizzled Wolverine", "Heal", "Hoar Shade", "Howl from Beyond", "Hydroblast", "Illusionary Forces", "Illusionary Wall", "Imposing Visage", "Incinerate", "Infuse", "Juniper Order Druid", "Kelsinko Ranger", "Kjeldoran Dead", "Kjeldoran Guard", "Kjeldoran Skyknight", "Kjeldoran Warrior", "Krovikan Fetish", "Krovikan Sorcerer", "Lava Burst", "Legions of Lim-Dûl", "Lim-Dûl's Cohort", "Meteor Shower", "Mind Ravel", "Mistfolk", "Moor Fiend", "Mountain Goat", "Mystic Remora", "Norritt", "Orcish Conscripts", "Orcish Farmer", "Orcish Lumberjack", "Panic", "Pestilence Rats", "Portent", "Power Sink", "Prismatic Ward", "Pyknite", "Pyroblast", "Rally", "Ray of Command", "Ray of Erasure", "Regeneration", "Rime Dryad", "Sabretooth Tiger", "Scaled Wurm", "Seizures", "Shambling Strider", "Shatter", "Shield Bearer", "Snow Devil", "Snowfall", "Songs of the Damned", "Soul Burn", "Soul Kiss", "Stone Rain", "Stonehands", "Tarpan", "Tinder Wall", "Tor Giant", "Touch of Death", "Warning", "Wild Growth", "Woolly Mammoths", "Woolly Spider", "Word of Undoing", "Zuran Enchanter", "Zuran Spellcaster");
		this.addCards(Rarity.UNCOMMON, "Abyssal Specter", "Adarkar Sentinel", "Aggression", "Anarchy", "Arcum's Sleigh", "Arcum's Weathervane", "Arcum's Whistle", "Ashen Ghoul", "Avalanche", "Balduvian Conjurer", "Baton of Morale", "Battle Cry", "Binding Grasp", "Black Scarab", "Blue Scarab", "Breath of Dreams", "Centaur Archer", "Cold Snap", "Conquer", "Dance of the Dead", "Demonic Consultation", "Diabolic Vision", "Dreams of the Dead", "Drift of the Dead", "Drought", "Essence Vortex", "Fanatical Fever", "Fire Covenant", "Flame Spirit", "Force Void", "Forgotten Lore", "Freyalise Supplicant", "Freyalise's Charm", "Fumarole", "Fyndhorn Bow", "Fyndhorn Elder", "Giant Trap Door Spider", "Glacial Chasm", "Glacial Wall", "Goblin Mutant", "Goblin Snowman", "Green Scarab", "Hallowed Ground", "Hematite Talisman", "Hipparion", "Hurricane", "Hyalopterous Lemure", "Hymn of Rebirth", "Ice Floe", "Iceberg", "Icequake", "Icy Manipulator", "Illusionary Terrain", "Jeweled Amulet", "Johtull Wurm", "Justice", "Karplusan Giant", "Kjeldoran Elite Guard", "Kjeldoran Frostbeast", "Kjeldoran Skycaptain", "Knight of Stromgald", "Krovikan Elementalist", "Krovikan Vampire", "Lapis Lazuli Talisman", "Leshrac's Rite", "Leshrac's Sigil", "Lim-Dûl's Hex", "Lure", "Maddening Wind", "Malachite Talisman", "Melee", "Melting", "Mind Warp", "Mole Worms", "Nacre Talisman", "Nature's Lore", "Onyx Talisman", "Orcish Cannoneers", "Orcish Healer", "Order of the White Shield", "Phantasmal Mount", "Pit Trap", "Pyroclasm", "Red Scarab", "Sacred Boon", "Sea Spirit", "Shield of the Ages", "Silver Erne", "Skull Catapult", "Sleight of Mind", "Snow Hound", "Soldevi Machinist", "Soldevi Simulacrum", "Soul Barrier", "Spectral Shield", "Stench of Evil", "Stone Spirit", "Sunstone", "Swords to Plowshares", "Thermokarst", "Thoughtleech", "Thunder Wall", "Touch of Vitae", "Updraft", "Urza's Bauble", "Venomous Breath", "Vertigo", "Walking Wall", "Wall of Lava", "Wall of Pine Needles", "Wall of Shields", "War Chariot", "Whalebone Glider", "White Scarab", "Whiteout", "Wind Spirit", "Wings of Aesthir", "Withering Wisps", "Word of Blasting", "Yavimaya Gnats", "Zuran Orb");
		this.addCards(Rarity.RARE, "Adarkar Wastes", "Aegis of the Meek", "Altar of Bone", "Amulet of Quoz", "Balduvian Hydra", "Blinking Spirit", "Blizzard", "Brand of Ill Omen", "Brushland", "Call to Arms", "Caribou Range", "Celestial Sword", "Chaos Lord", "Chaos Moon", "Chromatic Armor", "Crown of the Ages", "Curse of Marit Lage", "Deflection", "Despotic Scepter", "Dread Wight", "Dwarven Armory", "Earthlink", "Elder Druid", "Elemental Augury", "Elkin Bottle", "Enduring Renewal", "Energy Storm", "Fiery Justice", "Flooded Woodlands", "Flow of Maggots", "Forbidden Lore", "Formation", "Freyalise's Winds", "Fyndhorn Pollen", "Game of Chaos", "General Jarkeld", "Ghostly Flame", "Glacial Crevasses", "Glaciers", "Goblin Lyre", "Gravebind", "Halls of Mist", "Hecatomb", "Hot Springs", "Ice Cauldron", "Icy Prison", "Illusionary Presence", "Illusions of Grandeur", "Infernal Darkness", "Infernal Denizen", "Infinite Hourglass", "Jester's Cap", "Jester's Mask", "Jokulhaups", "Karplusan Forest", "Karplusan Yeti", "Kjeldoran Knight", "Kjeldoran Phalanx", "Kjeldoran Royal Guard", "Land Cap", "Lava Tubes", "Lhurgoyf", "Lightning Blow", "Lost Order of Jarkeld", "Magus of the Unseen", "Mercenaries", "Merieke Ri Berit", "Mesmeric Trance", "Mind Whip", "Minion of Leshrac", "Minion of Tevesh Szat", "Monsoon", "Mountain Titan", "Mudslide", "Musician", "Mystic Might", "Márton Stromgald", "Naked Singularity", "Necropotence", "Oath of Lim-Dûl", "Orcish Librarian", "Orcish Squatters", "Order of the Sacred Torch", "Pale Bears", "Pentagram of the Ages", "Polar Kraken", "Pox", "Pygmy Allosaurus", "Reality Twist", "Reclamation", "Ritual of Subdual", "River Delta", "Runed Arch", "Seraph", "Shyft", "Sibilant Spirit", "Skeleton Ship", "Snow Fortress", "Snowblind", "Soldevi Golem", "Spoils of Evil", "Spoils of War", "Staff of the Ages", "Stampede", "Storm Spirit", "Stormbind", "Stromgald Cabal", "Stunted Growth", "Sulfurous Springs", "Timberline Ridge", "Time Bomb", "Total War", "Trailblazer", "Underground River", "Veldt", "Vexing Arcanix", "Vibrating Sphere", "Wiitigo", "Winter's Chill", "Wrath of Marit Lage", "Zur's Weirding");
	}
}
