package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Innistrad")
public final class Innistrad extends SimpleExpansion
{
	public Innistrad()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Abbey Griffin", "Altar's Reap", "Ambush Viper", "Ancient Grudge", "Armored Skaab", "Ashmouth Hound", "Avacyn's Pilgrim", "Avacynian Priest", "Blazing Torch", "Bloodcrazed Neonate", "Bonds of Faith", "Brain Weevil", "Brimstone Volley", "Bump in the Night", "Caravan Vigil", "Chapel Geist", "Claustrophobia", "Cobbled Wings", "Corpse Lunge", "Crossway Vampire", "Curse of Oblivion", "Curse of the Bloody Tome", "Curse of the Pierced Heart", "Darkthicket Wolf", "Dead Weight", "Delver of Secrets", "Deranged Assistant", "Doomed Traveler", "Dream Twist", "Elder Cathar", "Feeling of Dread", "Feral Ridgewolf", "Festerhide Boar", "Forbidden Alchemy", "Fortress Crab", "Frightful Delusion", "Furor of the Bitten", "Geistflame", "Ghostly Possession", "Ghoulcaller's Bell", "Ghoulcaller's Chant", "Ghoulraiser", "Gnaw to the Bone", "Grave Bramble", "Grizzled Outcasts", "Gruesome Deformity", "Harvest Pyre", "Hysterical Blindness", "Infernal Plunge", "Kessig Wolf", "Kindercatch", "Lost in the Mist", "Makeshift Mauler", "Manor Skeleton", "Markov Patrician", "Maw of the Mire", "Moment of Heroism", "Moon Heron", "Moonmist", "Mulch", "Naturalize", "Night Revelers", "Night Terrors", "Nightbird's Clutches", "One-Eyed Scarecrow", "Orchard Spirit", "Pitchburn Devils", "Prey Upon", "Ranger's Guile", "Rebuke", "Riot Devils", "Rotting Fensnake", "Selfless Cathar", "Selhoff Occultist", "Sensory Deprivation", "Shimmering Grotto", "Silent Departure", "Silverchase Fox", "Skeletal Grimace", "Smite the Monstrous", "Somberwald Spider", "Spare from Evil", "Spectral Flight", "Spidery Grasp", "Stitched Drake", "Stitcher's Apprentice", "Stromkirk Patrol", "Think Twice", "Thraben Purebloods", "Thraben Sentry", "Tormented Pariah", "Traitorous Blood", "Travel Preparations", "Traveler's Amulet", "Typhoid Rats", "Unruly Mob", "Urgent Exorcism", "Vampire Interloper", "Vampiric Fury", "Victim of Night", "Village Bell-Ringer", "Village Ironsmith", "Villagers of Estwald", "Voiceless Spirit", "Walking Corpse", "Wooden Stake", "Woodland Sleuth");
		this.addCards(Rarity.UNCOMMON, "Abattoir Ghoul", "Battleground Geist", "Bitterheart Witch", "Boneyard Wurm", "Bramblecrush", "Burning Vengeance", "Butcher's Cleaver", "Cellar Door", "Civilized Scholar", "Cloistered Youth", "Curiosity", "Curse of the Nightly Hunt", "Demonmail Hauberk", "Desperate Ravings", "Diregraf Ghoul", "Disciple of Griselbrand", "Dissipate", "Falkenrath Noble", "Fiend Hunter", "Full Moon's Rise", "Gallows Warden", "Galvanic Juggernaut", "Gatstaf Shepherd", "Geistcatcher's Rig", "Ghost Quarter", "Grasp of Phantoms", "Graveyard Shovel", "Hamlet Captain", "Hanweir Watchkeep", "Hollowhenge Scavenger", "Inquisitor's Flail", "Intangible Virtue", "Into the Maw of Hell", "Invisible Stalker", "Lantern Spirit", "Lumberknot", "Make a Wish", "Mask of Avacyn", "Mausoleum Guard", "Memory's Journey", "Midnight Haunting", "Moan of the Unhallowed", "Morkrut Banshee", "Murder of Crows", "Paraselene", "Purify the Grave", "Rage Thrower", "Rakish Heir", "Rally the Peasants", "Reckless Waif", "Rolling Temblor", "Runic Repetition", "Scourge of Geier Reach", "Screeching Bat", "Sharpened Pitchfork", "Silver-Inlaid Dagger", "Skaab Goliath", "Skirsdag Cultist", "Slayer of the Wicked", "Spectral Rider", "Spider Spawning", "Trepanation Blade", "Tribute to Hunger", "Ulvenwald Mystics", "Unburial Rites", "Village Cannibals", "Wreath of Geists");
		this.addCards(Rarity.RARE, "Angel of Flight Alabaster", "Back from the Brink", "Blasphemous Act", "Bloodgift Demon", "Bloodline Keeper", "Cackling Counterpart", "Champion of the Parish", "Charmbreaker Devils", "Clifftop Retreat", "Creeping Renaissance", "Creepy Doll", "Curse of Death's Hold", "Curse of Stalked Prey", "Daybreak Ranger", "Dearly Departed", "Devil's Play", "Divine Reckoning", "Elder of Laurels", "Elite Inquisitor", "Endless Ranks of the Dead", "Evil Twin", "Falkenrath Marauders", "Gavony Township", "Geist-Honored Monk", "Gutter Grime", "Heartless Summoning", "Heretic's Punishment", "Hinterland Harbor", "Instigator Gang", "Isolated Chapel", "Kessig Cagebreakers", "Kessig Wolf Run", "Kruin Outlaw", "Laboratory Maniac", "Ludevic's Test Subject", "Manor Gargoyle", "Mayor of Avabruck", "Mentor of the Meek", "Mindshrieker", "Moldgraf Monstrosity", "Moorland Haunt", "Nephalia Drownyard", "Nevermore", "Parallel Lives", "Rooftop Storm", "Runechanter's Pike", "Sever the Bloodline", "Skirsdag High Priest", "Snapcaster Mage", "Splinterfright", "Stensia Bloodhall", "Stony Silence", "Stromkirk Noble", "Sturmgeist", "Sulfur Falls", "Unbreathing Horde", "Undead Alchemist", "Witchbane Orb", "Woodland Cemetery");
		this.addCards(Rarity.MYTHIC, "Angelic Overseer", "Army of the Damned", "Balefire Dragon", "Essence of the Wild", "Garruk Relentless", "Geist of Saint Traft", "Grimgrin, Corpse-Born", "Grimoire of the Dead", "Liliana of the Veil", "Mikaeus, the Lunarch", "Mirror-Mad Phantasm", "Olivia Voldaren", "Past in Flames", "Reaper from the Abyss", "Skaab Ruinator", "Tree of Redemption");
	}
}
