package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Invasion")
public final class Invasion extends SimpleExpansion
{
	public Invasion()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Aggressive Urge", "Agonizing Demise", "Ancient Kavu", "Ancient Spring", "Ardent Soldier", "Armadillo Cloak", "Barrin's Unmaking", "Benalish Lancer", "Benalish Trapper", "Bog Initiate", "Capashen Unicorn", "Crimson Acolyte", "Crown of Flames", "Cursed Flesh", "Dismantling Blow", "Dream Thrush", "Duskwalker", "Exclude", "Exotic Curse", "Explosive Growth", "Faerie Squadron", "Fertile Ground", "Firescreamer", "Frenzied Tilling", "Galina's Knight", "Geothermal Crevice", "Glimmering Angel", "Harrow", "Holy Day", "Hooded Kavu", "Hypnotic Cloud", "Irrigation Ditch", "Kavu Aggressor", "Kavu Climber", "Kavu Scout", "Llanowar Cavalry", "Llanowar Elite", "Llanowar Knight", "Llanowar Vanguard", "Maniacal Rage", "Metathran Zombie", "Mourning", "Nightscape Apprentice", "Nomadic Elf", "Obsidian Acolyte", "Opt", "Orim's Touch", "Overload", "Phantasmal Terrain", "Phyrexian Battleflies", "Phyrexian Reaper", "Phyrexian Slayer", "Pincer Spider", "Plague Spores", "Pouncing Kavu", "Prison Barricade", "Probe", "Prohibit", "Protective Sphere", "Quirion Elves", "Quirion Sentinel", "Quirion Trailblazer", "Rampant Elephant", "Ravenous Rats", "Razorfoot Griffin", "Recoil", "Recover", "Repulse", "Restrain", "Reviving Dose", "Rogue Kavu", "Savage Offensive", "Scarred Puma", "Scavenged Weaponry", "Scorching Lava", "Serpentine Kavu", "Shackles", "Shimmering Wings", "Shivan Zombie", "Shoreline Raider", "Slimy Kavu", "Soul Burn", "Stormscape Apprentice", "Strength of Unity", "Stun", "Sulfur Vent", "Sunscape Apprentice", "Tainted Well", "Thornscape Apprentice", "Thunderscape Apprentice", "Tidal Visionary", "Tinder Farm", "Tower Drake", "Tranquility", "Traveler's Cloak", "Tribal Flames", "Turf Wound", "Urborg Phantom", "Urborg Skeleton", "Viashino Grappler", "Vigorous Charge", "Vodalian Merchant", "Vodalian Serpent", "Vodalian Zombie", "Wandering Stream", "Whip Silk", "Wings of Hope", "Worldly Counsel", "Yavimaya Barbarian", "Zap");
		this.addCards(Rarity.UNCOMMON, "Addle", "Alloy Golem", "Angel of Mercy", "Angelic Shield", "Annihilate", "Archaeological Dig", "Assault // Battery", "Aura Shards", "Backlash", "Benalish Emissary", "Benalish Heralds", "Blinding Light", "Bloodstone Cameo", "Breath of Darigaaz", "Canopy Surge", "Cauldron Dance", "Chaotic Strike", "Charging Troll", "Chromatic Sphere", "Cinder Shade", "Coastal Tower", "Cremate", "Crosis's Attendant", "Darigaaz's Attendant", "Defiling Tears", "Disrupt", "Drake-Skull Cameo", "Dredge", "Dromar's Attendant", "Elfhame Palace", "Elfhame Sanctuary", "Essence Leak", "Fact or Fiction", "Firebrand Ranger", "Fires of Yavimaya", "Goblin Spy", "Goham Djinn", "Halam Djinn", "Hate Weaver", "Heroes' Reunion", "Horned Cheetah", "Hunting Kavu", "Kavu Chameleon", "Kavu Runner", "Liberate", "Lightning Dart", "Lobotomy", "Manipulate Fate", "Metathran Transport", "Might Weaver", "Ordered Migration", "Pain // Suffering", "Plague Spitter", "Pledge of Loyalty", "Power Armor", "Pulse of Llanowar", "Rage Weaver", "Rainbow Crow", "Reckless Spite", "Reviving Vapors", "Rewards of Diversity", "Riptide Crab", "Rith's Attendant", "Rooting Kavu", "Ruham Djinn", "Salt Marsh", "Samite Archer", "Samite Ministration", "Scouting Trek", "Searing Rays", "Seashell Cameo", "Seer's Vision", "Shivan Emissary", "Shivan Harvest", "Shivan Oasis", "Simoon", "Skittish Kavu", "Sky Weaver", "Sleeper's Robe", "Slinking Serpent", "Smoldering Tar", "Sparring Golem", "Spirit Weaver", "Spite // Malice", "Stand // Deliver", "Sterling Grove", "Sulam Djinn", "Sway of Illusion", "Tangle", "Teferi's Care", "Tigereye Cameo", "Tolarian Emissary", "Treefolk Healer", "Trench Wurm", "Treva's Attendant", "Troll-Horn Cameo", "Urborg Drake", "Urborg Emissary", "Urborg Shambler", "Urborg Volcano", "Verduran Emissary", "Vicious Kavu", "Vodalian Hypnotist", "Voracious Cobra", "Wallop", "Wash Out", "Wax // Wane", "Wayfaring Giant", "Yavimaya Kavu", "Zanam Djinn");
		this.addCards(Rarity.RARE, "AEther Rift", "Absorb", "Alabaster Leech", "Andradite Leech", "Armored Guardian", "Artifact Mutation", "Atalya, Samite Master", "Aura Mutation", "Barrin's Spite", "Bend or Break", "Bind", "Blazing Specter", "Blind Seer", "Blurred Mongoose", "Breaking Wave", "Callous Giant", "Captain Sisay", "Coalition Victory", "Collapsing Borders", "Collective Restraint", "Crosis, the Purger", "Crusading Knight", "Crypt Angel", "Crystal Spray", "Darigaaz, the Igniter", "Death or Glory", "Desperate Research", "Devouring Strossus", "Distorting Wake", "Divine Presence", "Do or Die", "Dromar, the Banisher", "Dueling Grounds", "Elvish Champion", "Empress Galina", "Fight or Flight", "Ghitu Fire", "Global Ruin", "Hanna, Ship's Navigator", "Harsh Judgment", "Jade Leech", "Juntu Stakes", "Kangee, Aerie Keeper", "Kavu Lair", "Kavu Monarch", "Kavu Titan", "Keldon Necropolis", "Loafing Giant", "Lotus Guardian", "Mages' Contest", "Mana Maze", "Marauding Knight", "Metathran Aerostat", "Meteor Storm", "Molimo, Maro-Sorcerer", "Nightscape Master", "Noble Panther", "Obliterate", "Overabundance", "Phyrexian Altar", "Phyrexian Delver", "Phyrexian Infiltrator", "Phyrexian Lens", "Planar Portal", "Psychic Battle", "Pure Reflection", "Pyre Zombie", "Raging Kavu", "Reckless Assault", "Restock", "Reya Dawnbringer", "Rith, the Awakener", "Rout", "Ruby Leech", "Sabertooth Nishoba", "Sapphire Leech", "Saproling Infestation", "Saproling Symbiosis", "Skizzik", "Spinal Embrace", "Spirit of Resistance", "Spreading Plague", "Stalking Assassin", "Stand or Fall", "Stormscape Master", "Sunscape Master", "Tectonic Instability", "Teferi's Moat", "Teferi's Response", "Tek", "Temporal Distortion", "Thicket Elemental", "Thornscape Master", "Thunderscape Master", "Treva, the Renewer", "Tsabo Tavoc", "Tsabo's Assassin", "Tsabo's Decree", "Tsabo's Web", "Twilight's Call", "Undermine", "Urza's Filter", "Urza's Rage", "Utopia Tree", "Verdeloth the Ancient", "Vile Consumption", "Void", "Well-Laid Plans", "Winnow", "Yawgmoth's Agenda");
	}
}
