package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Journey into Nyx")
public final class JourneyIntoNyx extends SimpleExpansion
{
	public JourneyIntoNyx()
	{
		super();

		this.addCards(Rarity.COMMON, "Aerial Formation", "Ajani's Presence", "Akroan Mastiff", "Armament of Nyx", "Aspect of Gorgon", "Bladetusk Boar", "Bloodcrazed Hoplite", "Cast into Darkness", "Cloaked Siren", "Countermand", "Cruel Feeding", "Desecration Plague", "Dreadbringer Lampads", "Eagle of the Watch", "Feast of Dreams", "Flamespeaker's Will", "Flurry of Horns", "Font of Fertility", "Font of Fortunes", "Font of Ire", "Font of Return", "Font of Vigor", "Gluttonous Cyclops", "Godhunter Octopus", "Golden Hind", "Grim Guardian", "Harvestguard Alseids", "Hubris", "Humbler of Mortals", "Kruphix's Insight", "Lagonna-Band Trailblazer", "Lightning Diadem", "Magma Spray", "Market Festival", "Mortal Obstinacy", "Nature's Panoply", "Nyx Infusion", "Oakheart Dryads", "Oppressive Rays", "Oreskos Swiftclaw", "Pensive Minotaur", "Pharika's Chosen", "Pheres-Band Thunderhoof", "Pin to the Earth", "Ravenous Leucrocota", "Renowned Weaver", "Returned Reveler", "Rise of Eagles", "Rotted Hulk", "Rouse the Mob", "Satyr Grovedancer", "Satyr Hoplite", "Sigiled Skink", "Sigiled Starfish", "Starfall", "Stonewise Fortifier", "Supply-Line Cranes", "Thassa's Devourer", "Triton Shorestalker", "War-Wing Siren");
		this.addCards(Rarity.UNCOMMON, "Agent of Erebos", "Akroan Line Breaker", "Armory of Iroas", "Banishing Light", "Bassara Tower Archer", "Blinding Flare", "Brain Maggot", "Chariot of Victory", "Colossal Heroics", "Consign to Dust", "Crystalline Nautilus", "Cyclops of Eternal Fury", "Dakra Mystic", "Deserter's Quarters", "Desperate Stand", "Disciple of Deceit", "Eidolon of Rhetoric", "Felhide Petrifier", "Fleetfeather Cockatrice", "Forgeborn Oreads", "Gnarled Scarhide", "Gold-Forged Sentinel", "Goldenhide Ox", "Hour of Need", "Interpret the Signs", "Kiora's Dismissal", "Knowledge and Power", "Leonin Iconoclast", "Mogis's Warhound", "Nessian Game Warden", "Nightmarish End", "Nyx Weaver", "Nyx-Fleece Ram", "Phalanx Formation", "Pull from the Deep", "Quarry Colossus", "Reprisal", "Reviving Melody", "Riddle of Lightning", "Riptide Chimera", "Ritual of the Returned", "Rollick of Abandon", "Sightless Brawler", "Skyspear Cavalry", "Solidarity of Heroes", "Spirespine", "Spite of Mogis", "Spiteful Blow", "Squelching Leeches", "Stormchaser Chimera", "Strength from the Fallen", "Swarmborn Giant", "Tethmos High Priest", "Thassa's Ire", "Thoughtrender Lamia", "Tormented Thoughts", "Triton Cavalry", "Underworld Coinsmith", "Whitewater Naiads", "Wildfire Cerberus");
		this.addCards(Rarity.RARE, "Aegis of the Gods", "Battlefield Thaumaturge", "Bearer of the Heavens", "Daring Thief", "Dawnbringer Charioteers", "Deicide", "Dictate of Erebos", "Dictate of Heliod", "Dictate of Karametra", "Dictate of Kruphix", "Dictate of the Twin Gods", "Doomwake Giant", "Eidolon of Blossoms", "Eidolon of the Great Revel", "Extinguish All Hope", "Hall of Triumph", "Harness by Force", "Heroes' Bane", "Hydra Broodmaster", "Hypnotic Siren", "King Macar, the Gold-Cursed", "Launch the Fleet", "Mana Confluence", "Master of the Feast", "Pheres-Band Warchief", "Polymorphous Rush", "Revel of the Fallen God", "Scourge of Fleets", "Setessan Tactics", "Silence the Believers", "Skybind", "Spawn of Thraxes", "Temple of Epiphany", "Temple of Malady", "Twinflame");
		this.addCards(Rarity.MYTHIC, "Ajani, Mentor of Heroes", "Athreos, God of Passage", "Godsend", "Iroas, God of Victory", "Keranos, God of Storms", "Kruphix, God of Horizons", "Pharika, God of Affliction", "Prophetic Flamespeaker", "Sage of Hours", "Worst Fears");
	}
}
