package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Legends")
public final class Legends extends SimpleExpansion
{
	public Legends()
	{
		super();

		this.addCards(Rarity.COMMON, "Active Volcano", "Aisling Leprechaun", "Alabaster Potion", "Amrou Kithkin", "Anti-Magic Aura", "Avoid Fate", "Barbary Apes", "Blazing Effigy", "Boomerang", "Cat Warriors", "Chain Lightning", "Clergy of the Holy Nimbus", "Crimson Kobolds", "Crookshank Kobolds", "Cyclopean Mummy", "D'Avenant Archer", "Darkness", "Devouring Deep", "Divine Offering", "Durkwood Boars", "Emerald Dragonfly", "Enchanted Being", "Enchantment Alteration", "Energy Tap", "Equinox", "Feint", "Fire Sprites", "Flash Counter", "Flash Flood", "Force Spike", "Gaseous Form", "Ghosts of the Damned", "Giant Slug", "Giant Strength", "Giant Turtle", "Glyph of Delusion", "Glyph of Destruction", "Glyph of Doom", "Glyph of Life", "Glyph of Reincarnation", "Headless Horseman", "Hell Swarm", "Holy Day", "Hornet Cobra", "Immolation", "Indestructible Aura", "Keepers of the Faith", "Kobolds of Kher Keep", "Lost Soul", "Moss Monster", "Osai Vultures", "Pit Scorpion", "Psychic Purge", "Pyrotechnics", "Raging Bull", "Remove Enchantments", "Remove Soul", "Rust", "Shelkin Brownie", "Spirit Shackle", "Subdue", "Syphon Soul", "The Brute", "Transmutation", "Tundra Wolves", "Vampire Bats", "Venarian Gold", "Walking Dead", "Wall of Caltrops", "Wall of Earth", "Wall of Heat", "Wall of Shadows", "Wall of Vapor", "Wolverine Pack", "Zephyr Falcon");
		this.addCards(Rarity.UNCOMMON, "AErathi Berserker", "Abomination", "Adventurers' Guildhouse", "Arboria", "Azure Drake", "Backdraft", "Backfire", "Barktooth Warbeard", "Beasts of Bogardan", "Black Mana Battery", "Blight", "Blood Lust", "Blue Mana Battery", "Brine Hag", "Cathedral of Serra", "Cocoon", "Craw Giant", "Crevasse", "Deadfall", "Demonic Torment", "Dream Coat", "Dwarven Song", "Eternal Warrior", "Evil Eye of Orms-by-Gore", "Fallen Angel", "Floral Spuzzem", "Fortified Area", "Frost Giant", "Great Defender", "Great Wall", "Greater Realm of Preservation", "Green Mana Battery", "Hammerheim", "Heaven's Gate", "Horror of Horrors", "Hunding Gjornersen", "Hyperion Blacksmith", "Ichneumon Druid", "Infernal Medusa", "Ivory Guardians", "Jasmine Boreal", "Jedit Ojanen", "Jerrard of the Closed Fist", "Karakas", "Kasimir the Lone Wolf", "Kismet", "Kobold Drill Sergeant", "Kobold Taskmaster", "Kry Shield", "Lady Orca", "Land Tax", "Lesser Werewolf", "Life Chisel", "Lord Magnus", "Mana Drain", "Marble Priest", "Marhault Elsdragon", "Mountain Stronghold", "Mountain Yeti", "Part Water", "Pavel Maliki", "Pendelhaven", "Pradesh Gypsies", "Presence of the Master", "Primordial Ooze", "Princess Lucrezia", "Puppet Master", "Quagmire", "Rabid Wombat", "Radjan Spirit", "Ramirez DePietro", "Red Mana Battery", "Reincarnation", "Relic Barrier", "Relic Bind", "Reset", "Righteous Avengers", "Riven Turnbull", "Sea Kings' Blessing", "Seafarer's Quay", "Seeker", "Segovian Leviathan", "Shield Wall", "Shimian Night Stalker", "Silhouette", "Sir Shandlar of Eberyn", "Sivitri Scarzam", "Spectral Cloak", "Spirit Link", "Storm Seeker", "Sunastian Falconer", "Sylvan Library", "Sylvan Paradise", "Takklemaggot", "The Lady of the Mountain", "Tobias Andrion", "Tolaria", "Tor Wauki", "Torsten Von Ursus", "Touch of Darkness", "Undertow", "Underworld Dreams", "Unholy Citadel", "Untamed Wilds", "Urborg", "Visions", "Wall of Dust", "Wall of Light", "Wall of Putrid Flesh", "Wall of Tombstones", "Wall of Wonder", "Whirling Dervish", "White Mana Battery", "Winds of Change");
		this.addCards(Rarity.RARE, "Acid Rain", "Adun Oakenshield", "Akron Legionnaire", "Al-abara's Carpet", "Alchor's Tomb", "All Hallow's Eve", "Angelic Voices", "Angus Mackenzie", "Arcades Sabboth", "Arena of the Ancients", "Axelrod Gunnarson", "Ayesha Tanaka", "Bartel Runeaxe", "Boris Devilboon", "Bronze Horse", "Carrion Ants", "Caverns of Despair", "Chains of Mephistopheles", "Chromium", "Cleanse", "Concordant Crossroads", "Cosmic Horror", "Crimson Manticore", "Dakkon Blackblade", "Disharmony", "Divine Intervention", "Divine Transformation", "Elder Land Wurm", "Elder Spawn", "Elven Riders", "Eureka", "Falling Star", "Field of Dreams", "Firestorm Phoenix", "Forethought Amulet", "Gabriel Angelfire", "Gauntlets of Chaos", "Gosta Dirk", "Gravity Sphere", "Greed", "Gwendlyn Di Corci", "Halfdane", "Hazezon Tamar", "Hell's Caretaker", "Hellfire", "Horn of Deafening", "Imprison", "In the Eye of Chaos", "Infinite Authority", "Invoke Prejudice", "Jacques le Vert", "Johan", "Jovial Evil", "Juxtapose", "Kei Takahashi", "Killer Bees", "Knowledge Vault", "Kobold Overlord", "Lady Caleria", "Lady Evangela", "Land Equilibrium", "Land's Edge", "Life Matrix", "Lifeblood", "Living Plane", "Livonya Silone", "Mana Matrix", "Master of the Hunt", "Mirror Universe", "Moat", "Mold Demon", "Nebuchadnezzar", "Nether Void", "Nicol Bolas", "North Star", "Nova Pentacle", "Palladia-Mors", "Petra Sphinx", "Pixie Queen", "Planar Gate", "Psionic Entity", "Quarum Trench Gnomes", "Ragnar", "Ramses Overdark", "Rapid Fire", "Rasputin Dreamweaver", "Rebirth", "Recall", "Revelation", "Reverberation", "Ring of Immortals", "Rohgahh of Kher Keep", "Rubinia Soulsinger", "Sentinel", "Serpent Generator", "Sol'kanar the Swamp King", "Spinal Villain", "Spiritual Sanctuary", "Stangg", "Storm World", "Sword of the Ages", "Telekinesis", "Teleport", "Tempest Efreet", "Tetsuo Umezawa", "The Abyss", "The Tabernacle at Pendrell Vale", "The Wretched", "Thunder Spirit", "Time Elemental", "Triassic Egg", "Tuknir Deathlock", "Typhoon", "Ur-Drago", "Vaevictis Asmadi", "Voodoo Doll", "Wall of Opposition", "Willow Satyr", "Winter Blast", "Wood Elemental", "Xira Arien");
	}
}
