package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Limited Edition Alpha")
public final class LimitedEditionAlpha extends SimpleExpansion
{
	public LimitedEditionAlpha()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Island", "Island", "Mountain", "Mountain", "Plains", "Plains", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Benalish Hero", "Blue Elemental Blast", "Circle of Protection: Blue", "Circle of Protection: Green", "Circle of Protection: Red", "Circle of Protection: White", "Craw Wurm", "Creature Bond", "Dark Ritual", "Death Ward", "Disenchant", "Disintegrate", "Drain Life", "Drudge Skeletons", "Dwarven Warriors", "Earthbind", "False Orders", "Fear", "Fireball", "Firebreathing", "Flight", "Fog", "Frozen Shade", "Giant Growth", "Giant Spider", "Gray Ogre", "Grizzly Bears", "Guardian Angel", "Healing Salve", "Hill Giant", "Holy Armor", "Holy Strength", "Howl from Beyond", "Hurloon Minotaur", "Invisibility", "Ironclaw Orcs", "Ironroot Treefolk", "Jump", "Lightning Bolt", "Llanowar Elves", "Merfolk of the Pearl Trident", "Mesa Pegasus", "Mons's Goblin Raiders", "Paralyze", "Pearled Unicorn", "Pestilence", "Phantasmal Terrain", "Plague Rats", "Power Leak", "Power Sink", "Prodigal Sorcerer", "Psychic Venom", "Raise Dead", "Red Elemental Blast", "Regeneration", "Samite Healer", "Scathe Zombies", "Scryb Sprites", "Sea Serpent", "Shanodin Dryads", "Shatter", "Sinkhole", "Spell Blast", "Stone Rain", "Stream of Life", "Terror", "Tranquility", "Twiddle", "Unholy Strength", "Unsummon", "Wall of Wood", "War Mammoth", "Weakness", "Wild Growth");
		this.addCards(Rarity.UNCOMMON, "Air Elemental", "Animate Artifact", "Animate Dead", "Basalt Monolith", "Berserk", "Black Knight", "Black Vise", "Black Ward", "Blue Ward", "Bog Wraith", "Burrowing", "Camouflage", "Castle", "Celestial Prism", "Channel", "Clone", "Consecrate Land", "Conservator", "Control Magic", "Conversion", "Copper Tablet", "Counterspell", "Crystal Rod", "Cursed Land", "Deathgrip", "Demonic Tutor", "Dragon Whelp", "Dwarven Demolition Team", "Earth Elemental", "Evil Presence", "Feedback", "Fire Elemental", "Flashfires", "Glasses of Urza", "Gloom", "Goblin Balloon Brigade", "Green Ward", "Hurricane", "Hypnotic Specter", "Ice Storm", "Icy Manipulator", "Instill Energy", "Iron Star", "Ivory Cup", "Jade Statue", "Juggernaut", "Karma", "Keldon Warlord", "Lance", "Ley Druid", "Library of Leng", "Lifeforce", "Lifetap", "Living Wall", "Lure", "Nettling Imp", "Obsianus Golem", "Orcish Artillery", "Orcish Oriflamme", "Phantasmal Forces", "Phantom Monster", "Psionic Blast", "Red Ward", "Regrowth", "Resurrection", "Rod of Ruin", "Sacrifice", "Scavenging Ghoul", "Sengir Vampire", "Serra Angel", "Simulacrum", "Siren's Call", "Sol Ring", "Soul Net", "Steal Artifact", "Stone Giant", "Swords to Plowshares", "Thicket Basilisk", "Throne of Bone", "Tsunami", "Tunnel", "Uthden Troll", "Wall of Air", "Wall of Bone", "Wall of Brambles", "Wall of Fire", "Wall of Ice", "Wall of Stone", "Wall of Swords", "Wall of Water", "Wanderlust", "Water Elemental", "White Knight", "White Ward", "Wooden Sphere");
		this.addCards(Rarity.RARE, "Ancestral Recall", "Animate Wall", "Ankh of Mishra", "Armageddon", "Aspect of Wolf", "Bad Moon", "Badlands", "Balance", "Bayou", "Birds of Paradise", "Black Lotus", "Blaze of Glory", "Blessing", "Braingeyser", "Chaos Orb", "Chaoslace", "Clockwork Beast", "Cockatrice", "Contract from Below", "Copy Artifact", "Crusade", "Cyclopean Tomb", "Darkpact", "Deathlace", "Demonic Attorney", "Demonic Hordes", "Dingus Egg", "Disrupting Scepter", "Drain Power", "Earthquake", "Elvish Archers", "Farmstead", "Fastbond", "Force of Nature", "Forcefield", "Fork", "Fungusaur", "Gaea's Liege", "Gauntlet of Might", "Goblin King", "Granite Gargoyle", "Helm of Chatzuk", "Howling Mine", "Illusionary Mask", "Island Sanctuary", "Jade Monolith", "Jayemdae Tome", "Kormus Bell", "Kudzu", "Lich", "Lifelace", "Living Artifact", "Living Lands", "Lord of Atlantis", "Lord of the Pit", "Magical Hack", "Mahamoti Djinn", "Mana Flare", "Mana Short", "Mana Vault", "Manabarbs", "Meekstone", "Mind Twist", "Mox Emerald", "Mox Jet", "Mox Pearl", "Mox Ruby", "Mox Sapphire", "Natural Selection", "Nether Shadow", "Nevinyrral's Disk", "Nightmare", "Northern Paladin", "Personal Incarnation", "Pirate Ship", "Plateau", "Power Surge", "Purelace", "Raging River", "Reverse Damage", "Righteousness", "Roc of Kher Ridges", "Rock Hydra", "Royal Assassin", "Savannah", "Savannah Lions", "Scrubland", "Sedge Troll", "Shivan Dragon", "Sleight of Mind", "Smoke", "Stasis", "Sunglasses of Urza", "Taiga", "The Hive", "Thoughtlace", "Timber Wolves", "Time Vault", "Time Walk", "Timetwister", "Tropical Island", "Tundra", "Two-Headed Giant of Foriys", "Underground Sea", "Verduran Enchantress", "Vesuvan Doppelganger", "Veteran Bodyguard", "Volcanic Eruption", "Warp Artifact", "Web", "Wheel of Fortune", "Will-o'-the-Wisp", "Winter Orb", "Word of Command", "Wrath of God", "Zombie Master");
	}
}
