package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Lorwyn")
public final class Lorwyn extends SimpleExpansion
{
	public Lorwyn()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "AEthersnipe", "Adder-Staff Boggart", "Amoeboid Changeling", "Aquitect's Will", "Avian Changeling", "Axegrinder Giant", "Battlewand Oak", "Black Poplar Shaman", "Blades of Velis Vel", "Blind-Spot Giant", "Bog Hoodlums", "Bog-Strider Ash", "Boggart Birth Rite", "Boggart Forager", "Boggart Loggers", "Boggart Sprite-Chaser", "Broken Ambitions", "Caterwauling Boggart", "Cenn's Heir", "Cloudcrown Oak", "Consuming Bonfire", "Dawnfluke", "Deeptread Merrow", "Dreamspoiler Witches", "Elvish Branchbender", "Elvish Eulogist", "Elvish Handservant", "Exiled Boggart", "Eyeblight's Ending", "Facevaulter", "Faerie Trickery", "Faultgrinder", "Fertile Ground", "Fire-Belly Changeling", "Fistful of Force", "Flamekin Brawler", "Footbottom Feast", "Giant's Ire", "Gilt-Leaf Ambush", "Gilt-Leaf Seer", "Glimmerdust Nap", "Goldmeadow Dodger", "Goldmeadow Harrier", "Heal the Scars", "Herbal Poultice", "Hillcomber Giant", "Hornet Harasser", "Hunt Down", "Hurly-Burly", "Ingot Chewer", "Inkfathom Divers", "Inner-Flame Acolyte", "Judge of Currents", "Kinsbaile Balloonist", "Kinsbaile Skirmisher", "Kithkin Daggerdare", "Kithkin Greatheart", "Kithkin Healer", "Lace with Moonglove", "Lairwatch Giant", "Lash Out", "Leaf Gilder", "Lignify", "Lowland Oaf", "Lys Alana Huntmaster", "Moonglove Extract", "Moonglove Winnower", "Mournwhelk", "Mudbutton Torchrunner", "Mulldrifter", "Nameless Inversion", "Nath's Buffoon", "Nath's Elite", "Neck Snap", "Needle Drop", "Nightshade Stinger", "Oaken Brawler", "Oakgnarl Warrior", "Oblivion Ring", "Paperfin Rascal", "Peppersmoke", "Pestermite", "Plover Knights", "Ponder", "Protective Bubble", "Quill-Slinger Boggart", "Ringskipper", "Rootgrapple", "Runed Stalactite", "Scarred Vinebreeder", "Sentinels of Glen Elendra", "Shields of Velis Vel", "Shimmering Grotto", "Silvergill Douser", "Skeletal Changeling", "Smokebraider", "Soaring Hope", "Soulbright Flamekin", "Spellstutter Sprite", "Spiderwig Boggart", "Spring Cleaning", "Springjack Knight", "Springleaf Drum", "Stinkdrinker Daredevil", "Stonybrook Angler", "Streambed Aquitects", "Surge of Thoughtweft", "Tarfire", "Thieving Sprite", "Tideshaper Mystic", "Triclopean Sight", "Wanderer's Twig", "Warren Pilferers", "Warren-Scourge Elf", "Weed Strangle", "Wellgabber Apothecary", "Whirlpool Whelm", "Wings of Velis Vel", "Wispmare", "Woodland Changeling", "Zephyr Net");
		this.addCards(Rarity.UNCOMMON, "Battle Mastery", "Benthicore", "Boggart Harbinger", "Boggart Shenanigans", "Briarhorn", "Burrenton Forge-Tender", "Captivating Glance", "Ceaseless Searblades", "Changeling Berserker", "Changeling Hero", "Changeling Titan", "Cloudgoat Ranger", "Crib Swap", "Crush Underfoot", "Drowner of Secrets", "Ego Erasure", "Elvish Harbinger", "Elvish Promenade", "Entangling Trap", "Ethereal Whiskergill", "Faerie Harbinger", "Faerie Tauntings", "Fallowsage", "Familiar's Ruse", "Final Revels", "Flamekin Bladewhirl", "Flamekin Harbinger", "Flamekin Spitfire", "Fodder Launch", "Ghostly Changeling", "Giant Harbinger", "Glarewielder", "Glen Elendra Pranksters", "Goatnapper", "Goldmeadow Stalwart", "Guardian of Cloverdell", "Harpoon Sniper", "Hearthcage Giant", "Hoarder's Greed", "Hunter of Eyeblights", "Imperious Perfect", "Incremental Growth", "Inner-Flame Igniter", "Jagged-Scar Archers", "Kithkin Harbinger", "Kithkin Mourncaller", "Knight of Meadowgrain", "Lammastide Weave", "Lys Alana Scarblade", "Makeshift Mannequin", "Marsh Flitter", "Merrow Commerce", "Merrow Harbinger", "Merrow Reejerey", "Nectar Faerie", "Pollen Lullaby", "Prowess of the Fair", "Rebellion of the Flamekin", "Scattering Stroke", "Seedguide Ash", "Sentry Oak", "Shriekmaw", "Silvergill Adept", "Squeaking Pie Sneak", "Summon the School", "Sylvan Echoes", "Tar Pitcher", "Thorntooth Witch", "Thundercloud Shaman", "Treefolk Harbinger", "Turtleshell Changeling", "Veteran of the Depths", "Vivid Crag", "Vivid Creek", "Vivid Grove", "Vivid Marsh", "Vivid Meadow", "Wizened Cenn", "Woodland Guidance", "Wren's Run Vanquisher");
		this.addCards(Rarity.RARE, "Ajani Goldmane", "Ancient Amphitheater", "Arbiter of Knollridge", "Ashling the Pilgrim", "Ashling's Prerogative", "Auntie's Hovel", "Austere Command", "Boggart Mob", "Brigid, Hero of Kinsbaile", "Brion Stoutarm", "Cairn Wanderer", "Chandra Nalaar", "Cloudthresher", "Colfenor's Plans", "Colfenor's Urn", "Cryptic Command", "Dauntless Dourbark", "Deathrender", "Dolmen Gate", "Doran, the Siege Tower", "Dread", "Epic Proportions", "Eyes of the Wisent", "Fathom Trawl", "Favor of the Mighty", "Forced Fruition", "Gaddock Teeg", "Galepowder Mage", "Garruk Wildspeaker", "Gilt-Leaf Palace", "Guile", "Hamletback Goliath", "Heat Shimmer", "Hoofprints of the Stag", "Horde of Notions", "Hostility", "Howltooth Hollow", "Immaculate Magistrate", "Incandescent Soulstoke", "Incendiary Command", "Jace Beleren", "Knucklebone Witch", "Liliana Vess", "Mad Auntie", "Masked Admirers", "Militia's Pride", "Mirror Entity", "Mistbind Clique", "Mosswort Bridge", "Nath of the Gilt-Leaf", "Nettlevine Blight", "Nova Chaser", "Oona's Prowler", "Primal Command", "Profane Command", "Purity", "Rings of Brighthearth", "Scion of Oona", "Secluded Glen", "Shapesharer", "Shelldock Isle", "Sower of Temptation", "Spinerock Knoll", "Sunrise Sovereign", "Surgespanner", "Sygg, River Guide", "Thorn of Amethyst", "Thoughtseize", "Thoughtweft Trio", "Thousand-Year Elixir", "Timber Protector", "Twinning Glass", "Vigor", "Wanderwine Hub", "Wanderwine Prophets", "Wild Ricochet", "Windbrisk Heights", "Wort, Boggart Auntie", "Wren's Run Packmaster", "Wydwen, the Biting Gale");
	}
}
