package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Magic 2015 Core Set")
public final class Magic2015CoreSet extends SimpleExpansion
{
	public Magic2015CoreSet()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Accursed Spirit", "Aeronaut Tinkerer", "Amphin Pathmage", "Black Cat", "Blastfire Bolt", "Borderland Marauder", "Bronze Sable", "Cancel", "Carnivorous Moss-Beast", "Carrion Crow", "Centaur Courser", "Charging Rhino", "Child of Night", "Chronostutter", "Clear a Path", "Coral Barrier", "Covenant of Blood", "Crippling Blight", "Crowd's Favor", "Divination", "Divine Favor", "Divine Verdict", "Elvish Mystic", "Encrust", "Ephemeral Shields", "Eternal Thirst", "Evolving Wilds", "Festergloom", "Flesh to Dust", "Forge Devil", "Foundry Street Denizen", "Frost Lynx", "Fugitive Wizard", "Generator Servant", "Glacial Crasher", "Goblin Roughrider", "Hammerhand", "Heliod's Pilgrim", "Hunt the Weak", "Hunter's Ambush", "Hydrosurge", "Inferno Fist", "Inspired Charge", "Invasive Species", "Invisibility", "Kinsbaile Skirmisher", "Krenko's Enforcer", "Lava Axe", "Lightning Strike", "Living Totem", "Marked by Honor", "Meditation Puzzle", "Midnight Guard", "Mind Rot", "Mind Sculpt", "Miner's Bane", "Naturalize", "Necrobite", "Necromancer's Assistant", "Negate", "Netcaster Spider", "Nimbus of the Isles", "Oppressive Rays", "Oreskos Swiftclaw", "Ornithopter", "Peel from Reality", "Pillar of Light", "Plummet", "Radiant Fountain", "Raise the Alarm", "Ranger's Guile", "Razorfoot Griffin", "Research Assistant", "Rotfeaster Maggot", "Rummaging Goblin", "Runeclaw Bear", "Sanctified Charge", "Satyr Wayfinder", "Scrapyard Mongrel", "Seismic Strike", "Selfless Cathar", "Shadowcloak Vampire", "Shaman of Spring", "Siege Wurm", "Sign in Blood", "Solemn Offering", "Soulmender", "Statute of Denial", "Sungrace Pegasus", "Thundering Giant", "Tireless Missionaries", "Titanic Growth", "Torch Fiend", "Triplicate Spirits", "Typhoid Rats", "Tyrant's Machine", "Undergrowth Scavenger", "Unmake the Graves", "Verdant Haven", "Vineweft", "Void Snare", "Walking Corpse", "Wall of Fire", "Welkin Tern", "Will-Forged Golem", "Witch's Familiar", "Zof Shade");
		this.addCards(Rarity.UNCOMMON, "Act on Impulse", "Ajani's Pridemate", "Altac Bloodseeker", "Ancient Silverback", "Back to Nature", "Battle Mastery", "Belligerent Sliver", "Blood Host", "Boonweaver Giant", "Brawler's Plate", "Brood Keeper", "Caustic Tar", "Circle of Flame", "Cone of Flame", "Congregate", "Constricting Sliver", "Darksteel Citadel", "Dauntless River Marshal", "Devouring Light", "Diffusion Sliver", "Dissipate", "Endless Obedience", "Ensoul Artifact", "Feast on the Fallen", "Feral Incarnation", "First Response", "Frenzied Goblin", "Furnace Whelp", "Gargoyle Sentinel", "Garruk's Packleader", "Gather Courage", "Geist of the Moors", "Gravedigger", "Heat Ray", "Hot Soup", "Illusory Angel", "Into the Void", "Jace's Ingenuity", "Jorubai Murk Lurker", "Juggernaut", "Kapsho Kitefins", "Kird Chieftain", "Leeching Sliver", "Meteorite", "Might Makes Right", "Military Intelligence", "Necrogen Scudder", "Nightfire Giant", "Nissa's Expedition", "Overwhelm", "Paragon of Eternal Wilds", "Paragon of Fierce Defiance", "Paragon of Gathering Mists", "Paragon of New Dawns", "Paragon of Open Graves", "Profane Memento", "Quickling", "Reclamation Sage", "Restock", "Roaring Primadox", "Rogue's Gloves", "Sacred Armory", "Sengir Vampire", "Seraph of the Masses", "Serra Angel", "Shrapnel Blast", "Stab Wound", "Staff of the Death Magus", "Staff of the Flame Magus", "Staff of the Mind Magus", "Staff of the Sun Magus", "Staff of the Wild Magus", "Stoke the Flames", "Sunblade Elf", "Tormod's Crypt", "Turn to Frog", "Ulcerate", "Venom Sliver", "Wall of Essence", "Wall of Frost", "Wall of Limbs", "Wall of Mulch", "Warden of the Beyond", "Xathrid Slyblade");
		this.addCards(Rarity.RARE, "AEtherspouts", "Aegis Angel", "Aggressive Mining", "Avacyn, Guardian Angel", "Avarice Amulet", "Battlefield Forge", "Burning Anger", "Caves of Koilos", "Chasm Skulker", "Chief Engineer", "Chord of Calling", "Crucible of Fire", "Cruel Sadist", "Genesis Hydra", "Goblin Kaboomist", "Goblin Rabblemaster", "Grindclock", "Haunted Plate Mail", "Hoarding Dragon", "Hornet Nest", "Hornet Queen", "Hushwing Gryff", "In Garruk's Wake", "Indulgent Tormentor", "Jalira, Master Polymorphist", "Kalonian Twingrove", "Kurkesh, Onakke Ancient", "Life's Legacy", "Llanowar Wastes", "Mahamoti Djinn", "Mass Calcify", "Master of Predicaments", "Mercurial Pretender", "Necromancer's Stockpile", "Nightmare", "Ob Nixilis, Unshackled", "Obelisk of Urd", "Phyrexian Revoker", "Phytotitan", "Polymorphist's Jest", "Preeminent Captain", "Resolute Archangel", "Return to the Ranks", "Scuttling Doom Engine", "Shield of the Avatar", "Shivan Dragon", "Shivan Reef", "Siege Dragon", "Sliver Hive", "Spectra Ward", "Spirit Bonds", "Stain the Mind", "Stormtide Leviathan", "Terra Stomper", "Urborg, Tomb of Yawgmoth", "Waste Not", "Yavimaya Coast", "Yisan, the Wanderer Bard");
		this.addCards(Rarity.MYTHIC, "Ajani Steadfast", "Chandra, Pyromaster", "Garruk, Apex Predator", "Jace, the Living Guildpact", "Liliana Vess", "Nissa, Worldwaker", "Perilous Vault", "Sliver Hivelord", "Soul of Innistrad", "Soul of New Phyrexia", "Soul of Ravnica", "Soul of Shandalar", "Soul of Theros", "Soul of Zendikar", "The Chain Veil");
	}
}
