package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Magic 2012")
public final class Magic2012 extends SimpleExpansion
{
	public Magic2012()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "AEther Adept", "Act of Treason", "Amphin Cutthroat", "Angel's Mercy", "Arachnus Web", "Armored Warhorse", "Assault Griffin", "Auramancer", "Aven Fleetwing", "Benalish Veteran", "Blood Ogre", "Blood Seeker", "Bloodrage Vampire", "Bonebreaker Giant", "Bountiful Harvest", "Brindle Boar", "Brink of Disaster", "Cancel", "Chandra's Outrage", "Chasm Drake", "Child of Night", "Coral Merfolk", "Dark Favor", "Demystify", "Devouring Swarm", "Disentomb", "Distress", "Divination", "Divine Favor", "Doom Blade", "Drifting Shade", "Duskhunter Bat", "Fiery Hellhound", "Firebreathing", "Flight", "Fling", "Fog", "Frost Breath", "Garruk's Companion", "Giant Spider", "Gideon's Lawkeeper", "Gladecover Scout", "Goblin Arsonist", "Goblin Fireslinger", "Goblin Piker", "Goblin Tunneler", "Goblin War Paint", "Gorehorn Minotaurs", "Gravedigger", "Greater Basilisk", "Griffin Rider", "Griffin Sentinel", "Guardians' Pledge", "Harbor Serpent", "Hideous Visage", "Ice Cage", "Incinerate", "Jace's Erasure", "Lava Axe", "Lifelink", "Lightning Elemental", "Llanowar Elves", "Lurking Crocodile", "Mana Leak", "Manalith", "Manic Vandal", "Merfolk Looter", "Merfolk Mesmerist", "Mighty Leap", "Mind Rot", "Naturalize", "Negate", "Pacifism", "Peregrine Griffin", "Phantasmal Bear", "Plummet", "Ponder", "Pride Guardian", "Rampant Growth", "Reclaim", "Runeclaw Bear", "Sacred Wolf", "Shock", "Siege Mastodon", "Skywinder Drake", "Slaughter Cry", "Sorin's Thirst", "Stampeding Rhino", "Stave Off", "Stonehorn Dignitary", "Stormfront Pegasus", "Taste of Blood", "Titanic Growth", "Tormented Soul", "Trollhide", "Unsummon", "Vastwood Gorger", "Wall of Torches", "Warpath Ghoul", "Wring Flesh", "Zombie Goliath");
		this.addCards(Rarity.UNCOMMON, "Acidic Slime", "Alabaster Mage", "Alluring Siren", "Angel's Feather", "Arbalest Elite", "Autumn's Veil", "Azure Mage", "Belltower Sphinx", "Buried Ruin", "Carnage Wurm", "Celestial Purge", "Circle of Flame", "Combust", "Consume Spirit", "Crimson Mage", "Crown of Empires", "Crumbling Colossus", "Cudgel Troll", "Deathmark", "Demon's Horn", "Diabolic Tutor", "Dragon's Claw", "Elite Vanguard", "Elixir of Immortality", "Fireball", "Flashfreeze", "Goblin Bangchuckers", "Goblin Grenade", "Greatsword", "Hunter's Insight", "Jade Mage", "Kite Shield", "Kraken's Eye", "Levitation", "Lure", "Master Thief", "Mind Control", "Oblivion Ring", "Onyx Mage", "Overrun", "Phantasmal Dragon", "Reassembling Skeleton", "Roc Egg", "Rusted Sentinel", "Scepter of Empires", "Sengir Vampire", "Serra Angel", "Smallpox", "Spirit Mantle", "Stingerfling Spider", "Stormblood Berserker", "Swiftfoot Boots", "Tectonic Rift", "Thran Golem", "Timely Reinforcements", "Turn to Frog", "Vampire Outcasts", "Volcanic Dragon", "Wurm's Tooth", "Zombie Infestation");
		this.addCards(Rarity.RARE, "Adaptive Automaton", "Aegis Angel", "Arachnus Spinner", "Archon of Justice", "Birds of Paradise", "Call to the Grave", "Cemetery Reaper", "Chandra's Phoenix", "Day of Judgment", "Djinn of Wishes", "Doubling Chant", "Dragonskull Summit", "Drowned Catacomb", "Druidic Satchel", "Dungrove Elder", "Elvish Archdruid", "Flameblast Dragon", "Garruk's Horde", "Gideon's Avenger", "Glacial Fortress", "Goblin Chieftain", "Grand Abolisher", "Grim Lavamancer", "Honor of the Pure", "Jace's Archivist", "Lord of the Unreal", "Manabarbs", "Mesa Enchantress", "Mind Unbound", "Monomania", "Pentavus", "Personal Sanctuary", "Phantasmal Image", "Quicksilver Amulet", "Redirect", "Reverberate", "Rites of Flourishing", "Rootbound Crag", "Royal Assassin", "Rune-Scarred Demon", "Scrambleverse", "Skinshifter", "Solemn Simulacrum", "Sorin's Vengeance", "Sphinx of Uthuun", "Sundial of the Infinite", "Sunpetal Grove", "Sutured Ghoul", "Throne of Empires", "Vengeful Pharaoh", "Visions of Beyond", "Warstorm Surge", "Worldslayer");
		this.addCards(Rarity.MYTHIC, "Angelic Destiny", "Bloodlord of Vaasgoth", "Chandra, the Firebrand", "Frost Titan", "Furyborn Hellkite", "Garruk, Primal Hunter", "Gideon Jura", "Grave Titan", "Inferno Titan", "Jace, Memory Adept", "Primeval Titan", "Primordial Hydra", "Sorin Markov", "Sun Titan", "Time Reversal");
	}
}
