package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Magic 2014 Core Set")
public final class Magic2014CoreSet extends SimpleExpansion
{
	public Magic2014CoreSet()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Academy Raider", "Accursed Spirit", "Act of Treason", "Advocate of the Beast", "Altar's Reap", "Angelic Wall", "Archaeomancer", "Armored Cancrix", "Auramancer", "Blood Bairn", "Blur Sliver", "Brindle Boar", "Cancel", "Canyon Minotaur", "Capashen Knight", "Celestial Flare", "Chandra's Outrage", "Charging Griffin", "Child of Night", "Claustrophobia", "Coral Merfolk", "Corpse Hauler", "Cyclops Tyrant", "Dark Favor", "Dawnstrike Paladin", "Deadly Recluse", "Deathgaze Cockatrice", "Demolish", "Disperse", "Divination", "Divine Favor", "Dragon Hatchling", "Duress", "Elvish Mystic", "Essence Scatter", "Festering Newt", "Fog", "Fortify", "Frost Breath", "Giant Growth", "Giant Spider", "Gladecover Scout", "Goblin Shortcutter", "Griffin Sentinel", "Groundshaker Sliver", "Hive Stirrings", "Hunt the Weak", "Lava Axe", "Lay of the Land", "Lightning Talons", "Liturgy of Blood", "Marauding Maulhorn", "Mark of the Vampire", "Master of Diversion", "Merfolk Spy", "Messenger Drake", "Mind Rot", "Minotaur Abomination", "Naturalize", "Negate", "Nephalia Seakite", "Nightwing Shade", "Pacifism", "Pay No Heed", "Pillarfield Ox", "Pitchburn Devils", "Plummet", "Predatory Sliver", "Quag Sickness", "Ranger's Guile", "Regathan Firecat", "Rootwalla", "Rumbling Baloth", "Scroll Thief", "Seacoast Drake", "Seismic Stomp", "Sensory Deprivation", "Sentinel Sliver", "Shadowborn Apostle", "Shock", "Show of Valor", "Shrivel", "Siege Mastodon", "Sliver Construct", "Smelt", "Solemn Offering", "Soulmender", "Sporemound", "Striking Sliver", "Suntail Hawk", "Thunder Strike", "Time Ebb", "Tome Scour", "Trained Condor", "Trollhide", "Undead Minotaur", "Verdant Haven", "Vile Rebirth", "Wild Guess", "Wring Flesh", "Zephyr Charge");
		this.addCards(Rarity.UNCOMMON, "Accorder's Shield", "Air Servant", "Angelic Accord", "Artificer's Hex", "Banisher Priest", "Barrage of Expendables", "Battle Sliver", "Blessing", "Blightcaster", "Bramblecrush", "Brave the Elements", "Briarpack Alpha", "Bubbling Cauldron", "Congregate", "Corrupt", "Darksteel Ingot", "Diabolic Tutor", "Doom Blade", "Dragon Egg", "Elixir of Immortality", "Encroaching Wastes", "Enlarge", "Fireshrieker", "Flames of the Firebrand", "Fleshpulper Giant", "Glimpse the Future", "Gnawing Zombie", "Howl of the Night Pack", "Illusionary Armor", "Kalonian Tusker", "Manaweft Sliver", "Millstone", "Molten Birth", "Opportunity", "Phantom Warrior", "Rod of Ruin", "Sengir Vampire", "Serra Angel", "Shimmering Grotto", "Shiv's Embrace", "Spell Blast", "Staff of the Death Magus", "Staff of the Flame Magus", "Staff of the Mind Magus", "Staff of the Sun Magus", "Staff of the Wild Magus", "Steelform Sliver", "Stonehorn Chanter", "Tenacious Dead", "Vampire Warlord", "Vial of Poison", "Volcanic Geyser", "Voracious Wurm", "Wall of Frost", "Wall of Swords", "Warden of Evos Isle", "Water Servant", "Windstorm", "Woodborn Behemoth", "Young Pyromancer");
		this.addCards(Rarity.RARE, "Ajani's Chosen", "Awaken the Ancient", "Bogbrew Witch", "Bonescythe Sliver", "Burning Earth", "Chandra's Phoenix", "Clone", "Colossal Whale", "Dark Prophecy", "Dismiss into Dream", "Domestication", "Door of Destinies", "Elite Arcanist", "Fiendslayer Paladin", "Galerider Sliver", "Garruk's Horde", "Goblin Diplomats", "Grim Return", "Guardian of the Ages", "Haunted Plate Mail", "Imposing Sovereign", "Indestructibility", "Into the Wilds", "Jace's Mindseeker", "Lifebane Zombie", "Liliana's Reaver", "Megantic Sliver", "Mindsparker", "Mutavault", "Nightmare", "Oath of the Ancient Wood", "Ogre Battledriver", "Path of Bravery", "Planar Cleansing", "Pyromancer's Gauntlet", "Quicken", "Ratchet Bomb", "Sanguine Bond", "Savage Summoning", "Scavenging Ooze", "Seraph of the Sword", "Shivan Dragon", "Silence", "Strionic Resonator", "Syphon Sliver", "Thorncaster Sliver", "Tidebinder Mage", "Trading Post", "Traumatize", "Vastwood Hydra", "Wild Ricochet", "Witchstalker", "Xathrid Necromancer");
		this.addCards(Rarity.MYTHIC, "Ajani, Caller of the Pride", "Archangel of Thune", "Chandra, Pyromaster", "Darksteel Forge", "Devout Invocation", "Garruk, Caller of Beasts", "Jace, Memory Adept", "Kalonian Hydra", "Liliana of the Dark Realms", "Primeval Bounty", "Ring of Three Wishes", "Rise of the Dark Realms", "Scourge of Valkas", "Shadowborn Demon", "Windreader Sphinx");
	}
}
