package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Magic: The Gathering—Conspiracy")
public final class MagicTheGatheringConspiracy extends SimpleExpansion
{
	public MagicTheGatheringConspiracy()
	{
		super();

		this.addCards(Rarity.COMMON, "AEther Tradewinds", "Ajani's Sunstriker", "Altar's Reap", "Apex Hawks", "Assassinate", "Brago's Favor", "Brago's Representative", "Brainstorm", "Brimstone Volley", "Charging Rhino", "Chartooth Cougar", "Cinder Wall", "Cogwork Librarian", "Cogwork Spy", "Compulsive Research", "Copperhorn Scout", "Courier Hawk", "Crookclaw Transmuter", "Custodi Squire", "Doomed Traveler", "Dream Fracture", "Echoing Courage", "Elvish Aberration", "Enclave Elite", "Enraged Revolutionary", "Flowstone Blade", "Gnarlid Pack", "Grenzo's Cutthroat", "Grixis Illusionist", "Grudge Keeper", "Guardian Zendikon", "Howling Wolf", "Hunger of the Howlpack", "Immediate Action", "Infectious Horror", "Kor Chant", "Liliana's Specter", "Lizard Warrior", "Lurking Automaton", "Mana Geyser", "Marchesa's Emissary", "Minamo Scrollkeeper", "Moment of Heroism", "Muzzio's Preparations", "Nature's Claim", "Necromantic Thirst", "Noble Templar", "Orcish Cannonade", "Pillarfield Ox", "Pitchburn Devils", "Plated Seastrider", "Plummet", "Power of Fire", "Pride Guardian", "Provoke", "Quag Vampires", "Reckless Scholar", "Respite", "Rousing of Souls", "Sakura-Tribe Elder", "Scaled Wurm", "Screaming Seahawk", "Secrets of Paradise", "Selvala's Enforcer", "Sentinel Dispatch", "Shoreline Ranger", "Silverchase Fox", "Skitter of Lizards", "Sporecap Spider", "Stasis Cell", "Stave Off", "Stronghold Discipline", "Syphon Soul", "Torch Fiend", "Tragic Slip", "Traveler's Cloak", "Trumpet Blast", "Turn the Tide", "Twisted Abomination", "Typhoid Rats", "Tyrant's Choice", "Unhallowed Pact", "Valor Made Real", "Vent Sentinel", "Wakedancer", "Whispergear Sneak", "Wrap in Flames", "Wrap in Vigor", "Zombie Goliath");
		this.addCards(Rarity.UNCOMMON, "Advantageous Proclamation", "Agent of Acquisitions", "Air Servant", "Barbed Shocker", "Bite of the Black Rose", "Boldwyr Intimidator", "Breakthrough", "Cogwork Tracker", "Council Guardian", "Deathforge Shaman", "Deathreap Ritual", "Double Stroke", "Elephant Guide", "Explorer's Scope", "Extract from Darkness", "Fact or Fiction", "Favorable Winds", "Fires of Yavimaya", "Fireshrieker", "Flamewright", "Flaring Flame-Kin", "Galvanic Juggernaut", "Gamekeeper", "Glimmerpoint Stag", "Heckling Fiends", "Intangible Virtue", "Iterative Analysis", "Jetting Glasskite", "Lead the Stampede", "Marchesa's Infiltrator", "Marchesa's Smuggler", "Mirrodin's Core", "Morkrut Banshee", "Mortify", "Peace Strider", "Pelakka Wurm", "Plagued Rusalka", "Power Play", "Predator's Howl", "Quicksand", "Reckless Spite", "Reito Lantern", "Relic Crush", "Runed Servitor", "Secret Summoning", "Selvala's Charge", "Skeletal Scrying", "Sky Spirit", "Smallpox", "Soulcatcher", "Spectral Searchlight", "Split Decision", "Spontaneous Combustion", "Squirrel Nest", "Swords to Plowshares", "Treasonous Ogre", "Uncontrollable Anger", "Unexpected Potential", "Unquestioned Authority", "Vampire Hexmage", "Victimize", "Volcanic Fallout", "Vow of Duty", "Wakestone Gargoyle", "Warmonger's Chariot", "Wind Dancer", "Wood Sage", "Woodvine Elemental");
		this.addCards(Rarity.RARE, "AEther Searcher", "Academy Elite", "Altar of Dementia", "Backup Plan", "Basandra, Battle Seraph", "Brago, King Eternal", "Canal Dredger", "Cogwork Grinder", "Council's Judgment", "Custodi Soulbinders", "Dack's Duplicate", "Deal Broker", "Deathrender", "Decimate", "Dimir Doppelganger", "Drakestown Forgotten", "Edric, Spymaster of Trest", "Exploration", "Grenzo's Rebuttal", "Grenzo, Dungeon Warden", "Heartless Hidetsugu", "Ignition Team", "Ill-Gotten Gains", "Lore Seeker", "Magister of Worth", "Magus of the Mirror", "Misdirection", "Paliano, the High City", "Plea for Power", "Realm Seekers", "Reflecting Pool", "Reign of the Pit", "Reya Dawnbringer", "Rout", "Selvala, Explorer Returned", "Silent Arbiter", "Spiritmonger", "Stifle", "Sulfuric Vortex", "Terastodon", "Vedalken Orrery", "Wolfbriar Elemental", "Worldknit");
		this.addCards(Rarity.MYTHIC, "Coercive Portal", "Dack Fayden", "Hydra Omnivore", "Marchesa, the Black Rose", "Mirari's Wake", "Muzzio, Visionary Architect", "Pernicious Deed", "Phage the Untouchable", "Pristine Angel", "Scourge of the Throne");
	}
}
