package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Magic: The Gathering-Commander")
public final class MagicTheGatheringCommander extends SimpleExpansion
{
	public MagicTheGatheringCommander()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "AEthersnipe", "Aquastrand Spider", "Armillary Sphere", "Azorius Chancery", "Barren Moor", "Bojuka Bog", "Boros Garrison", "Boros Signet", "Brainstorm", "Chartooth Cougar", "Colossal Might", "Command Tower", "Congregate", "Cultivate", "Darksteel Ingot", "Deadly Recluse", "Desecrator Hag", "Dimir Aqueduct", "Dimir Signet", "Doom Blade", "Evincar's Justice", "Evolving Wilds", "Faultgrinder", "Fertilid", "Fierce Empath", "Fists of Ironwood", "Footbottom Feast", "Forgotten Cave", "Golgari Rot Farm", "Golgari Signet", "Gravedigger", "Gruul Signet", "Gruul Turf", "Hull Breach", "Invigorate", "Izzet Boilerworks", "Izzet Chronarch", "Izzet Signet", "Journey to Nowhere", "Kodama's Reach", "Krosan Tusker", "Lash Out", "Lonely Sandbar", "Monk Realist", "Mulldrifter", "Murmurs from Beyond", "Oblivion Ring", "Orim's Thunder", "Orzhov Basilica", "Orzhov Signet", "Penumbra Spider", "Prophetic Prism", "Rakdos Carnarium", "Rakdos Signet", "Ray of Command", "Relic Crush", "Repulse", "Rupture Spire", "Sakura-Tribe Elder", "Secluded Steppe", "Selesnya Evangel", "Selesnya Sanctuary", "Selesnya Signet", "Sign in Blood", "Simic Growth Chamber", "Simic Signet", "Slipstream Eel", "Syphon Mind", "Terminate", "Terramorphic Expanse", "Tranquil Thicket", "Unnerve", "Valley Rannet", "Vision Skeins", "Whirlpool Whelm", "Wrecking Ball", "Yavimaya Elder");
		this.addCards(Rarity.UNCOMMON, "Acidic Slime", "Afterlife", "Akoum Refuge", "Anger", "Artisan of Kozilek", "Aura Shards", "Azorius Guildmage", "Baloth Woodcrasher", "Bathe in Light", "Bestial Menace", "Boros Guildmage", "Brawn", "Breath of Darigaaz", "Buried Alive", "Cleansing Beam", "Cobra Trap", "Court Hussar", "Deadwood Treefolk", "Death Mutation", "Death by Dragons", "Diabolic Tutor", "Dragon Whelp", "Dreadship Reef", "Dreamstone Hedron", "Duergar Hedge-Mage", "Electrolyze", "Elvish Aberration", "Eternal Witness", "Explosive Vegetation", "Fact or Fiction", "Fellwar Stone", "Fire // Ice", "Firespout", "Flametongue Kavu", "Fleshbag Marauder", "Fog Bank", "Fungal Reaches", "Furnace Whelp", "Ghostly Prison", "Goblin Cadets", "Golgari Guildmage", "Gomazoa", "Guard Gomazoa", "Gwyllion Hedge-Mage", "Harmonize", "Hunting Pack", "Jotun Grunt", "Jwar Isle Refuge", "Kazandu Refuge", "Lightkeeper of Emeria", "Lightning Greaves", "Molten Slagheap", "Mortify", "Mother of Runes", "Nantuko Husk", "Necrogenesis", "Nemesis Trap", "Nezumi Graverobber", "Nucklavee", "Oni of Wild Places", "Orzhov Guildmage", "Path to Exile", "Perilous Research", "Plumeveil", "Pollen Lullaby", "Prison Term", "Propaganda", "Punishing Fire", "Pyrohemia", "Rapacious One", "Razorjaw Oni", "Return to Dust", "Righteous Cause", "Rise from the Grave", "Savage Twister", "Scattering Stroke", "Selesnya Guildmage", "Serra Angel", "Shattered Angel", "Shriekmaw", "Sigil Captain", "Skullclamp", "Skyscribing", "Sol Ring", "Soul Snare", "Spell Crumple", "Spike Feeder", "Spitebellows", "Spurnmage Advocate", "Squallmonger", "Stitch Together", "Sulfurous Blast", "Svogthos, the Restless Tomb", "Syphon Flesh", "Temple of the False God", "Tribute to the Wild", "Vampire Nighthawk", "Vedalken Plotter", "Vengeful Rebirth", "Veteran Explorer", "Vivid Crag", "Vivid Creek", "Vivid Grove", "Vivid Marsh", "Vivid Meadow", "Vow of Duty", "Vow of Flight", "Vow of Lightning", "Vow of Malice", "Vow of Wildness", "Wall of Denial", "Wall of Omens", "Windfall", "Wonder", "Zoetic Cavern");
		this.addCards(Rarity.RARE, "Acorn Catapult", "Akroma's Vengeance", "Akroma, Angel of Fury", "Alliance of Arms", "Angel of Despair", "Angelic Arbiter", "Arbiter of Knollridge", "Archangel of Strife", "Attrition", "Austere Command", "Avatar of Fury", "Avatar of Slaughter", "Avatar of Woe", "Awakening Zone", "Basandra, Battle Seraph", "Bladewing the Risen", "Brion Stoutarm", "Butcher of Malakir", "Call the Skybreaker", "Celestial Force", "Chain Reaction", "Champion's Helm", "Chaos Warp", "Chorus of the Conclave", "Chromeshell Crab", "Collective Voyage", "Conundrum Sphinx", "Crescendo of War", "Dark Hatchling", "Disaster Radius", "Dominus of Fealty", "Dread Cacodemon", "Dreamborn Muse", "Earthquake", "Edric, Spymaster of Trest", "Extractor Demon", "Fallen Angel", "False Prophet", "Flusterstorm", "Grave Pact", "Hex", "Homeward Path", "Hornet Queen", "Hour of Reckoning", "Howling Mine", "Hydra Omnivore", "Insurrection", "Intet, the Dreamer", "Lhurgoyf", "Living Death", "Magmatic Force", "Magus of the Vineyard", "Mana-Charged Dragon", "Martyr's Bond", "Master Warcraft", "Memory Erosion", "Minds Aglow", "Mortivore", "Nin, the Pain Artist", "Numot, the Devastator", "Oblation", "Oblivion Stone", "Oros, the Avenger", "Patron of the Nezumi", "Prophetic Bolt", "Reins of Power", "Reiver Demon", "Riddlekeeper", "Ruination", "Scavenging Ooze", "Scythe Specter", "Sewer Nemesis", "Shared Trauma", "Simic Sky Swallower", "Skullbriar, the Walking Grave", "Solemn Simulacrum", "Spawnwrithe", "Storm Herd", "Stranglehold", "Symbiotic Wurm", "Szadek, Lord of Secrets", "Teneb, the Harvester", "Trade Secrets", "Trench Gorger", "Triskelavus", "Troll Ascetic", "Vish Kal, Blood Arbiter", "Voice of All", "Vorosh, the Hunter", "Vulturous Zombie", "Wild Ricochet", "Windborn Muse");
		this.addCards(Rarity.MYTHIC, "Animar, Soul of Elements", "Comet Storm", "Damia, Sage of Stone", "Garruk Wildspeaker", "Ghave, Guru of Spores", "Kaalia of the Vast", "Karador, Ghost Chieftain", "Malfegor", "Riku of Two Reflections", "Ruhan of the Fomori", "Tariel, Reckoner of Souls", "The Mimeoplasm", "Wrexial, the Risen Deep", "Zedruu the Greathearted");
	}
}
