package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Magic 2010")
public final class Magic2010 extends SimpleExpansion
{
	public Magic2010()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Acolyte of Xathrid", "Angel's Mercy", "Assassinate", "Berserkers of Blood Ridge", "Blinding Mage", "Borderland Ranger", "Bountiful Harvest", "Bramble Creeper", "Burning Inquiry", "Burst of Speed", "Cancel", "Canyon Minotaur", "Centaur Courser", "Child of Night", "Convincing Mirage", "Coral Merfolk", "Craw Wurm", "Deadly Recluse", "Disentomb", "Disorient", "Divination", "Divine Verdict", "Doom Blade", "Dread Warlock", "Drudge Skeletons", "Duress", "Elvish Visionary", "Emerald Oryx", "Entangling Vines", "Essence Scatter", "Excommunicate", "Fiery Hellhound", "Firebreathing", "Fog", "Giant Growth", "Giant Spider", "Glorious Charge", "Goblin Piker", "Gravedigger", "Griffin Sentinel", "Holy Strength", "Horned Turtle", "Ice Cage", "Illusionary Servant", "Jackal Familiar", "Jump", "Kelinore Bat", "Kindled Fury", "Lava Axe", "Lifelink", "Lightning Bolt", "Lightning Elemental", "Llanowar Elves", "Looming Shade", "Merfolk Looter", "Mind Rot", "Mist Leopard", "Naturalize", "Negate", "Oakenform", "Pacifism", "Palace Guard", "Panic Attack", "Ponder", "Raging Goblin", "Rampant Growth", "Razorfoot Griffin", "Regenerate", "Runeclaw Bear", "Safe Passage", "Sage Owl", "Seismic Strike", "Serpent of the Endless Sea", "Shatter", "Siege Mastodon", "Sign in Blood", "Silvercoat Lion", "Snapping Drake", "Solemn Offering", "Soul Bleed", "Soul Warden", "Sparkmage Apprentice", "Stampeding Rhino", "Stormfront Pegasus", "Tendrils of Corruption", "Terramorphic Expanse", "Tome Scour", "Trumpet Blast", "Unholy Strength", "Unsummon", "Vampire Aristocrat", "Veteran Armorsmith", "Veteran Swordsmith", "Viashino Spearhunter", "Wall of Faith", "Warpath Ghoul", "Weakness", "Wind Drake", "Yawning Fissure", "Zephyr Sprite", "Zombie Goliath");
		this.addCards(Rarity.UNCOMMON, "Acidic Slime", "Act of Treason", "Air Elemental", "Alluring Siren", "Angel's Feather", "Armored Ascension", "Awakener Druid", "Black Knight", "Bog Wraith", "Celestial Purge", "Consume Spirit", "Cudgel Troll", "Deathmark", "Demon's Horn", "Diabolic Tutor", "Dragon Whelp", "Dragon's Claw", "Elite Vanguard", "Enormous Baloth", "Fabricate", "Fireball", "Flashfreeze", "Goblin Artillery", "Gorgon Flail", "Harm's Way", "Howl of the Night Pack", "Howling Banshee", "Ignite Disorder", "Inferno Elemental", "Kraken's Eye", "Levitation", "Megrim", "Mind Control", "Mold Adder", "Nature's Spiral", "Ornithopter", "Overrun", "Phantom Warrior", "Prized Unicorn", "Prodigal Pyromancer", "Pyroclasm", "Relentless Rats", "Rhox Pikemaster", "Righteousness", "Rise from the Grave", "Rod of Ruin", "Serra Angel", "Sleep", "Spellbook", "Stone Giant", "Telepathy", "Tempest of Light", "Undead Slayer", "Wall of Bone", "Wall of Fire", "Wall of Frost", "Whispersilk Cloak", "White Knight", "Windstorm", "Wurm's Tooth");
		this.addCards(Rarity.RARE, "Ant Queen", "Ball Lightning", "Birds of Paradise", "Capricious Efreet", "Captain of the Watch", "Cemetery Reaper", "Clone", "Coat of Arms", "Djinn of Wishes", "Dragonskull Summit", "Drowned Catacomb", "Earthquake", "Elvish Archdruid", "Elvish Piper", "Gargoyle Castle", "Glacial Fortress", "Goblin Chieftain", "Great Sable Stag", "Guardian Seraph", "Haunting Echoes", "Hive Mind", "Honor of the Pure", "Howling Mine", "Hypnotic Specter", "Indestructibility", "Kalonian Behemoth", "Lightwielder Paladin", "Lurking Predators", "Magebane Armor", "Magma Phoenix", "Manabarbs", "Merfolk Sovereign", "Mesa Enchantress", "Might of Oaks", "Mind Shatter", "Mind Spring", "Mirror of Fate", "Nightmare", "Open the Vaults", "Pithing Needle", "Planar Cleansing", "Polymorph", "Rootbound Crag", "Royal Assassin", "Sanguine Bond", "Shivan Dragon", "Siege-Gang Commander", "Silence", "Sunpetal Grove", "Traumatize", "Twincast", "Underworld Dreams", "Warp World");
		this.addCards(Rarity.MYTHIC, "Ajani Goldmane", "Baneslayer Angel", "Bogardan Hellkite", "Chandra Nalaar", "Darksteel Colossus", "Garruk Wildspeaker", "Jace Beleren", "Liliana Vess", "Master of the Wild Hunt", "Platinum Angel", "Protean Hydra", "Sphinx Ambassador", "Time Warp", "Vampire Nocturnus", "Xathrid Demon");
	}
}
