package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Magic 2011")
public final class Magic2011 extends SimpleExpansion
{
	public Magic2011()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "AEther Adept", "Act of Treason", "Ajani's Mantra", "Arc Runner", "Armored Cancrix", "Assassinate", "Assault Griffin", "Augury Owl", "Azure Drake", "Barony Vampire", "Berserkers of Blood Ridge", "Blinding Mage", "Blood Tithe", "Bloodcrazed Goblin", "Bloodthrone Vampire", "Bog Raiders", "Brindle Boar", "Cancel", "Canyon Minotaur", "Chandra's Outrage", "Child of Night", "Cloud Crusader", "Cloud Elemental", "Cultivate", "Demolish", "Diminish", "Disentomb", "Doom Blade", "Dryad's Favor", "Duress", "Excommunicate", "Fiery Hellhound", "Fling", "Fog", "Foresee", "Garruk's Companion", "Giant Growth", "Giant Spider", "Goblin Balloon Brigade", "Goblin Piker", "Goblin Tunneler", "Goldenglow Moth", "Gravedigger", "Greater Basilisk", "Harbor Serpent", "Holy Strength", "Hornet Sting", "Hunters' Feast", "Ice Cage", "Incite", "Infantry Veteran", "Inspired Charge", "Jace's Erasure", "Lava Axe", "Lightning Bolt", "Liliana's Specter", "Llanowar Elves", "Mana Leak", "Manic Vandal", "Maritime Guard", "Merfolk Spy", "Mighty Leap", "Mind Rot", "Naturalize", "Negate", "Nether Horror", "Nightwing Shade", "Pacifism", "Palace Guard", "Phantom Beast", "Plummet", "Preordain", "Primal Cocoon", "Pyretic Ritual", "Quag Sickness", "Rotting Legion", "Runeclaw Bear", "Sacred Wolf", "Safe Passage", "Scroll Thief", "Siege Mastodon", "Sign in Blood", "Silvercoat Lion", "Solemn Offering", "Spined Wurm", "Squadron Hawk", "Stabbing Pain", "Stormfront Pegasus", "Sylvan Ranger", "Terramorphic Expanse", "Thunder Strike", "Tireless Missionaries", "Tome Scour", "Unholy Strength", "Unsummon", "Viscera Seer", "Volcanic Strength", "Vulshok Berserker", "Wall of Vines", "Wild Griffin", "Yavimaya Wurm");
		this.addCards(Rarity.UNCOMMON, "Acidic Slime", "Air Servant", "Ajani's Pridemate", "Alluring Siren", "Angel's Feather", "Armored Ascension", "Autumn's Veil", "Awakener Druid", "Back to Nature", "Black Knight", "Call to Mind", "Celestial Purge", "Chandra's Spitfire", "Combust", "Condemn", "Corrupt", "Crystal Ball", "Cudgel Troll", "Deathmark", "Demon's Horn", "Diabolic Tutor", "Dragon's Claw", "Duskdale Wurm", "Earth Servant", "Elite Vanguard", "Elixir of Immortality", "Ember Hauler", "Fire Servant", "Fireball", "Flashfreeze", "Gargoyle Sentinel", "Garruk's Packleader", "Howling Banshee", "Jace's Ingenuity", "Juggernaut", "Kraken's Eye", "Liliana's Caress", "Mind Control", "Nature's Spiral", "Ornithopter", "Prized Unicorn", "Prodigal Pyromancer", "Pyroclasm", "Reassembling Skeleton", "Relentless Rats", "Rise from the Grave", "Roc Egg", "Serra Angel", "Shiv's Embrace", "Sleep", "Sorcerer's Strongbox", "Stone Golem", "Voltaic Key", "Wall of Frost", "War Priest of Thune", "Warlord's Axe", "Water Servant", "Whispersilk Cloak", "White Knight", "Wurm's Tooth");
		this.addCards(Rarity.RARE, "Ancient Hellkite", "Angelic Arbiter", "Birds of Paradise", "Brittle Effigy", "Captivating Vampire", "Clone", "Conundrum Sphinx", "Cyclops Gladiator", "Dark Tutelage", "Day of Judgment", "Destructive Force", "Dragonskull Summit", "Drowned Catacomb", "Elvish Archdruid", "Fauna Shaman", "Glacial Fortress", "Goblin Chieftain", "Haunting Echoes", "Hoarding Dragon", "Honor of the Pure", "Jinxed Idol", "Knight Exemplar", "Leyline of Anticipation", "Leyline of Punishment", "Leyline of Sanctity", "Leyline of Vitality", "Leyline of the Void", "Magma Phoenix", "Mass Polymorph", "Merfolk Sovereign", "Mitotic Slime", "Mystifying Maze", "Nantuko Shade", "Necrotic Plague", "Obstinate Baloth", "Overwhelming Stampede", "Phylactery Lich", "Protean Hydra", "Redirect", "Reverberate", "Rootbound Crag", "Royal Assassin", "Serra Ascendant", "Silence", "Steel Overseer", "Stormtide Leviathan", "Sunpetal Grove", "Sword of Vengeance", "Temple Bell", "Traumatize", "Triskelion", "Vengeful Archon", "Wild Evocation");
		this.addCards(Rarity.MYTHIC, "Ajani Goldmane", "Baneslayer Angel", "Chandra Nalaar", "Demon of Death's Gate", "Frost Titan", "Gaea's Revenge", "Garruk Wildspeaker", "Grave Titan", "Inferno Titan", "Jace Beleren", "Liliana Vess", "Platinum Angel", "Primeval Titan", "Sun Titan", "Time Reversal");
	}
}
