package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Magic 2013")
public final class Magic2013 extends SimpleExpansion
{
	public Magic2013()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "Ajani's Sunstriker", "Angel's Mercy", "Arbor Elf", "Archaeomancer", "Attended Knight", "Aven Squire", "Battleflight Eagle", "Bladetusk Boar", "Bloodhunter Bat", "Bloodthrone Vampire", "Bond Beetle", "Bountiful Harvest", "Canyon Minotaur", "Captain's Call", "Centaur Courser", "Chandra's Fury", "Craterize", "Crippling Blight", "Dark Favor", "Deadly Recluse", "Disentomb", "Divination", "Divine Favor", "Divine Verdict", "Downpour", "Dragon Hatchling", "Duress", "Duty-Bound Dead", "Elvish Visionary", "Encrust", "Erase", "Essence Drain", "Essence Scatter", "Evolving Wilds", "Faerie Invaders", "Farseek", "Fire Elemental", "Fog", "Giant Scorpion", "Glorious Charge", "Goblin Arsonist", "Goblin Battle Jester", "Griffin Protector", "Guardian Lions", "Guardians of Akrasa", "Harbor Serpent", "Hydrosurge", "Index", "Kindled Fury", "Kraken Hatchling", "Krenko's Command", "Liliana's Shade", "Mark of the Vampire", "Merfolk of the Pearl Trident", "Mind Rot", "Mind Sculpt", "Mogg Flunkies", "Murder", "Naturalize", "Negate", "Pacifism", "Pillarfield Ox", "Plummet", "Prey Upon", "Primal Huntbeast", "Ranger's Path", "Ravenous Rats", "Reckless Brute", "Rummaging Goblin", "Safe Passage", "Scroll Thief", "Searing Spear", "Sentinel Spider", "Serpent's Gift", "Servant of Nefarox", "Show of Valor", "Sign in Blood", "Silvercoat Lion", "Smelt", "Spiked Baloth", "Timberpack Wolf", "Titanic Growth", "Tormented Soul", "Tricks of the Trade", "Trumpet Blast", "Turn to Slag", "Unsummon", "Vastwood Gorger", "Vedalken Entrancer", "Vile Rebirth", "Volcanic Strength", "Walking Corpse", "Wall of Fire", "War Falcon", "Warclamp Mastiff", "Watercourser", "Welkin Tern", "Wild Guess", "Wind Drake", "Yeva's Forcemage", "Zombie Goliath");
		this.addCards(Rarity.UNCOMMON, "Acidic Slime", "Angelic Benediction", "Arctic Aven", "Arms Dealer", "Augur of Bolas", "Blood Reckoning", "Chronomaton", "Cleaver Riot", "Clock of Omens", "Courtly Provocateur", "Cower in Fear", "Crimson Muckwader", "Crusader of Odric", "Duskdale Wurm", "Duskmantle Prowler", "Elixir of Immortality", "Flames of the Firebrand", "Flinthoof Boar", "Fog Bank", "Fungal Sprouting", "Furnace Whelp", "Garruk's Packleader", "Gem of Becoming", "Harbor Bandit", "Healer of the Pride", "Jace's Phantasm", "Jayemdae Tome", "Kitesail", "Knight of Glory", "Knight of Infamy", "Mark of Mutiny", "Mindclaw Shaman", "Mwonvuli Beast Tracker", "Oblivion Ring", "Phyrexian Hulk", "Primal Clay", "Prized Elephant", "Public Execution", "Rain of Blades", "Rancor", "Reliquary Tower", "Revive", "Rewind", "Ring of Evos Isle", "Ring of Kalonia", "Ring of Thune", "Ring of Valkas", "Ring of Xathrid", "Rise from the Grave", "Roaring Primadox", "Serra Angel", "Sleep", "Switcheroo", "Talrand's Invocation", "Torch Fiend", "Tormod's Crypt", "Vampire Nighthawk", "Veilborn Ghoul", "Volcanic Geyser", "War Priest of Thune");
		this.addCards(Rarity.RARE, "Battle of Wits", "Boundless Realms", "Captain of the Watch", "Cathedral of War", "Clone", "Diabolic Revelation", "Disciple of Bolas", "Door to Nothingness", "Dragonskull Summit", "Drowned Catacomb", "Elvish Archdruid", "Faith's Reward", "Fervor", "Firewing Phoenix", "Gilded Lotus", "Glacial Fortress", "Ground Seal", "Hamletback Goliath", "Hellion Crucible", "Intrepid Hero", "Krenko, Mob Boss", "Magmaquake", "Master of the Pearl Trident", "Mutilate", "Nefarox, Overlord of Grixis", "Odric, Master Tactician", "Phylactery Lich", "Planar Cleansing", "Predatory Rampage", "Quirion Dryad", "Redirect", "Reverberate", "Rhox Faithmender", "Rootbound Crag", "Sands of Delirium", "Serra Avenger", "Shimian Specter", "Silklash Spider", "Slumbering Dragon", "Spelltwine", "Sphinx of Uthuun", "Staff of Nin", "Stormtide Leviathan", "Stuffy Doll", "Sunpetal Grove", "Talrand, Sky Summoner", "Thragtusk", "Touch of the Eternal", "Trading Post", "Void Stalker", "Wit's End", "Xathrid Gorgon", "Yeva, Nature's Herald");
		this.addCards(Rarity.MYTHIC, "Ajani, Caller of the Pride", "Akroma's Memorial", "Chandra, the Firebrand", "Elderscale Wurm", "Garruk, Primal Hunter", "Jace, Memory Adept", "Liliana of the Dark Realms", "Nicol Bolas, Planeswalker", "Omniscience", "Primordial Hydra", "Serra Avatar", "Sublime Archangel", "Thundermaw Hellkite", "Vampire Nocturnus", "Worldfire");
	}
}
