package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Masters Edition IV")
public final class MastersEditionIV extends SimpleExpansion
{
	public MastersEditionIV()
	{
		super();

		this.addCards(Rarity.LAND, "Urza's Mine", "Urza's Power Plant", "Urza's Tower");
		this.addCards(Rarity.COMMON, "Aesthir Glider", "Alaborn Musketeer", "Alaborn Trooper", "Alluring Scent", "Amulet of Kroog", "Argothian Pixies", "Artifact Blast", "Atog", "Bird Maiden", "Brass Man", "Citanul Druid", "Clockwork Swarm", "Cloud Spirit", "Counterspell", "Crumble", "Cyclopean Mummy", "Dark Ritual", "Divine Offering", "Dragon Engine", "Drowned", "Ebony Horse", "Ebony Rhino", "Elite Cat Warrior", "False Summoning", "Flying Carpet", "Fog", "Foul Spirit", "Giant Growth", "Giant Tortoise", "Glasses of Urza", "Goblin Bully", "Goblin Cavaliers", "Goblin Caves", "Goblin Firestarter", "Goblin Shrine", "Gorilla War Cry", "Gravebind", "Hasran Ogress", "Healing Salve", "Howl from Beyond", "Ironhoof Ox", "Just Fate", "Lava Flow", "Library of Leng", "Lim-Dûl's Cohort", "Mightstone", "Oasis", "Obsianus Golem", "Ogre Taskmaster", "Onulet", "Osai Vultures", "Owl Familiar", "Phantasmal Forces", "Phantasmal Terrain", "Primal Clay", "Prowling Nightstalker", "Reconstruction", "Righteous Charge", "Rockslide Ambush", "Sandstorm", "Scavenger Folk", "Sea Serpent", "Serra Bestiary", "Sleight of Hand", "Soul Shred", "Southern Elephant", "Spotted Griffin", "Staff of Zegon", "Symbol of Unsummoning", "Tablet of Epityr", "Tawnos's Wand", "Temple Acolyte", "Terror", "Urza's Chalice", "War Mammoth", "Warp Artifact", "Weakness", "Wild Aesthir", "Wild Griffin", "Yotian Soldier");
		this.addCards(Rarity.UNCOMMON, "Air Elemental", "Angelic Voices", "Animate Artifact", "Argivian Blacksmith", "Argothian Treefolk", "Basalt Monolith", "Bee Sting", "Black Knight", "Blaze of Glory", "Blue Elemental Blast", "Book of Rass", "Bronze Horse", "Celestial Sword", "Clay Statue", "Clockwork Avian", "Clockwork Gnomes", "Coral Helm", "Dakmor Plague", "Detonate", "Diabolic Machine", "Dread Wight", "Dust to Dust", "Elephant Graveyard", "Energy Flux", "Fire Imp", "Fireball", "Gaea's Avenger", "Gate to Phyrexia", "Goblin General", "Goblin Warrens", "Grapeshot Catapult", "Horn of Deafening", "Icy Manipulator", "Instill Energy", "Juggernaut", "Junún Efreet", "Kudzu", "Living Wall", "Martyrs of Korlis", "Mystic Decree", "Orcish Mechanics", "Pentagram of the Ages", "Planar Gate", "Primitive Justice", "Prodigal Sorcerer", "Radjan Spirit", "Red Elemental Blast", "Roc of Kher Ridges", "Savannah Lions", "Scarecrow", "Scavenging Ghoul", "Sengir Vampire", "Serra Angel", "Serra Aviary", "Shapeshifter", "Soldevi Golem", "Soldevi Machinist", "Squall", "Swords to Plowshares", "Sylvan Tutor", "Talas Researcher", "Tawnos's Weaponry", "Theft of Dreams", "Two-Headed Giant of Foriys", "Water Elemental", "Weakstone", "Whiptail Wurm", "White Knight", "Wicked Pact", "Wild Ox", "Xenic Poltergeist", "Zombie Master");
		this.addCards(Rarity.RARE, "Acid Rain", "Al-abara's Carpet", "Aladdin", "Alchor's Tomb", "Ali from Cairo", "Armageddon", "Armageddon Clock", "Ashnod's Altar", "Badlands", "Balance", "Bayou", "Bottle of Suleiman", "Braingeyser", "Candelabra of Tawnos", "Champion Lancer", "Channel", "City of Brass", "Cloud Dragon", "Colossus of Sardia", "Control Magic", "Conversion", "Copy Artifact", "Cyclone", "Cyclopean Tomb", "Deathcoil Wurm", "Deathgrip", "Demonic Hordes", "Demonic Tutor", "Devastation", "Drain Power", "Dread Reaper", "Drop of Honey", "Ebon Dragon", "Eye for an Eye", "Fastbond", "Fire Tempest", "Floodwater Dam", "Force of Nature", "Fork", "Gauntlet of Might", "Gloom", "Guardian Beast", "Harsh Justice", "Ice Cauldron", "In the Eye of Chaos", "Island Sanctuary", "Jade Monolith", "Kismet", "Kormus Bell", "Last Chance", "Leeches", "Library of Alexandria", "Lich", "Lifeforce", "Living Lands", "Mahamoti Djinn", "Mana Matrix", "Mana Vault", "Martyr's Cry", "Maze of Ith", "Mijae Djinn", "Minion of Tevesh Szat", "Mishra's Workshop", "Naked Singularity", "Obelisk of Undoing", "Overwhelming Forces", "Personal Incarnation", "Plateau", "Power Artifact", "Rain of Daggers", "Rakalite", "Regrowth", "Ring of Renewal", "Rock Hydra", "Savannah", "Scarwood Bandits", "Scrubland", "Sedge Troll", "Serendib Djinn", "Shivan Dragon", "Sinkhole", "Smoke", "Sol Ring", "Stasis", "Steam Catapult", "Strip Mine", "Taiga", "Tetravus", "Thing from the Deep", "Thunder Dragon", "Time Vault", "Titania's Song", "Transmute Artifact", "Triassic Egg", "Tropical Island", "Tsunami", "Tundra", "Underground Sea", "Urza's Miter", "Veteran Bodyguard", "Vibrating Sphere", "Volcanic Island", "Wheel of Fortune", "Wood Elemental", "Word of Command");
	}
}
