package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Masters Edition II")
public final class MastersEditionII extends SimpleExpansion
{
	public MastersEditionII()
	{
		super();

		this.addCards(Rarity.LAND, "Snow-Covered Forest", "Snow-Covered Island", "Snow-Covered Mountain", "Snow-Covered Plains", "Snow-Covered Swamp");
		this.addCards(Rarity.COMMON, "Adarkar Sentinel", "Aeolipile", "Ambush Party", "Armor Thrull", "Armor of Faith", "Armored Griffin", "Aurochs", "Aysen Bureaucrats", "Balduvian Conjurer", "Barbed Sextant", "Brainstorm", "Brassclaw Orcs", "Brine Shaman", "Carapace", "Cloak of Confusion", "Combat Medic", "Dark Banishing", "Death Spark", "Disenchant", "Drift of the Dead", "Dry Spell", "Elven Lyre", "Elvish Hunter", "Elvish Ranger", "Enervate", "Errantry", "Essence Flare", "Feral Thallid", "Folk of the Pines", "Foul Familiar", "Funeral March", "Gangrenous Zombies", "Giant Growth", "Goblin Ski Patrol", "Icatian Javelineers", "Icatian Phalanx", "Icatian Scout", "Icequake", "Icy Prison", "Incinerate", "Ironclaw Orcs", "Kjeldoran Dead", "Kjeldoran Elite Guard", "Kjeldoran Skycaptain", "Krovikan Fetish", "Krovikan Sorcerer", "Lat-Nam's Legacy", "Leaping Lizard", "Meteor Shower", "Necrite", "Orcish Conscripts", "Orcish Farmer", "Orcish Lumberjack", "Orcish Veteran", "Panic", "Phantasmal Fiend", "Phantasmal Mount", "Portent", "Red Cliffs Armada", "Reinforcements", "Reprisal", "Roterothopter", "Royal Trooper", "Screeching Drake", "Shield Bearer", "Shrink", "Shyft", "Songs of the Damned", "Stonehands", "Thallid", "Thallid Devourer", "Thermokarst", "Tinder Wall", "Varchild's Crusader", "Viscerid Armor", "Wall of Kelp", "Warning", "Whiteout", "Woolly Mammoths", "Zuran Spellcaster");
		this.addCards(Rarity.UNCOMMON, "AEther Storm", "Abbey Gargoyles", "Angel of Light", "Ashen Ghoul", "Aysen Crusader", "Balduvian Dead", "Broken Visage", "Browse", "Burnout", "Clockwork Steed", "Conquer", "Counterspell", "Dance of the Dead", "Demonic Consultation", "Diabolic Vision", "Dwarven Ruins", "Ebon Stronghold", "Elvish Spirit Guide", "Errand of Duty", "Essence Filter", "Farrel's Mantle", "Farrel's Zealot", "Flame Spirit", "Forbidden Lore", "Forgotten Lore", "Fumarole", "Giant Trap Door Spider", "Gorilla Shaman", "Havenwood Battleground", "Ice Floe", "Iceberg", "Inheritance", "Jeweled Amulet", "Johtull Wurm", "Joven's Ferrets", "Juniper Order Advocate", "Karplusan Giant", "Kjeldoran Home Guard", "Knight of Stromgald", "Krovikan Vampire", "Lava Burst", "Lim-Dûl's High Guard", "Mishra's Groundbreaker", "Misinformation", "Narwhal", "Nature's Blessing", "Night Soil", "Orc General", "Orcish Cannoneers", "Orcish Captain", "Order of the White Shield", "Personal Tutor", "Phyrexian Devourer", "Pillage", "Ray of Command", "Retribution", "Ruins of Trokair", "Sacred Boon", "Sea Spirit", "Skull Catapult", "Snow Fortress", "Soldevi Digger", "Soldevi Simulacrum", "Soul Exchange", "Soul Kiss", "Spore Cloud", "Spore Flower", "Stampede", "Stone Spirit", "Storm Elemental", "Svyelunite Temple", "Swords to Plowshares", "Thunder Wall", "Viscerid Drone", "Whirling Catapult", "Wind Spirit", "Wings of Aesthir", "Withering Wisps", "Woolly Spider", "Yavimaya Ancients");
		this.addCards(Rarity.RARE, "An-Zerrin Ruins", "Anarchy", "Angel of Fury", "Ashnod's Cylix", "Badlands", "Balduvian Hydra", "Balduvian Trading Post", "Binding Grasp", "Bounty of the Hunt", "Brimstone Dragon", "Caribou Range", "Deep Spawn", "Despotic Scepter", "Dreams of the Dead", "Dystopia", "Earthlink", "Ebon Praetor", "Elemental Augury", "Elkin Bottle", "Elvish Farmer", "Energy Storm", "Fire Dragon", "Fungal Bloom", "Fyndhorn Pollen", "Glacial Chasm", "Glacial Crevasses", "Grandmother Sengir", "Gustha's Scepter", "Heart of Yavimaya", "Helm of Obedience", "Ihsan's Shade", "Imperial Recruiter", "Imperial Seal", "Infernal Darkness", "Ivory Gargoyle", "Jester's Mask", "Kaysa", "Kjeldoran Outpost", "Krovikan Horror", "Lodestone Bauble", "Lost Order of Jarkeld", "Magus of the Unseen", "Mana Crypt", "Marjhan", "Mesmeric Trance", "Minion of Leshrac", "Mudslide", "Musician", "Nature's Wrath", "Necropotence", "Orcish Squatters", "Order of the Sacred Torch", "Phyrexian Portal", "Pyrokinesis", "Ravages of War", "Righteous Fury", "Ritual of Subdual", "Ritual of the Machine", "Rogue Skycaptain", "Royal Decree", "Savannah", "Scars of the Veteran", "Sea Drake", "Sibilant Spirit", "Skeleton Ship", "Soldevi Excavations", "Storm Spirit", "Stromgald Cabal", "Stunted Growth", "Sustaining Spirit", "Taiga", "Temporal Manipulation", "Thelonite Druid", "Thought Lash", "Time Bomb", "Tundra", "Underground Sea", "Wiitigo", "Winter's Night", "Wolf Pack");
	}
}
