package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Masters Edition III")
public final class MastersEditionIII extends SimpleExpansion
{
	public MastersEditionIII()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "Amrou Kithkin", "Anaba Ancestor", "Anaba Spirit Crafter", "Astrolabe", "Barktooth Warbeard", "Benthic Explorers", "Blood Lust", "Bone Flute", "Boomerang", "Brilliant Plan", "Chain Lightning", "Coal Golem", "Crimson Kobolds", "D'Avenant Archer", "Demonic Torment", "Desperate Charge", "Disenchant", "Elves of Deep Shadow", "Evil Presence", "Fellwar Stone", "Fevered Strength", "Fire Ambush", "Fire Drake", "Fire Sprites", "Force Spike", "Forced Retreat", "Ghostly Visit", "Ghosts of the Damned", "Giant Growth", "Heal", "Heavy Fog", "Hunting Cheetah", "Hurloon Minotaur", "Immolation", "Infuse", "Jedit Ojanen", "Jerrard of the Closed Fist", "Jungle Lion", "Kobold Taskmaster", "Kobolds of Kher Keep", "Labyrinth Minotaur", "Lady Orca", "Lesser Werewolf", "Lightning Blow", "Meng Huo's Horde", "Misfortune's Gain", "Peach Garden Oath", "Raging Minotaur", "Ramirez DePietro", "Remove Soul", "Scryb Sprites", "Shu Cavalry", "Shu Elite Companions", "Shu General", "Shu Soldier-Farmers", "Sir Shandlar of Eberyn", "Sivitri Scarzam", "Slashing Tiger", "Sol Grail", "Spirit Shackle", "Spoils of Victory", "Strategic Planning", "The Lady of the Mountain", "Three Visits", "Tobias Andrion", "Torsten Von Ursus", "Trip Wire", "Wall of Light", "Wei Elite Companions", "Wei Infantry", "Wei Strike Force", "Wu Elite Cavalry", "Wu Longbowman", "Wu Warship", "Young Wei Recruits");
		this.addCards(Rarity.UNCOMMON, "Active Volcano", "Alabaster Potion", "Ashes to Ashes", "Axelrod Gunnarson", "Banshee", "Bartel Runeaxe", "Boris Devilboon", "Borrowing 100,000 Arrows", "Call to Arms", "Carrion Ants", "Cinder Storm", "Corrupt Eunuchs", "Crimson Manticore", "Dance of Many", "Desert Twister", "Didgeridoo", "Disharmony", "Eightfold Maze", "Exorcist", "Faerie Noble", "False Defeat", "Famine", "Flash Flood", "Forked Lightning", "Frost Giant", "Gaea's Touch", "Guan Yu, Sainted Warrior", "Hammerheim", "Hunding Gjornersen", "Ivory Guardians", "Kei Takahashi", "Killer Bees", "Kjeldoran Frostbeast", "Knowledge Vault", "Kobold Drill Sergeant", "Kobold Overlord", "Lady Caleria", "Lady Evangela", "Livonya Silone", "Loyal Retainers", "Lu Meng, Wu General", "Lu Xun, Scholar General", "Marhault Elsdragon", "Nebuchadnezzar", "Pavel Maliki", "Princess Lucrezia", "Ragnar", "Ramses Overdark", "Recall", "Reincarnation", "Reveka, Wizard Savant", "Riding the Dilu Horse", "Riven Turnbull", "Spectral Shield", "Spiny Starfish", "Stangg", "Stolen Grain", "Sun Ce, Young Conquerer", "Sunastian Falconer", "Takklemaggot", "The Wretched", "Tor Wauki", "Tracker", "Tuknir Deathlock", "Urborg", "Wei Night Raiders", "Willow Priestess", "Wormwood Treefolk", "Xiahou Dun, the One-Eyed", "Zhang Fei, Fierce Warrior");
		this.addCards(Rarity.RARE, "Akron Legionnaire", "All Hallow's Eve", "Angus Mackenzie", "Arboria", "Arcades Sabboth", "Arena of the Ancients", "Barl's Cage", "Bayou", "Bazaar of Baghdad", "Black Vise", "Burning of Xinye", "Capture of Jingzhou", "Chromium", "City of Shadows", "Cleanse", "Concordant Crossroads", "Cosmic Horror", "Divine Intervention", "Dong Zhou, the Tyrant", "Firestorm Phoenix", "Freyalise's Winds", "Gabriel Angelfire", "Gauntlets of Chaos", "Grim Tutor", "Guan Yu's 1,000-Li March", "Gwendlyn Di Corci", "Halfdane", "Hazezon Tamar", "Hellfire", "Hua Tuo, Honored Physician", "Illusionary Mask", "Karakas", "Kongming, \"Sleeping Dragon\"", "Land Equilibrium", "Land Tax", "Life Chisel", "Liu Bei, Lord of Shu", "Living Plane", "Lu Bu, Master-at-Arms", "Mana Drain", "Mana Vortex", "Meng Huo, Barbarian King", "Mind Twist", "Nether Void", "Nicol Bolas", "Nova Pentacle", "Old Man of the Sea", "Palladia-Mors", "Plateau", "Rasputin Dreamweaver", "Reset", "Rohgahh of Kher Keep", "Rolling Earthquake", "Rubinia Soulsinger", "Scrubland", "Sorrow's Path", "Storm World", "Sun Quan, Lord of Wu", "Sword of the Ages", "Tetsuo Umezawa", "The Abyss", "The Tabernacle at Pendrell Vale", "Tropical Island", "Vaevictis Asmadi", "Volcanic Island", "Voodoo Doll", "Wandering Mage", "Willow Satyr", "Xira Arien", "Zodiac Dragon");
	}
}
