package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Mercadian Masques")
public final class MercadianMasques extends SimpleExpansion
{
	public MercadianMasques()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Alabaster Wall", "Alley Grifters", "Ancestral Mask", "Balloon Peddler", "Battle Rampart", "Blaster Mage", "Blockade Runner", "Bog Smugglers", "Bog Witch", "Brainstorm", "Buoyancy", "Cateran Brute", "Cateran Persuader", "Cave Sense", "Cavern Crawler", "Ceremonial Guard", "Charm Peddler", "Cho-Manno's Blessing", "Cloud Sprite", "Counterspell", "Crash", "Crossbow Infantry", "Dark Ritual", "Darting Merfolk", "Deadly Insect", "Deepwood Drummer", "Deepwood Ghoul", "Deepwood Wolverine", "Dehydration", "Devout Witness", "Diplomatic Immunity", "Disenchant", "Drake Hatchling", "Ferocity", "Flailing Soldier", "Flaming Sword", "Fresh Volunteers", "Furious Assault", "Gerrard's Irregulars", "Giant Caterpillar", "Gush", "Hickory Woodlot", "Highway Robber", "Hoodwink", "Horned Troll", "Howling Wolf", "Insubordination", "Invigorate", "Inviolability", "Kris Mage", "Kyren Glider", "Kyren Sniper", "Land Grant", "Lightning Hounds", "Lunge", "Maggot Therapy", "Misshapen Fiend", "Misstep", "Moment of Silence", "Muzzle", "Nightwind Glider", "Orim's Cure", "Peat Bog", "Pious Warrior", "Port Inspector", "Ramosian Lieutenant", "Ramosian Rally", "Ramosian Sergeant", "Rampart Crawler", "Remote Farm", "Revered Elder", "Rishadan Airship", "Rishadan Cutpurse", "Rouse", "Rushwood Dryad", "Rushwood Herbalist", "Sacred Prey", "Sandstone Needle", "Saprazzan Outrigger", "Saprazzan Raider", "Saprazzan Skerry", "Sever Soul", "Shock Troops", "Silverglade Elemental", "Sizzle", "Skulking Fugitive", "Snorting Gahr", "Snuff Out", "Soothing Balm", "Soul Channeling", "Specter's Wail", "Spidersilk Armor", "Squall", "Steadfast Guard", "Stinging Barrier", "Stone Rain", "Task Force", "Thermal Glider", "Thunderclap", "Tidal Bore", "Tiger Claws", "Tranquility", "Tremor", "Undertaker", "Vendetta", "Venomous Dragonfly", "Vine Trellis", "Wall of Distortion", "Waterfront Bouncer", "Wild Jhovall");
		this.addCards(Rarity.UNCOMMON, "Afterlife", "Arms Dealer", "Arrest", "Ballista Squad", "Barbed Wire", "Boa Constrictor", "Briar Patch", "Cackling Witch", "Cateran Enforcer", "Cateran Kidnappers", "Cateran Summons", "Caustic Wasps", "Chambered Nautilus", "Chameleon Spirit", "Charmed Griffin", "Cho-Arrim Legate", "Cinder Elemental", "Close Quarters", "Coastal Piracy", "Credit Voucher", "Crenellated Wall", "Customs Depot", "Deathgazer", "Deepwood Legate", "Deepwood Tantiv", "Desert Twister", "Diplomatic Escort", "Energy Flux", "Enslaved Horror", "False Demise", "Flailing Ogre", "Fountain of Cho", "Ghoul's Feast", "Glowing Anemone", "Groundskeeper", "Hammer Mage", "Haunted Crossroads", "Henge Guardian", "Henge of Ramos", "High Seas", "Hired Giant", "Hunted Wumpus", "Ignoble Soldier", "Indentured Djinn", "Intimidation", "Iron Lance", "Jeweled Torque", "Jhovall Rider", "Kyren Legate", "Kyren Negotiations", "Larceny", "Last Breath", "Ley Line", "Lumbering Satyr", "Lure", "Magistrate's Veto", "Mercadia's Downfall", "Mercadian Bazaar", "Molting Harpy", "Moonlit Wake", "Noble Purpose", "Ogre Taskmaster", "Panacea", "Pretender's Claim", "Primeval Shambler", "Puffer Extract", "Putrefaction", "Quagmire Lamprey", "Rain of Tears", "Ramosian Captain", "Ramosian Commander", "Renounce", "Revive", "Righteous Aura", "Righteous Indignation", "Rishadan Footpad", "Robber Fly", "Rock Badger", "Rushwood Grove", "Rushwood Legate", "Saber Ants", "Sailmonger", "Saprazzan Breaker", "Saprazzan Cove", "Saprazzan Legate", "Scandalmonger", "Shoving Match", "Silverglade Pathfinder", "Snake Pit", "Soothsaying", "Squallmonger", "Stamina", "Story Circle", "Strongarm Thug", "Subterranean Hangar", "Sustenance", "Thwart", "Timid Drake", "Tonic Peddler", "Toymaker", "Trap Runner", "Uphill Battle", "Venomous Breath", "Volcanic Wind", "War Cadence", "War Tax", "Warmonger", "Warpath", "Wishmonger", "Word of Blasting");
		this.addCards(Rarity.RARE, "Aerial Caravan", "Armistice", "Assembly Hall", "Bargaining Table", "Battle Squadron", "Bifurcate", "Black Market", "Blood Hound", "Blood Oath", "Brawl", "Bribery", "Caller of the Hunt", "Cateran Overlord", "Cateran Slaver", "Cave-In", "Charisma", "Cho-Arrim Alchemist", "Cho-Arrim Bruiser", "Cho-Manno, Revolutionary", "Clear the Land", "Collective Unconscious", "Common Cause", "Conspiracy", "Cornered Market", "Corrupt Official", "Cowardice", "Crackdown", "Crag Saurian", "Crooked Scales", "Crumbling Sanctuary", "Dawnstrider", "Deepwood Elder", "Delraich", "Distorting Lens", "Dust Bowl", "Embargo", "Erithizon", "Extortion", "Extravagant Spirit", "Eye of Ramos", "Flailing Manticore", "Food Chain", "Forced March", "Foster", "Fountain Watch", "Game Preserve", "General's Regalia", "Heart of Ramos", "High Market", "Honor the Fallen", "Horn of Plenty", "Horn of Ramos", "Instigator", "Ivory Mask", "Jhovall Queen", "Karn's Touch", "Kyren Archive", "Kyren Toy", "Lava Runner", "Liability", "Lithophage", "Magistrate's Scepter", "Megatherium", "Mercadian Atlas", "Mercadian Lift", "Midnight Ritual", "Misdirection", "Monkey Cage", "Natural Affinity", "Nether Spirit", "Notorious Assassin", "Overtaker", "Pangosaur", "Power Matrix", "Pulverize", "Puppet's Verdict", "Ramosian Sky Marshal", "Rappelling Scouts", "Reverent Mantra", "Rishadan Brigand", "Rishadan Pawnshop", "Rishadan Port", "Rushwood Elemental", "Sand Squid", "Saprazzan Bailiff", "Saprazzan Heir", "Security Detail", "Seismic Mage", "Silent Assassin", "Skull of Ramos", "Spiritual Focus", "Spontaneous Generation", "Squee, Goblin Nabob", "Squeeze", "Statecraft", "Tectonic Break", "Territorial Dispute", "Thieves' Auction", "Thrashing Wumpus", "Tidal Kraken", "Tooth of Ramos", "Tower of the Magistrate", "Trade Routes", "Two-Headed Dragon", "Unmask", "Unnatural Hunger", "Vernal Equinox", "Vine Dryad", "Wave of Reckoning", "Worry Beads");
	}
}
