package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Mirage")
public final class Mirage extends SimpleExpansion
{
	public Mirage()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Agility", "Alarum", "Armor of Thorns", "Armorer Guildmage", "Azimaet Drake", "Bay Falcon", "Benevolent Unicorn", "Binding Agony", "Blistering Barrier", "Bone Harvest", "Boomerang", "Breathstealer", "Builder's Bane", "Burning Shield Askari", "Cadaverous Knight", "Chaos Charm", "Choking Sands", "Civic Guildmage", "Cloak of Invisibility", "Crash of Rhinos", "Dark Banishing", "Dark Ritual", "Dazzling Beauty", "Dirtwater Wraith", "Disempower", "Disenchant", "Divine Offering", "Drain Life", "Dream Cache", "Dream Fighter", "Dwarven Nomad", "Ebony Charm", "Ekundu Cyclops", "Ekundu Griffin", "Enfeeblement", "Femeref Healer", "Femeref Knight", "Femeref Scouts", "Feral Shadow", "Fetid Horror", "Firebreathing", "Flare", "Fog", "Giant Mantis", "Gibbering Hyenas", "Goblin Elite Infantry", "Goblin Tinkerer", "Granger Guildmage", "Grave Servitude", "Gravebane Zombie", "Healing Salve", "Incinerate", "Ivory Charm", "Jolrael's Centaur", "Jolt", "Jungle Wurm", "Kaervek's Torch", "Kukemssa Serpent", "Lightning Reflexes", "Memory Lapse", "Merfolk Raiders", "Merfolk Seer", "Mtenda Herder", "Mtenda Lion", "Noble Elephant", "Pacifism", "Power Sink", "Prismatic Circle", "Pyric Salamander", "Quirion Elves", "Raging Spirit", "Rampant Growth", "Ray of Command", "Reality Ripple", "Regeneration", "Restless Dead", "Ritual of Steel", "Sabertooth Cobra", "Sandbar Crocodile", "Sandstorm", "Sapphire Charm", "Sea Scryer", "Searing Spear Askari", "Seedling Charm", "Serene Heart", "Sewer Rats", "Shadow Guildmage", "Shaper Guildmage", "Skulking Ghost", "Soar", "Soulshriek", "Spitting Earth", "Stalking Tiger", "Stone Rain", "Talruum Minotaur", "Teferi's Curse", "Teferi's Drake", "Teremko Griffin", "Thirst", "Tranquil Domain", "Uktabi Faerie", "Urborg Panther", "Viashino Warrior", "Village Elder", "Wall of Corpses", "Wall of Resistance", "Wall of Roots", "Ward of Lights", "Wild Elephant", "Zhalfirin Knight");
		this.addCards(Rarity.UNCOMMON, "Afterlife", "Aleatory", "Bad River", "Barbed Foliage", "Barbed-Back Wurm", "Basalt Golem", "Blighted Shaman", "Blind Fury", "Blinding Light", "Burning Palm Efreet", "Cerulean Wyvern", "Charcoal Diamond", "Chariot of the Sun", "Cinder Cloud", "Consuming Ferocity", "Coral Fighters", "Crimson Roc", "Crypt Cobra", "Crystal Golem", "Crystal Vein", "Decomposition", "Delirium", "Dissipate", "Dread Specter", "Dwarven Miner", "Elixir of Vitality", "Enlightened Tutor", "Ersatz Gnomes", "Ether Well", "Fallow Earth", "Favorable Destiny", "Femeref Archers", "Fire Diamond", "Flame Elemental", "Flood Plain", "Floodgate", "Foratog", "Goblin Scouts", "Goblin Soothsayer", "Grasslands", "Harbor Guardian", "Harmattan Efreet", "Haunting Apparition", "Hazerider Drake", "Horrible Hordes", "Igneous Golem", "Illumination", "Iron Tusk Elephant", "Jungle Troll", "Kaervek's Hex", "Kaervek's Purge", "Karoo Meerkat", "Lead Golem", "Locust Swarm", "Mana Prism", "Mangara's Blessing", "Mangara's Equity", "Marble Diamond", "Meddle", "Melesse Spirit", "Mind Bend", "Mind Harness", "Mire Shade", "Moss Diamond", "Mountain Valley", "Mtenda Griffin", "Mystical Tutor", "Nettletooth Djinn", "Nocturnal Raid", "Painful Memories", "Patagia Golem", "Phyrexian Vault", "Prismatic Boon", "Radiant Essence", "Ravenous Vampire", "Reign of Chaos", "Reign of Terror", "Rocky Tar Pit", "Roots of Life", "Sand Golem", "Savage Twister", "Sealed Fate", "Shadowbane", "Shauku's Minion", "Sirocco", "Sky Diamond", "Soul Rend", "Spatial Binding", "Stupor", "Superior Numbers", "Suq'Ata Firewalker", "Telim'Tor's Darts", "Tidal Wave", "Tropical Storm", "Unerring Sling", "Unseen Walker", "Unyaro Bee Sting", "Unyaro Griffin", "Vaporous Djinn", "Vigilant Martyr", "Vitalizing Cascade", "Volcanic Geyser", "Wave Elemental", "Wildfire Emissary", "Windreaper Falcon", "Withering Boon", "Worldly Tutor", "Zebra Unicorn", "Zhalfirin Commander", "Zombie Mob");
		this.addCards(Rarity.RARE, "Abyssal Hunter", "Acidic Dagger", "Afiya Grove", "Amber Prison", "Amulet of Unmaking", "Ancestral Memories", "Ashen Powder", "Asmira, Holy Avenger", "Auspicious Ancestor", "Barreling Attack", "Bazaar of Wonders", "Benthic Djinn", "Bone Mask", "Brushwagg", "Cadaverous Bloom", "Canopy Dragon", "Carrion", "Catacomb Dragon", "Celestial Dawn", "Chaosphere", "Circle of Despair", "Crimson Hellkite", "Cursed Totem", "Cycle of Life", "Daring Apprentice", "Discordant Spirit", "Divine Retribution", "Early Harvest", "Emberwilde Caliph", "Emberwilde Djinn", "Energy Bolt", "Energy Vortex", "Ethereal Champion", "Final Fortune", "Flash", "Forbidden Crypt", "Forsaken Wastes", "Frenetic Efreet", "Grim Feast", "Grinning Totem", "Hakim, Loreweaver", "Hall of Gemstone", "Hammer of Bogardan", "Harbinger of Night", "Hivis of the Scale", "Illicit Auction", "Infernal Contract", "Jabari's Influence", "Jungle Patrol", "Kukemssa Pirates", "Leering Gargoyle", "Lion's Eye Diamond", "Lure of Prey", "Malignant Growth", "Mangara's Tome", "Maro", "Mindbender Spores", "Misers' Cage", "Mist Dragon", "Natural Balance", "Null Chamber", "Paupers' Cage", "Pearl Dragon", "Phyrexian Dreadnought", "Phyrexian Purge", "Phyrexian Tribute", "Political Trickery", "Polymorph", "Preferred Selection", "Prismatic Lace", "Psychic Transfer", "Purgatory", "Purraj of Urborg", "Rashida Scalebane", "Razor Pendulum", "Reckless Embermage", "Reflect Damage", "Reparations", "Rock Basilisk", "Sacred Mesa", "Sawback Manticore", "Seeds of Innocence", "Shallow Grave", "Shauku, Endbringer", "Shimmer", "Sidar Jabari", "Soul Echo", "Spectral Guardian", "Spirit of the Night", "Subterranean Spirit", "Sunweb", "Tainted Specter", "Taniwha", "Teeka's Dragon", "Teferi's Imp", "Teferi's Isle", "Telim'Tor", "Telim'Tor's Edict", "Tombstone Stairwell", "Torrent of Lava", "Uktabi Wildcats", "Unfulfilled Desires", "Ventifact Bottle", "Volcanic Dragon", "Waiting in the Weeds", "Warping Wurm", "Wellspring", "Yare", "Zirilan of the Claw", "Zuberi, Golden Feather");
	}
}
