package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Mirrodin")
public final class Mirrodin extends SimpleExpansion
{
	public Mirrodin()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "AEther Spellbomb", "Alpha Myr", "Ancient Den", "Annul", "Arrest", "Auriok Transfixer", "Awe Strike", "Battlegrowth", "Blinding Beam", "Bonesplitter", "Chimney Imp", "Chromatic Sphere", "Clockwork Beetle", "Clockwork Condor", "Cloudpost", "Cobalt Golem", "Consume Spirit", "Contaminated Bond", "Copper Myr", "Deconstruct", "Disarm", "Disciple of the Vault", "Dream's Grip", "Dross Prowler", "Dross Scorpion", "Electrostatic Bolt", "Elf Replica", "Fangren Hunter", "Fists of the Anvil", "Frogmite", "Galvanic Key", "Goblin Replica", "Goblin Striker", "Goblin War Wagon", "Gold Myr", "Great Furnace", "Groffskithur", "Hematite Golem", "Incite War", "Inertia Bubble", "Iron Myr", "Irradiate", "Journey of Discovery", "Krark-Clan Grunt", "Krark-Clan Shaman", "Leaden Myr", "Leonin Den-Guard", "Leonin Elder", "Leonin Scimitar", "Lifespark Spellbomb", "Loxodon Mender", "Lumengrid Warden", "Malachite Golem", "Molten Rain", "Moriok Scavenger", "Myr Adapter", "Myr Enforcer", "Necrogen Spellbomb", "Neurok Familiar", "Neurok Hoversail", "Neurok Spy", "Nim Lasher", "Nim Replica", "Nim Shrieker", "Ogre Leadfoot", "Omega Myr", "Override", "Pewter Golem", "Predator's Strike", "Pyrite Spellbomb", "Raise the Alarm", "Razor Barrier", "Regress", "Scale of Chiss-Goria", "Seat of the Synod", "Seething Song", "Shatter", "Silver Myr", "Skyhunter Cub", "Skyhunter Patrol", "Slagwurm Armor", "Soldier Replica", "Somber Hoverguard", "Sphere of Purity", "Spikeshot Goblin", "Steel Wall", "Sunbeam Spellbomb", "Tanglebloom", "Tel-Jilad Archers", "Tel-Jilad Chosen", "Tel-Jilad Exile", "Terror", "Thoughtcast", "Titanium Golem", "Tooth of Chiss-Goria", "Tree of Tales", "Turn to Dust", "Vault of Whispers", "Viridian Joiner", "Viridian Longbow", "Vorrac Battlehorns", "Vulshok Berserker", "Vulshok Gauntlets", "Wail of the Nim", "Wanderguard Sentry", "Welding Jar", "Wizard Replica", "Wrench Mind", "Wurmskin Forger", "Yotian Soldier");
		this.addCards(Rarity.UNCOMMON, "Altar's Light", "Assert Authority", "Atog", "Auriok Bladewarden", "Banshee's Blade", "Barter in Blood", "Betrayal of Flesh", "Blinkmoth Well", "Bloodscent", "Bottle Gnomes", "Brown Ouphe", "Cathodion", "Clockwork Vorrac", "Creeping Mold", "Crystal Shard", "Dead-Iron Sledge", "Detonate", "Domineer", "Dragon Blood", "Duskworker", "Fabricate", "Farsight Mask", "Fireshrieker", "Flayed Nim", "Forge Armor", "Fractured Loyalty", "Goblin Dirigible", "Golem-Skin Gauntlets", "Grab the Reins", "Granite Shard", "Heartwood Shard", "Icy Manipulator", "Isochron Scepter", "Leonin Bladetrap", "Leonin Skyhunter", "Lightning Greaves", "Looming Hoverguard", "Loxodon Warhammer", "Lumengrid Sentinel", "Mask of Memory", "Mindstorm Crown", "Mirror Golem", "Mourner's Shield", "Myr Mindservant", "Myr Prototype", "Myr Retriever", "Needlebug", "Nim Shambler", "Nuisance Engine", "One Dozen Eyes", "Ornithopter", "Pearl Shard", "Power Conduit", "Psychic Membrane", "Relic Bane", "Roar of the Kha", "Rust Elemental", "Rustmouth Ogre", "Rustspore Ram", "Scrabbling Claws", "Serum Tank", "Shrapnel Blast", "Skeleton Shard", "Slith Ascendant", "Slith Bloodletter", "Slith Firewalker", "Slith Predator", "Slith Strider", "Soul Nova", "Stalking Stones", "Sun Droplet", "Sylvan Scrying", "Synod Sanctum", "Taj-Nar Swordsmith", "Talisman of Dominance", "Talisman of Impulse", "Talisman of Indulgence", "Talisman of Progress", "Talisman of Unity", "Tel-Jilad Stylus", "Tempest of Light", "Thirst for Knowledge", "Thought Prison", "Trolls of Tel-Jilad", "Viridian Shaman", "Vulshok Battlegear", "Wall of Blood", "Woebearer");
		this.addCards(Rarity.RARE, "Altar of Shadows", "Arc-Slogger", "Auriok Steelshaper", "Blinkmoth Urn", "Bosh, Iron Golem", "Broodstar", "Chalice of the Void", "Chrome Mox", "Clockwork Dragon", "Confusion in the Ranks", "Copperhoof Vorrac", "Culling Scales", "Damping Matrix", "Dross Harvester", "Duplicant", "Empyrial Plate", "Extraplanar Lens", "Fatespinner", "Fiery Gambit", "Gate to the AEther", "Gilded Lotus", "Glimmervoid", "Glissa Sunseeker", "Goblin Charbelcher", "Grid Monitor", "Grim Reminder", "Hum of the Radix", "Jinxed Choker", "Krark's Thumb", "Leonin Abunas", "Leonin Sun Standard", "Leveler", "Liar's Pendulum", "Lightning Coils", "Living Hive", "Lodestone Myr", "Loxodon Peacekeeper", "Loxodon Punisher", "Lumengrid Augur", "Luminous Angel", "March of the Machines", "Mass Hysteria", "Megatog", "Mesmeric Orb", "Mind's Eye", "Mindslaver", "Molder Slug", "Myr Incubator", "Necrogen Mists", "Nightmare Lash", "Nim Devourer", "Oblivion Stone", "Pentavus", "Plated Slagwurm", "Platinum Angel", "Promise of Power", "Proteus Staff", "Psychogenic Probe", "Quicksilver Elemental", "Quicksilver Fountain", "Reiver Demon", "Rule of Law", "Sculpting Steel", "Scythe of the Wretched", "Second Sunrise", "Shared Fate", "Solar Tide", "Solemn Simulacrum", "Soul Foundry", "Spellweaver Helix", "Spoils of the Vault", "Sword of Kaldra", "Tangleroot", "Temporal Cascade", "Timesifter", "Tooth and Nail", "Tower of Champions", "Tower of Eons", "Tower of Fortunes", "Tower of Murmurs", "Trash for Treasure", "Triskelion", "Troll Ascetic", "Vedalken Archmage", "Vermiculos", "Vulshok Battlemaster", "War Elemental", "Worldslayer");
	}
}
