package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Modern Masters")
public final class ModernMasters extends SimpleExpansion
{
	public ModernMasters()
	{
		super();

		this.addCards(Rarity.COMMON, "AEther Spellbomb", "AEthersnipe", "Absorb Vis", "Amrou Scout", "Amrou Seekers", "Arcbound Stinger", "Arcbound Wanderer", "Arcbound Worker", "Avian Changeling", "Blightspeaker", "Blind-Spot Giant", "Blinding Beam", "Bonesplitter", "Bound in Silence", "Brute Force", "Cenn's Enlistment", "Citanul Woodreaders", "Court Homunculus", "Crush Underfoot", "Dampen Thought", "Death Denied", "Deepcavern Imp", "Dispeller's Capsule", "Drag Down", "Dreamspoiler Witches", "Durkwood Baloth", "Echoing Courage", "Echoing Truth", "Empty the Warrens", "Errant Ephemeron", "Erratic Mutation", "Etherium Sculptor", "Facevaulter", "Faerie Macabre", "Faerie Mechanist", "Festering Goblin", "Fiery Fall", "Frogmite", "Fury Charm", "Giant Dustwasp", "Glacial Ray", "Gleam of Resistance", "Grapeshot", "Greater Mossdog", "Hammerheim Deadeye", "Hana Kami", "Hillcomber Giant", "Imperiosaur", "Ivory Giant", "Kithkin Greatheart", "Kodama's Reach", "Latchkey Faerie", "Lava Spike", "Logic Knot", "Mogg War Marshal", "Moldervine Cloak", "Mothdust Changeling", "Myr Enforcer", "Nantuko Shaman", "Otherworldly Journey", "Pallid Mycoderm", "Peer Through Depths", "Penumbra Spider", "Peppersmoke", "Perilous Research", "Pestermite", "Petals of Insight", "Pyrite Spellbomb", "Rathi Trapper", "Raven's Crime", "Reach Through Mists", "Rift Bolt", "Rift Elemental", "Runed Stalactite", "Saltfield Recluse", "Sanctum Gargoyle", "Search for Tomorrow", "Skyreach Manta", "Spellstutter Sprite", "Sporoloth Ancient", "Stingscourger", "Stinkdrinker Daredevil", "Stinkweed Imp", "Street Wraith", "Sylvan Bounty", "Syphon Life", "Terramorphic Expanse", "Test of Faith", "Thallid", "Thallid Germinator", "Thallid Shell-Dweller", "Thieving Sprite", "Thundering Giant", "Torrent of Stone", "Traumatic Visions", "Vedalken Dismisser", "Veteran Armorer", "Walker of the Grove", "War-Spike Changeling", "Warren Pilferers", "Warren Weirding");
		this.addCards(Rarity.UNCOMMON, "Auntie's Snitch", "Careful Consideration", "Cloudgoat Ranger", "Dakmor Salvage", "Death Rattle", "Desperate Ritual", "Electrolyze", "Epochrasite", "Esperzoa", "Etched Oracle", "Eternal Witness", "Executioner's Capsule", "Feudkiller's Verdict", "Flickerwisp", "Grinning Ignus", "Horobi's Whisper", "Incremental Growth", "Kitchen Finks", "Krosan Grip", "Lightning Helix", "Mad Auntie", "Manamorphose", "Marsh Flitter", "Masked Admirers", "Meadowboon", "Mind Funeral", "Mulldrifter", "Murderous Redcap", "Myr Retriever", "Narcomoeba", "Paradise Mantle", "Pardic Dragon", "Path to Exile", "Phthisis", "Plumeveil", "Reach of Branches", "Relic of Progenitus", "Riftsweeper", "Riftwing Cloudskate", "Sandsower", "Shrapnel Blast", "Spell Snare", "Sporesower Thallid", "Stir the Pride", "Sudden Shock", "Take Possession", "Tar Pitcher", "Terashi's Grasp", "Thirst for Knowledge", "Thundercloud Shaman", "Tidehollow Sculler", "Tribal Flames", "Tromp the Domains", "Trygon Predator", "Vivid Crag", "Vivid Creek", "Vivid Grove", "Vivid Marsh", "Vivid Meadow", "Worm Harvest");
		this.addCards(Rarity.RARE, "AEther Vial", "Academy Ruins", "Adarkar Valkyrie", "Angel's Grace", "Arcbound Ravager", "Auriok Salvagers", "Blinkmoth Nexus", "Blood Moon", "Bridge from Below", "Chalice of the Void", "City of Brass", "Cold-Eyed Selkie", "Countryside Crusher", "Cryptic Command", "Death Cloud", "Demigod of Revenge", "Divinity of Pride", "Doubling Season", "Dragonstorm", "Earwig Squad", "Engineered Explosives", "Ethersworn Canonist", "Extirpate", "Figure of Destiny", "Gifts Ungiven", "Glen Elendra Archmage", "Glimmervoid", "Grand Arbiter Augustin IV", "Greater Gargadon", "Jhoira of the Ghitu", "Kataki, War's Wage", "Kira, Great Glass-Spinner", "Knight of the Reliquary", "Life from the Loam", "Lotus Bloom", "Maelstrom Pulse", "Meloku the Clouded Mirror", "Molten Disaster", "Oona, Queen of the Fae", "Pact of Negation", "Pyromancer's Swath", "Reveillark", "Rude Awakening", "Scion of Oona", "Skeletal Vampire", "Slaughter Pact", "Squee, Goblin Nabob", "Stonehewer Giant", "Summoner's Pact", "Tombstalker", "Tooth and Nail", "Verdeloth the Ancient", "Woodfall Primus");
		this.addCards(Rarity.MYTHIC, "Dark Confidant", "Elspeth, Knight-Errant", "Jugan, the Rising Star", "Keiga, the Tide Star", "Kiki-Jiki, Mirror Breaker", "Kokusho, the Evening Star", "Progenitus", "Ryusei, the Falling Star", "Sarkhan Vol", "Sword of Fire and Ice", "Sword of Light and Shadow", "Tarmogoyf", "Vedalken Shackles", "Vendilion Clique", "Yosei, the Morning Star");
	}
}
