package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Morningtide")
public final class Morningtide extends SimpleExpansion
{
	public Morningtide()
	{
		super();

		this.addCards(Rarity.COMMON, "Ambassador Oak", "Ballyrush Banneret", "Blightsoil Druid", "Bosk Banneret", "Brighthearth Banneret", "Burrenton Bombardier", "Burrenton Shield-Bearers", "Changeling Sentinel", "Coordinated Barrage", "Deglamer", "Dewdrop Spy", "Disperse", "Distant Melody", "Earthbrawn", "Elvish Warrior", "Everbark Shaman", "Fencer Clique", "Fertilid", "Festercreep", "Final-Sting Faerie", "Fire Juggler", "Floodchaser", "Forfend", "Frogtosser Banneret", "Game-Trail Changeling", "Hostile Realm", "Ink Dissolver", "Kindled Fury", "Kithkin Zephyrnaut", "Latchkey Faerie", "Luminescent Rain", "Lunk Errant", "Lys Alana Bowmaster", "Merrow Witsniper", "Moonglove Changeling", "Morsel Theft", "Mosquito Guard", "Mothdust Changeling", "Mudbutton Clanger", "Negate", "Order of the Golden Cricket", "Pack's Disdain", "Prickly Boggart", "Pulling Teeth", "Reins of the Vinesteed", "Roar of the Crowd", "Seething Pathblazer", "Shard Volley", "Shinewend", "Squeaking Pie Grubfellows", "Stingmoggie", "Stonybrook Banneret", "Stonybrook Schoolmaster", "Stream of Unconsciousness", "Sunflare Shaman", "Violet Pall", "War-Spike Changeling", "Weed-Pruner Poplar", "Weight of Conscience", "Winnower Patrol");
		this.addCards(Rarity.UNCOMMON, "Boldwyr Intimidator", "Bramblewood Paragon", "Cenn's Tactician", "Cloak and Dagger", "Daily Regimen", "Diviner's Wand", "Graceful Reprieve", "Heritage Druid", "Hunting Triad", "Inspired Sprite", "Meadowboon", "Nevermaker", "Nightshade Schemers", "Noggin Whack", "Obsidian Battle-Axe", "Offalsnout", "Oona's Blackguard", "Orchard Warden", "Pyroclast Consul", "Rage Forger", "Recross the Paths", "Redeem the Lost", "Release the Ants", "Research the Deep", "Revive the Fallen", "Rivals' Duel", "Sage of Fables", "Sage's Dousing", "Spitebellows", "Stinkdrinker Bandit", "Stomping Slabs", "Swell of Courage", "Thieves' Fortune", "Thornbite Staff", "Veteran's Armaments", "Walker of the Grove", "Wandering Graybeard", "Warren Weirding", "Waterspout Weavers", "Wolf-Skull Shaman");
		this.addCards(Rarity.RARE, "Auntie's Snitch", "Battletide Alchemist", "Bitterblossom", "Boldwyr Heavyweights", "Borderland Behemoth", "Chameleon Colossus", "Countryside Crusher", "Cream of the Crop", "Declaration of Naught", "Door of Destinies", "Earwig Squad", "Fendeep Summoner", "Feudkiller's Verdict", "Gilt-Leaf Archdruid", "Greatbow Doyen", "Grimoire Thief", "Idyllic Tutor", "Indomitable Ancients", "Kinsbaile Borderguard", "Kinsbaile Cavalier", "Knowledge Exploitation", "Leaf-Crowned Elder", "Lightning Crafter", "Maralen of the Mornsong", "Mind Shatter", "Mind Spring", "Murmuring Bosk", "Mutavault", "Notorious Throng", "Preeminent Captain", "Primal Beyond", "Reach of Branches", "Reveillark", "Rhys the Exiled", "Rustic Clachan", "Scapeshift", "Scarblade Elite", "Sensation Gorger", "Shared Animosity", "Sigil Tracer", "Slithermuse", "Stenchskipper", "Stonehewer Giant", "Supreme Exemplar", "Taurean Mauler", "Titan's Revenge", "Unstoppable Ash", "Vendilion Clique", "Vengeful Firebrand", "Weirding Shaman");
	}
}
