package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("New Phyrexia")
public final class NewPhyrexia extends SimpleExpansion
{
	public NewPhyrexia()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Island", "Island", "Mountain", "Mountain", "Plains", "Plains", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Apostle's Blessing", "Artillerize", "Blighted Agent", "Blind Zealot", "Blinding Souleater", "Chained Throatseeker", "Death-Hood Cobra", "Defensive Stance", "Dementia Bat", "Evil Presence", "Flameborn Viron", "Forced Worship", "Furnace Scamp", "Geth's Verdict", "Gitaxian Probe", "Glissa's Scorn", "Glistener Elf", "Gremlin Mine", "Grim Affliction", "Hovermyr", "Immolating Souleater", "Impaler Shrike", "Insatiable Souleater", "Leeching Bite", "Lost Leonin", "Loxodon Convert", "Maul Splicer", "Mortis Dogs", "Mutagenic Growth", "Mycosynth Wellspring", "Numbing Dose", "Ogre Menial", "Parasitic Implant", "Pestilent Souleater", "Phyrexian Hulk", "Pith Driller", "Porcelain Legionnaire", "Pristine Talisman", "Psychic Barrier", "Razor Swine", "Remember the Fallen", "Rotted Hystrix", "Ruthless Invasion", "Scrapyard Salvo", "Sensor Splicer", "Shriek Raptor", "Slash Panther", "Spined Thopter", "Spire Monitor", "Suture Priest", "Thundering Tanadon", "Toxic Nim", "Trespassing Souleater", "Vapor Snag", "Vault Skirge", "Victorious Destruction", "Viridian Betrayers", "Viridian Harvest", "Volt Charge", "War Report");
		this.addCards(Rarity.UNCOMMON, "Act of Aggression", "Alloy Myr", "Argent Mutation", "Arm with AEther", "Auriok Survivors", "Beast Within", "Brutalizer Exarch", "Caress of Phyrexia", "Cathedral Membrane", "Conversion Chamber", "Corrosive Gale", "Corrupted Resolve", "Darksteel Relic", "Deceiver Exarch", "Despise", "Dismember", "Dispatch", "Due Respect", "Enslave", "Entomber Exarch", "Exclusion Ritual", "Fallen Ferromancer", "Geosurge", "Greenhilt Trainee", "Gut Shot", "Ichor Explosion", "Inquisitor Exarch", "Isolation Cell", "Kiln Walker", "Marrow Shards", "Master Splicer", "Mental Misstep", "Mindcrank", "Mindculling", "Mycosynth Fiend", "Necropouncer", "Noxious Revival", "Phyrexia's Core", "Postmortem Lunge", "Priest of Urabrask", "Rage Extractor", "Reaper of Sheoldred", "Shattered Angel", "Shrine of Boundless Growth", "Shrine of Burning Rage", "Shrine of Limitless Power", "Shrine of Loyal Legions", "Shrine of Piercing Vision", "Sickleslicer", "Spinebiter", "Surge Node", "Tezzeret's Gambit", "Tormentor Exarch", "Triumph of the Hordes", "Viral Drake", "Vital Splicer", "Vulshok Refugee", "Whipflare", "Whispering Specter", "Wing Splicer");
		this.addCards(Rarity.RARE, "Birthing Pod", "Blade Splicer", "Bludgeon Brawl", "Caged Sun", "Chancellor of the Annex", "Chancellor of the Dross", "Chancellor of the Forge", "Chancellor of the Spires", "Chancellor of the Tangle", "Fresh Meat", "Glistening Oil", "Hex Parasite", "Invader Parasite", "Jor Kadeen, the Prevailer", "Lashwrithe", "Life's Finale", "Melira, Sylvok Outcast", "Moltensteel Dragon", "Myr Superion", "Norn's Annex", "Omen Machine", "Phyrexian Ingester", "Phyrexian Metamorph", "Phyrexian Swarmlord", "Phyrexian Unlife", "Praetor's Grasp", "Psychic Surgery", "Puresteel Paladin", "Slag Fiend", "Soul Conduit", "Spellskite", "Surgical Extraction", "Torpor Orb", "Unwinding Clock", "Xenograft");
		this.addCards(Rarity.MYTHIC, "Batterskull", "Elesh Norn, Grand Cenobite", "Etched Monstrosity", "Jin-Gitaxias, Core Augur", "Karn Liberated", "Phyrexian Obliterator", "Sheoldred, Whispering One", "Sword of War and Peace", "Urabrask the Hidden", "Vorinclex, Voice of Hunger");
	}
}
