package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Ninth Edition")
public final class NinthEdition extends SimpleExpansion
{
	public NinthEdition()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Anaba Shaman", "Angelic Blessing", "Aven Cloudchaser", "Aven Fisher", "Aven Flock", "Aven Windreader", "Balduvian Barbarians", "Bog Imp", "Boomerang", "Coercion", "Contaminated Bond", "Coral Eel", "Counsel of the Soratami", "Crafty Pathmage", "Craw Wurm", "Crossbow Infantry", "Dark Banishing", "Dehydration", "Demystify", "Eager Cadet", "Elvish Berserker", "Elvish Warrior", "Enfeeblement", "Fear", "Festering Goblin", "Firebreathing", "Fishliver Oil", "Flight", "Flowstone Shambler", "Foot Soldiers", "Foul Imp", "Fugitive Wizard", "Giant Cockroach", "Giant Growth", "Giant Octopus", "Giant Spider", "Glory Seeker", "Goblin Brigand", "Goblin Chariot", "Goblin Mountaineer", "Goblin Piker", "Goblin Raider", "Goblin Sky Raider", "Gravedigger", "Grizzly Bears", "Highway Robber", "Hill Giant", "Hollow Dogs", "Holy Day", "Holy Strength", "Honor Guard", "Horned Turtle", "Index", "Infantry Veteran", "Kavu Climber", "Lava Axe", "Lightning Elemental", "Llanowar Elves", "Looming Shade", "Lumengrid Warden", "Mana Leak", "Master Decoy", "Mending Hands", "Mind Rot", "Natural Spring", "Naturalize", "Norwood Ranger", "Order of the Sacred Bell", "Overgrowth", "Pacifism", "Panic Attack", "Pegasus Charger", "Plague Beetle", "Raging Goblin", "Raise Dead", "Rampant Growth", "Ravenous Rats", "Razortooth Rats", "Reclaim", "Reflexes", "Remove Soul", "Rogue Kavu", "Rootwalla", "Sacred Nectar", "Sage Aven", "Samite Healer", "Sandstone Warrior", "Scaled Wurm", "Scathe Zombies", "Sea Monster", "Sea's Claim", "Seething Song", "Serpent Warrior", "Shatter", "Shock", "Sift", "Skyhunter Prowler", "Sleight of Hand", "Spined Wurm", "Spineless Thug", "Stone Rain", "Storm Crow", "Suntail Hawk", "Time Ebb", "Trained Armodon", "Tree Monkey", "Treetop Bracers", "Unholy Strength", "Venerable Monk", "Veteran Cavalier", "Volcanic Hammer", "Wanderguard Sentry", "Warrior's Honor", "Wind Drake", "Wood Elves", "Zodiac Monkey");
		this.addCards(Rarity.UNCOMMON, "Air Elemental", "Anaconda", "Anarchist", "Angel of Mercy", "Angel's Feather", "Annex", "Azure Drake", "Baleful Stare", "Ballista Squad", "Blackmail", "Blanchwood Armor", "Blaze", "Blessed Orator", "Bog Wraith", "Boiling Seas", "Bottle Gnomes", "Chastise", "Circle of Protection: Black", "Circle of Protection: Red", "Confiscate", "Consume Spirit", "Creeping Mold", "Cruel Edict", "Dancing Scimitar", "Deathgazer", "Demolish", "Demon's Horn", "Diabolic Tutor", "Dragon's Claw", "Dream Prowler", "Drudge Skeletons", "Elvish Bard", "Enormous Baloth", "Enrage", "Execute", "Exhaustion", "Fellwar Stone", "Flame Wave", "Flashfires", "Flowstone Crusher", "Gift of Estates", "Gluttonous Zombie", "Goblin Balloon Brigade", "Groundskeeper", "Guerrilla Tactics", "Horror of Horrors", "Hunted Wumpus", "Icy Manipulator", "Inspirit", "Kami of Old Stone", "King Cheetah", "Kird Ape", "Kraken's Eye", "Leonin Skyhunter", "Levitation", "Ley Druid", "Llanowar Behemoth", "Megrim", "Nantuko Husk", "Needle Storm", "Nekrataal", "Ogre Taskmaster", "Orcish Artillery", "Ornithopter", "Peace of Mind", "Phantom Warrior", "Phyrexian Gargantua", "Phyrexian Hulk", "Puppeteer", "Pyroclasm", "Quicksand", "Regeneration", "Reminisce", "Rewind", "River Bear", "Rod of Ruin", "Rootbreaker Wurm", "Sanctum Guardian", "Seasoned Marshal", "Serra's Blessing", "Slay", "Soul Feast", "Soul Warden", "Spellbook", "Spirit Link", "Stream of Life", "Sudden Impact", "Summer Bloom", "Swarm of Rats", "Tanglebloom", "Telepathy", "Tempest of Light", "Thieving Magpie", "Thought Courier", "Threaten", "Tidings", "Treasure Trove", "Ur-Golem's Eye", "Urza's Mine", "Urza's Power Plant", "Urza's Tower", "Vengeance", "Viashino Sandstalker", "Viridian Shaman", "Vulshok Morningstar", "Web", "Whip Sergeant", "Withering Gaze", "Wurm's Tooth", "Yavimaya Enchantress", "Zealous Inquisitor", "Zombify");
		this.addCards(Rarity.RARE, "Adarkar Wastes", "Aladdin's Ring", "Ancient Silverback", "Archivist", "Battle of Wits", "Battlefield Forge", "Beast of Burden", "Biorhythm", "Blinding Angel", "Blinking Spirit", "Blood Moon", "Bloodfire Colossus", "Booby Trap", "Brushland", "Caves of Koilos", "Clone", "Coat of Arms", "Cowardice", "Daring Apprentice", "Death Pits of Rath", "Defense Grid", "Disrupting Scepter", "Early Harvest", "Elvish Champion", "Elvish Piper", "Emperor Crocodile", "Evacuation", "Final Punishment", "Fleeting Image", "Flowstone Slide", "Force of Nature", "Form of the Dragon", "Furnace of Rath", "Glorious Anthem", "Goblin King", "Grave Pact", "Greater Good", "Hell's Caretaker", "Howling Mine", "Hypnotic Specter", "Imaginary Pet", "Ivory Mask", "Jade Statue", "Jester's Cap", "Karplusan Forest", "Karplusan Yeti", "Llanowar Wastes", "Lord of the Undead", "Loxodon Warhammer", "Magnivore", "Mahamoti Djinn", "Mana Clash", "Marble Titan", "Maro", "Master Healer", "Might of Oaks", "Millstone", "Mind Bend", "Mindslicer", "Mogg Sentry", "Mortivore", "Natural Affinity", "Nightmare", "Oracle's Attendants", "Paladin en-Vec", "Persecute", "Phyrexian Arena", "Plagiarize", "Plague Wind", "Polymorph", "Rathi Dragon", "Relentless Assault", "Reverse Damage", "Righteousness", "Royal Assassin", "Rukh Egg", "Sacred Ground", "Savannah Lions", "Seedborn Muse", "Sengir Vampire", "Serra Angel", "Shard Phoenix", "Shivan Dragon", "Shivan Reef", "Silklash Spider", "Slate of Ancestry", "Storage Matrix", "Story Circle", "Sulfurous Springs", "Teferi's Puzzle Box", "Temporal Adept", "Thran Golem", "Thundermare", "Tidal Kraken", "Trade Routes", "Traumatize", "Underground River", "Underworld Dreams", "Utopia Tree", "Verdant Force", "Verduran Enchantress", "Vizzerdrix", "Weathered Wayfarer", "Weird Harvest", "Wildfire", "Will-o'-the-Wisp", "Worship", "Wrath of God", "Yavimaya Coast", "Yawgmoth Demon", "Zur's Weirding");
	}
}
