package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Odyssey")
public final class Odyssey extends SimpleExpansion
{
	public Odyssey()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "AEther Burst", "Abandoned Outpost", "Aboshan's Desire", "Acceptable Losses", "Afflict", "Anarchist", "Angelic Wall", "Auramancer", "Aven Cloudchaser", "Aven Fisher", "Aven Flock", "Aven Windreader", "Barbarian Lunatic", "Blazing Salvo", "Bog Wreckage", "Cabal Inquisitor", "Careful Study", "Cartographer", "Cease-Fire", "Cephalid Looter", "Cephalid Scout", "Chainflinger", "Chatter of the Squirrel", "Coffin Purge", "Confessor", "Crypt Creeper", "Dedicated Martyr", "Dematerialize", "Demoralize", "Diligent Farmhand", "Dirty Wererat", "Dreamwinder", "Druid Lyrist", "Dusk Imp", "Dwarven Grunt", "Earth Rift", "Elephant Ambush", "Ember Beast", "Embolden", "Escape Artist", "Filthy Cur", "Firebolt", "Flame Burst", "Fledgling Imp", "Frightcrawler", "Ghastly Demise", "Gravedigger", "Halberdier", "Hallowed Healer", "Immobilizing Ink", "Innocent Blood", "Kamahl's Desire", "Kirtar's Desire", "Krosan Archer", "Krosan Avenger", "Last Rites", "Leaf Dancer", "Life Burst", "Mad Dog", "Mind Burst", "Moment's Peace", "Morbid Hunger", "Morgue Theft", "Muscle Burst", "Mystic Visionary", "Mystic Zealot", "Nantuko Disciple", "Overeager Apprentice", "Pardic Firecat", "Pardic Swordsmith", "Patriarch's Desire", "Patrol Hound", "Peek", "Phantom Whelp", "Pilgrim of Justice", "Pilgrim of Virtue", "Primal Frenzy", "Psionic Gift", "Rabid Elephant", "Ravaged Highlands", "Ray of Distortion", "Reckless Charge", "Refresh", "Repel", "Rites of Initiation", "Rites of Refusal", "Rites of Spring", "Sacred Rites", "Scorching Missile", "Scrivener", "Seafloor Debris", "Second Thoughts", "Seton's Desire", "Shelter", "Simplify", "Springing Tiger", "Syncopate", "Thermal Blast", "Thought Nibbler", "Timberland Ruins", "Tireless Tribe", "Touch of Invisibility", "Tremble", "Werebear", "Whispering Shade", "Wild Mongrel", "Woodland Druid", "Words of Wisdom", "Zombie Assassin", "Zombie Cannibal");
		this.addCards(Rarity.UNCOMMON, "Animal Boneyard", "Aura Graft", "Aven Archer", "Aven Smokeweaver", "Balshan Beguiler", "Balshan Griffin", "Bamboozle", "Barbarian Ring", "Bash to Bits", "Battle Strain", "Beast Attack", "Beloved Chaplain", "Blessed Orator", "Buried Alive", "Cabal Pit", "Caustic Tar", "Centaur Garden", "Cephalid Broker", "Cephalid Coliseum", "Chamber of Manipulation", "Childhood Horror", "Concentrate", "Crashing Centaur", "Darkwater Egg", "Decompose", "Deep Reconnaissance", "Deluge", "Demolish", "Diabolic Tutor", "Druid's Call", "Dwarven Recruiter", "Dwarven Strike Force", "Engulfing Flames", "Execute", "Face of Fear", "Famished Ghoul", "Fervent Denial", "Frenetic Ogre", "Gallantry", "Gorilla Titan", "Howling Gale", "Infected Vermin", "Laquatus's Creativity", "Lava Blister", "Limestone Golem", "Liquid Fire", "Lithatog", "Luminous Guardian", "Magma Vein", "Malevolent Awakening", "Metamorphic Wurm", "Millikin", "Minotaur Explorer", "Mossfire Egg", "Mystic Penitent", "Nantuko Elder", "Nimble Mongoose", "Nomad Decoy", "Nomad Stadium", "Overrun", "Painbringer", "Patchwork Gnomes", "Phantatog", "Piper's Melody", "Predict", "Price of Glory", "Psychatog", "Pulsating Illusion", "Puppeteer", "Recoup", "Resilient Wanderer", "Roar of the Wurm", "Rotting Giant", "Sadistic Hypnotist", "Sandstone Deadfall", "Sarcatog", "Screams of the Damned", "Shadowblood Egg", "Shower of Coals", "Skeletal Scrying", "Skull Fracture", "Skycloud Egg", "Skyshooter", "Soulcatcher", "Spark Mage", "Sphere of Duty", "Sphere of Grace", "Sphere of Law", "Sphere of Reason", "Sphere of Truth", "Spiritualize", "Squirrel Nest", "Standstill", "Steam Vines", "Steamclaw", "Still Life", "Sungrass Egg", "Sylvan Might", "Tattoo Ward", "Testament of Faith", "Thaumatog", "Think Tank", "Thought Eater", "Treetop Sentinel", "Twigwalker", "Vivify", "Volcanic Spray", "Whipkeeper", "Zombie Infestation", "Zombify");
		this.addCards(Rarity.RARE, "Aboshan, Cephalid Emperor", "Aegis of Honor", "Amugaba", "Ancestral Tribute", "Ashen Firebeast", "Atogatog", "Aven Shrine", "Balancing Act", "Battle of Wits", "Bearscape", "Bloodcurdler", "Bomb Squad", "Braids, Cabal Minion", "Burning Sands", "Cabal Patriarch", "Cabal Shrine", "Call of the Herd", "Cantivore", "Catalyst Stone", "Cephalid Retainer", "Cephalid Shrine", "Chance Encounter", "Charmed Pendant", "Chlorophant", "Cognivore", "Crystal Quarry", "Cultural Exchange", "Cursed Monstrosity", "Darkwater Catacombs", "Decaying Soil", "Decimate", "Delaying Shield", "Deserted Temple", "Devoted Caretaker", "Divert", "Divine Sacrament", "Dogged Hunter", "Dwarven Shrine", "Earnest Fellowship", "Entomb", "Epicenter", "Extract", "Graceful Antelope", "Gravestorm", "Ground Seal", "Haunting Echoes", "Hint of Insanity", "Holistic Wisdom", "Impulsive Maneuvers", "Iridescent Angel", "Ivy Elemental", "Junk Golem", "Kamahl, Pit Fighter", "Karmic Justice", "Kirtar's Wrath", "Krosan Beast", "Lieutenant Kirtar", "Magnivore", "Master Apothecary", "Mindslicer", "Mine Layer", "Mirari", "Molten Influence", "Mortivore", "Mossfire Valley", "Mudhole", "Mystic Crusader", "Mystic Enforcer", "Nantuko Mentor", "Nantuko Shrine", "Need for Speed", "Nefarious Lich", "New Frontiers", "Nut Collector", "Obstinate Familiar", "Otarian Juggernaut", "Pardic Miner", "Patron Wizard", "Pedantic Learning", "Persuasion", "Petrified Field", "Pianna, Nomad Captain", "Repentant Vampire", "Savage Firecat", "Seize the Day", "Seton, Krosan Protector", "Shadowblood Ridge", "Shadowmage Infiltrator", "Shifty Doppelganger", "Skycloud Expanse", "Spellbane Centaur", "Squirrel Mob", "Stalking Bloodsucker", "Stone-Tongue Basilisk", "Sungrass Prairie", "Tainted Pact", "Tarnished Citadel", "Terravore", "Thought Devourer", "Time Stretch", "Tombfire", "Traumatize", "Traveling Plague", "Unifying Theory", "Upheaval", "Vampiric Dragon", "Verdant Succession", "Volley of Boulders", "Wayward Angel", "Zoologist");
	}
}
