package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Onslaught")
public final class Onslaught extends SimpleExpansion
{
	public Onslaught()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "Accursed Centaur", "Airborne Aid", "Anurid Murkdiver", "Aphetto Dredging", "Ascending Aven", "Backslide", "Barkhide Mauler", "Barren Moor", "Battering Craghorn", "Battlefield Medic", "Birchlore Rangers", "Break Open", "Brightstone Ritual", "Charging Slateback", "Choking Tethers", "Crafty Pathmage", "Crown of Ascension", "Crown of Awe", "Crown of Fury", "Crown of Suspicion", "Crown of Vigor", "Cruel Revival", "Daru Cavalier", "Daru Healer", "Daru Lancer", "Daunting Defender", "Defensive Maneuvers", "Demystify", "Dirge of Dread", "Disciple of Grace", "Disciple of Malice", "Disruptive Pitmage", "Dive Bomber", "Elvish Guidance", "Elvish Pathcutter", "Elvish Pioneer", "Elvish Warrior", "Erratic Explosion", "Fallen Cleric", "Festering Goblin", "Fever Charm", "Foothill Guide", "Forgotten Cave", "Glory Seeker", "Goblin Sky Raider", "Goblin Sledder", "Goblin Taskmaster", "Grassland Crusader", "Gravel Slinger", "Gustcloak Harrier", "Gustcloak Runner", "Haunted Cadaver", "Imagecrafter", "Information Dealer", "Ixidor's Will", "Krosan Tusker", "Lavamancer's Skill", "Lay Waste", "Leery Fogbeast", "Lonely Sandbar", "Mage's Guile", "Misery Charm", "Mistform Dreamer", "Mistform Mask", "Mistform Wall", "Nantuko Husk", "Naturalize", "Nosy Goblin", "Pacifism", "Piety Charm", "Pinpoint Avalanche", "Profane Prayers", "Renewed Faith", "Riptide Biologist", "Sage Aven", "Sandskin", "Screaming Seahawk", "Screeching Buzzard", "Sea's Claim", "Secluded Steppe", "Severed Legion", "Shepherd of Rot", "Shock", "Skirk Commando", "Skirk Prospector", "Slipstream Eel", "Snarling Undorak", "Solar Blast", "Sparksmith", "Spined Basher", "Spitting Gourna", "Spurred Wolverine", "Spy Network", "Swat", "Symbiotic Elf", "Syphon Mind", "Syphon Soul", "Taunting Elf", "Tranquil Thicket", "Treespring Lorian", "Trickery Charm", "Unified Strike", "Vitality Charm", "Wave of Indifference", "Wellwisher", "Wirewood Elf", "Wirewood Herald", "Wirewood Pride", "Wirewood Savage", "Wretched Anurid");
		this.addCards(Rarity.UNCOMMON, "AEther Charge", "Airdrop Condor", "Akroma's Blessing", "Annex", "Aphetto Alchemist", "Aphetto Grifter", "Aphetto Vulture", "Astral Slide", "Aura Extraction", "Avarax", "Aven Fateshaper", "Aven Soulgazer", "Blackmail", "Bloodline Shaman", "Boneknitter", "Broodhatch Nantuko", "Cabal Archon", "Cabal Executioner", "Cabal Slaver", "Catapult Squad", "Centaur Glade", "Chain of Acid", "Chain of Plasma", "Chain of Silence", "Chain of Smog", "Chain of Vapor", "Commando Raid", "Complicate", "Crowd Favorites", "Crude Rampart", "Custody Battle", "Daru Encampment", "Dawning Purist", "Death Pulse", "Discombobulate", "Dispersing Orb", "Doubtless One", "Dwarven Blastminer", "Elven Riders", "Elvish Scrapper", "Embermage Goblin", "Essence Fracture", "Everglove Courier", "Explosive Vegetation", "Fade from Memory", "Feeding Frenzy", "Flamestick Courier", "Fleeting Aven", "Frightshroud Courier", "Ghosthelm Courier", "Gluttonous Zombie", "Goblin Burrows", "Goblin Machinist", "Graxiplon", "Gustcloak Sentinel", "Gustcloak Skirmisher", "Headhunter", "Heedless One", "Improvised Armor", "Infest", "Inspirit", "Invigorating Boon", "Ironfist Crusher", "Kamahl's Summons", "Krosan Groundshaker", "Lightning Rift", "Meddle", "Mistform Mutant", "Mistform Shrieker", "Mistform Stalker", "Nameless One", "Nova Cleric", "Overwhelming Instinct", "Pearlspear Courier", "Primal Boost", "Prowling Pangolin", "Reckless One", "Reminisce", "Righteous Cause", "Riptide Chronologist", "Riptide Shapeshifter", "Rummaging Wizard", "Run Wild", "Searing Flesh", "Seaside Haven", "Serpentine Basilisk", "Shade's Breath", "Shaleskin Bruiser", "Shieldmage Elder", "Skittish Valesk", "Slice and Dice", "Smother", "Snapping Thragg", "Soulless One", "Spitfire Handler", "Starlit Sanctum", "Sunfire Balm", "Symbiotic Beast", "Thoughtbound Primoc", "Thrashing Mudspawn", "Threaten", "Thunder of Hooves", "Towering Baloth", "Tribal Unity", "Venomspout Brackus", "Walking Desecration", "Wall of Mulch", "Whipcorder", "Wirewood Lodge", "Withering Hex");
		this.addCards(Rarity.RARE, "Aggravated Assault", "Akroma's Vengeance", "Ancestor's Prophet", "Animal Magnetism", "Arcanis the Omnipotent", "Artificial Evolution", "Aurification", "Aven Brigadier", "Biorhythm", "Blatant Thievery", "Blistering Firecat", "Bloodstained Mire", "Butcher Orgg", "Callous Oppressor", "Catapult Master", "Circle of Solace", "Clone", "Contested Cliffs", "Convalescent Care", "Cover of Darkness", "Cryptic Gateway", "Death Match", "Doom Cannon", "Doomed Necromancer", "Dragon Roost", "Dream Chisel", "Ebonblade Reaper", "Elvish Vanguard", "Enchantress's Presence", "Endemic Plague", "Entrails Feaster", "Exalted Angel", "False Cure", "Flooded Strand", "Future Sight", "Gangrenous Goliath", "Gigapede", "Glarecaster", "Goblin Piledriver", "Goblin Pyromancer", "Goblin Sharpshooter", "Grand Coliseum", "Grand Melee", "Gratuitous Violence", "Gravespawn Sovereign", "Grinning Demon", "Gustcloak Savior", "Harsh Mercy", "Head Games", "Hystrodon", "Insurrection", "Ixidor, Reality Sculptor", "Jareth, Leonine Titan", "Kaboom!", "Kamahl, Fist of Krosa", "Krosan Colossus", "Mana Echoes", "Menacing Ogre", "Mistform Skyreaver", "Mobilization", "Mythic Proportions", "Oblation", "Oversold Cemetery", "Patriarch's Bidding", "Peer Pressure", "Polluted Delta", "Psychic Trance", "Quicksilver Dragon", "Ravenous Baloth", "Read the Runes", "Riptide Entrancer", "Riptide Laboratory", "Riptide Replicator", "Risky Move", "Rorix Bladewing", "Rotlung Reanimator", "Shared Triumph", "Sigil of the New Dawn", "Silent Specter", "Silklash Spider", "Silvos, Rogue Elemental", "Skirk Fire Marshal", "Slate of Ancestry", "Stag Beetle", "Standardize", "Starstorm", "Steely Resolve", "Strongarm Tactics", "Supreme Inquisitor", "Symbiotic Wurm", "Tempting Wurm", "Tephraderm", "Trade Secrets", "Tribal Golem", "True Believer", "Undead Gladiator", "Unholy Grotto", "Visara the Dreadful", "Voice of the Woods", "Voidmage Prodigy", "Weathered Wayfarer", "Weird Harvest", "Wheel and Deal", "Windswept Heath", "Wooded Foothills", "Words of War", "Words of Waste", "Words of Wilding", "Words of Wind", "Words of Worship");
	}
}
