package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Planar Chaos")
public final class PlanarChaos extends SimpleExpansion
{
	public PlanarChaos()
	{
		super();

		this.addCards(Rarity.COMMON, "Aquamorph Entity", "Aven Riftwatcher", "Battering Sliver", "Blightspeaker", "Bog Serpent", "Brain Gorgers", "Brute Force", "Citanul Woodreaders", "Cradle to Grave", "Dash Hopes", "Dawn Charm", "Dead // Gone", "Deadly Grub", "Dreamscape Artist", "Dust Corona", "Erratic Mutation", "Essence Warden", "Evolution Charm", "Fa'adiyah Seer", "Firefright Mage", "Fury Charm", "Ghost Tactician", "Giant Dustwasp", "Gossamer Phantasm", "Healing Leaves", "Keldon Marauders", "Mana Tithe", "Melancholy", "Merfolk Thaumaturgist", "Midnight Charm", "Mire Boa", "Needlepeak Spider", "Pallid Mycoderm", "Piracy Charm", "Poultice Sliver", "Primal Plasma", "Prodigal Pyromancer", "Rathi Trapper", "Reality Acid", "Reflex Sliver", "Revered Dead", "Ridged Kusite", "Saltfield Recluse", "Seal of Primordium", "Shade of Trokair", "Shaper Parasite", "Simian Spirit Guide", "Sinew Sliver", "Skirk Shaman", "Spitting Sliver", "Stingscourger", "Sunlance", "Synchronous Sliver", "Uktabi Drake", "Utopia Vow", "Vampiric Link", "Veiling Oddity", "Vitaspore Thallid", "Whitemane Lion", "Wistful Thinking");
		this.addCards(Rarity.UNCOMMON, "AEther Membrane", "Ana Battlemage", "Auramancer's Guise", "Big Game Hunter", "Blood Knight", "Calciderm", "Cautery Sliver", "Circle of Affliction", "Darkheart Sliver", "Deadwood Treefolk", "Dismal Failure", "Dormant Sliver", "Dunerider Outlaw", "Enslave", "Frenetic Sliver", "Frozen AEther", "Hammerheim Deadeye", "Harmonize", "Hedge Troll", "Hunting Wilds", "Jodah's Avenger", "Kavu Predator", "Keen Sense", "Kor Dirge", "Lavacore Elemental", "Malach of the Dawn", "Mantle of Leadership", "Muck Drubb", "Mycologist", "Necrotic Sliver", "Ovinize", "Phantasmagorian", "Pongify", "Pouncing Wurm", "Psychotrope Thallid", "Pyrohemia", "Rebuff the Wicked", "Reckless Wurm", "Riftmarked Knight", "Riptide Pilferer", "Rough // Tumble", "Saltblast", "Serra's Boon", "Shivan Meteor", "Shrouded Lore", "Sophic Centaur", "Stonecloaker", "Stormfront Riders", "Sulfur Elemental", "Tidewalker", "Timebender", "Timecrafting", "Treacherous Urge", "Venarian Glimmer", "Waning Wurm");
		this.addCards(Rarity.RARE, "Aeon Chronicler", "Akroma, Angel of Fury", "Benalish Commander", "Body Double", "Boom // Bust", "Braids, Conjurer Adept", "Chronozoa", "Crovax, Ascendant Hero", "Damnation", "Detritivore", "Dichotomancy", "Dust Elemental", "Extirpate", "Fatal Frenzy", "Fungal Behemoth", "Gaea's Anthem", "Groundbreaker", "Heroes Remembered", "Imp's Mischief", "Intet, the Dreamer", "Jedit Ojanen of Efrava", "Life and Limb", "Magus of the Arena", "Magus of the Bazaar", "Magus of the Coffers", "Magus of the Library", "Magus of the Tabernacle", "Mesa Enchantress", "Mirri the Cursed", "Molten Firebird", "Null Profusion", "Numot, the Devastator", "Oros, the Avenger", "Porphyry Nodes", "Radha, Heir to Keld", "Retether", "Roiling Horror", "Serendib Sorcerer", "Serra Sphinx", "Shivan Wumpus", "Spellshift", "Temporal Extortion", "Teneb, the Harvester", "Timbermare", "Torchling", "Urborg, Tomb of Yawgmoth", "Voidstone Gargoyle", "Volcano Hellion", "Vorosh, the Hunter", "Wild Pair");
	}
}
