package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Planechase 2012 Edition")
public final class Planechase2012Edition extends SimpleExpansion
{
	public Planechase2012Edition()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Akoum", "Aretopolis", "Armillary Sphere", "Assassinate", "Astral Arena", "Augury Owl", "Aura Gnarlid", "Auramancer", "Bloodhill Bastion", "Bramble Elemental", "Cadaver Imp", "Cage of Hands", "Cancel", "Chaotic AEther", "Cultivate", "Deny Reality", "Dimir Aqueduct", "Dimir Infiltrator", "Edge of Malacol", "Erratic Explosion", "Fiery Conclusion", "Fiery Fall", "Flayer Husk", "Fling", "Fractured Powerstone", "Furnace Layer", "Gavony", "Glen Elendra", "Grand Ossuary", "Grove of the Dreampods", "Gruul Turf", "Hedron Fields of Agadeem", "Hissing Iguanar", "Hyena Umbra", "Interplanar Tunnel", "Jund", "Kessig", "Khalni Garden", "Kharasha Foothills", "Kilnspire District", "Lair of the Ashen Idol", "Liliana's Specter", "Mistblade Shinobi", "Morphic Tide", "Mount Keralia", "Mudbutton Torchrunner", "Mutual Epiphany", "Nephalia", "Nest Invader", "Ninja of the Deep Hours", "Norn's Dominion", "Nullmage Advocate", "Okiba-Gang Shinobi", "Onakke Catacomb", "Ondu Giant", "Orochi Colony", "Orzhova", "Penumbra Spider", "Planewide Disaster", "Prahv", "Primal Plasma", "Quicksilver Sea", "Quiet Disrepair", "Rancor", "Reality Shaping", "Rupture Spire", "See Beyond", "Selesnya Loft Gardens", "Selesnya Sanctuary", "Shimmering Grotto", "Silhana Ledgewalker", "Skullsnatcher", "Snake Umbra", "Spatial Merging", "Stensia", "Takenuma", "Talon Gates", "Terramorphic Expanse", "The Zephyr Maze", "Thorn-Thrash Viashino", "Time Distortion", "Tormented Soul", "Trail of the Mage-Rings", "Truga Jungle", "Tukatongue Thallid", "Viridian Emissary", "Windriddle Palaces");
		this.addCards(Rarity.UNCOMMON, "Arc Trail", "Armored Griffin", "Auratouched Mage", "Baleful Strix", "Beast Within", "Beetleback Chief", "Bituminous Blast", "Bloodbraid Elf", "Boar Umbra", "Brindle Shoat", "Brutalizer Exarch", "Concentrate", "Dowsing Shaman", "Dreampod Druid", "Enlisted Wurm", "Farsight Mask", "Felidar Umbra", "Fires of Yavimaya", "Fusion Elemental", "Ghostly Prison", "Gluttonous Slime", "Graypelt Refuge", "Guard Gomazoa", "Hellkite Hatchling", "Illusory Angel", "Inkfathom Witch", "Jwar Isle Refuge", "Kathari Remnant", "Kazandu Refuge", "Krosan Verge", "Lumberknot", "Mammoth Umbra", "Mark of Mutiny", "Noggle Ransacker", "Overrun", "Peregrine Drake", "Pollenbright Wings", "Rivals' Duel", "Sai of the Shinobi", "Shardless Agent", "Skarrg, the Rage Pits", "Spirit Mantle", "Tainted Isle", "Thran Golem", "Throat Slitter", "Thunder-Thrash Elder", "Vitu-Ghazi, the City-Tree", "Vivid Creek", "Walker of Secret Ways", "Wall of Blossoms", "Wall of Frost", "Whispersilk Cloak");
		this.addCards(Rarity.RARE, "Awakening Zone", "Celestial Ancient", "Dark Hatchling", "Dragonlair Spider", "Elderwood Scion", "Enigma Sphinx", "Etherium-Horn Sorcerer", "Exotic Orchard", "Glen Elendra Liege", "Hellion Eruption", "Higure, the Still Wind", "Indrik Umbra", "Ink-Eyes, Servant of Oni", "Kor Spiritdancer", "Last Stand", "Mass Mutiny", "Mitotic Slime", "Mycoloth", "Predatory Urge", "Preyseizer Dragon", "Quietus Spike", "Sakashima's Student", "Sigil of the Empty Throne", "Silent-Blade Oni", "Stairs to Infinity", "Sunken Hope", "Three Dreams", "Warstorm Surge", "Whirlpool Warrior");
		this.addCards(Rarity.MYTHIC, "Krond the Dawn-Clad", "Maelstrom Wanderer", "Thromok the Insatiable", "Vela the Night-Clad");
	}
}
