package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Portal")
public final class Portal extends SimpleExpansion
{
	public Portal()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Angelic Blessing", "Armored Pegasus", "Bog Imp", "Bog Raiders", "Border Guard", "Breath of Life", "Burning Cloak", "Cloak of Feathers", "Cloud Pirates", "Coral Eel", "Craven Giant", "Craven Knight", "Dejà Vu", "Devoted Hero", "Elite Cat Warrior", "Elite Cat Warrior", "Elven Cache", "Elvish Ranger", "False Peace", "Feral Shadow", "Fire Snake", "Fleet-Footed Monk", "Foot Soldiers", "Fruition", "Giant Octopus", "Giant Spider", "Goblin Bully", "Gorilla Warrior", "Grizzly Bears", "Hand of Death", "Hand of Death", "Highland Giant", "Hill Giant", "Horned Turtle", "Howling Fury", "Hulking Goblin", "Jungle Lion", "Keen-Eyed Archers", "Knight Errant", "Lava Axe", "Lizard Warrior", "Merfolk of the Pearl Trident", "Mind Knives", "Mind Rot", "Minotaur Warrior", "Mobilize", "Monstrous Growth", "Monstrous Growth", "Muck Rats", "Nature's Lore", "Omen", "Owl Familiar", "Panther Warriors", "Path of Peace", "Python", "Raging Cougar", "Raging Goblin", "Raging Goblin", "Raging Minotaur", "Raise Dead", "Redwood Treefolk", "Regal Unicorn", "Rowan Treefolk", "Sacred Knight", "Sacred Nectar", "Scorching Spear", "Serpent Warrior", "Skeletal Crocodile", "Skeletal Snake", "Snapping Drake", "Sorcerous Sight", "Soul Shred", "Spined Wurm", "Spitting Earth", "Spotted Griffin", "Stalking Tiger", "Steadfastness", "Stone Rain", "Storm Crow", "Symbol of Unsummoning", "Tidal Surge", "Time Ebb", "Touch of Brilliance", "Undying Beast", "Vampiric Touch", "Volcanic Hammer", "Warrior's Charge", "Warrior's Charge", "Willow Dryad", "Wind Drake");
		this.addCards(Rarity.UNCOMMON, "Anaconda", "Anaconda", "Ardent Militia", "Arrogant Vampire", "Assassin's Blade", "Baleful Stare", "Bee Sting", "Blaze", "Blaze", "Bog Wraith", "Boiling Seas", "Bull Hippo", "Charging Bandits", "Charging Paladin", "Cloud Spirit", "Command of Unsummoning", "Deep Wood", "Deep-Sea Serpent", "Defiant Stand", "Desert Drake", "Dry Spell", "Fire Imp", "Flashfires", "Flux", "Gravedigger", "Hulking Cyclops", "Ingenious Thief", "Lava Flow", "Man-o'-War", "Moon Sprite", "Mountain Goat", "Mystic Denial", "Natural Spring", "Nature's Ruin", "Needle Storm", "Noxious Toad", "Personal Tutor", "Plant Elemental", "Rain of Salt", "Rain of Tears", "Renewing Dawn", "Scorching Winds", "Seasoned Marshal", "Starlight", "Starlit Angel", "Theft of Dreams", "Untamed Wilds", "Valorous Charge", "Vampiric Feast", "Venerable Monk", "Vengeance", "Virtue's Ruin", "Wall of Granite", "Wall of Swords", "Whiptail Wurm", "Winter's Grasp", "Withering Gaze");
		this.addCards(Rarity.RARE, "Alabaster Dragon", "Alluring Scent", "Ancestral Memories", "Archangel", "Armageddon", "Balance of Power", "Blessed Reversal", "Blinding Light", "Capricious Sorcerer", "Charging Rhino", "Cloud Dragon", "Cruel Bargain", "Cruel Fate", "Cruel Tutor", "Devastation", "Djinn of the Lamp", "Dread Charge", "Dread Reaper", "Earthquake", "Ebon Dragon", "Endless Cockroaches", "Exhaustion", "Final Strike", "Fire Dragon", "Fire Tempest", "Forked Lightning", "Gift of Estates", "Harsh Justice", "Hurricane", "King's Assassin", "Last Chance", "Mercenary Knight", "Natural Order", "Nature's Cloak", "Phantom Warrior", "Pillaging Horde", "Primeval Force", "Prosperity", "Pyroclasm", "Serpent Assassin", "Spiritual Guardian", "Stern Marshal", "Summer Bloom", "Sylvan Tutor", "Taunt", "Temporary Truce", "Thing from the Deep", "Thundering Wurm", "Thundermare", "Treetop Defense", "Volcanic Dragon", "Wicked Pact", "Winds of Change", "Wood Elves", "Wrath of God");
	}
}
