package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Portal Three Kingdoms")
public final class PortalThreeKingdoms extends SimpleExpansion
{
	public PortalThreeKingdoms()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Barbarian Horde", "Broken Dam", "Burning Fields", "Deception", "Desert Sandstorm", "Extinguish", "False Defeat", "Fire Ambush", "Forced Retreat", "Forest Bear", "Ghostly Visit", "Imperial Edict", "Independent Troops", "Meng Huo's Horde", "Misfortune's Gain", "Mountain Bandit", "Preemptive Strike", "Return to Battle", "Riding Red Hare", "Sage's Knowledge", "Shu Cavalry", "Shu Defender", "Shu Elite Infantry", "Shu Farmer", "Shu Foot Soldiers", "Shu Grain Caravan", "Southern Elephant", "Spring of Eternal Peace", "Stalking Tiger", "Stone Rain", "Straw Soldiers", "Three Visits", "Trained Jackal", "Virtuous Charge", "Volunteer Militia", "Wei Ambush Force", "Wei Infantry", "Wei Scout", "Wei Strike Force", "Wielding the Green Dragon", "Wu Elite Cavalry", "Wu Infantry", "Wu Light Cavalry", "Wu Scout", "Wu Warship", "Yellow Scarves Cavalry", "Yellow Scarves Troops", "Young Wei Recruits", "Zodiac Dog", "Zodiac Goat", "Zodiac Monkey", "Zodiac Rabbit", "Zodiac Rat", "Zodiac Rooster", "Zodiac Snake");
		this.addCards(Rarity.UNCOMMON, "Alert Shu Infantry", "Barbarian General", "Blaze", "Borrowing 100,000 Arrows", "Brilliant Plan", "Champion's Victory", "Coercion", "Control of the Court", "Corrupt Court Official", "Corrupt Eunuchs", "Council of Advisors", "Counterintelligence", "Cunning Advisor", "Desperate Charge", "Empty City Ruse", "Eunuchs' Intrigues", "False Mourning", "Famine", "Fire Bowman", "Flanking Troops", "Heavy Fog", "Hunting Cheetah", "Imperial Recruiter", "Lone Wolf", "Loyal Retainers", "Mystic Denial", "Peach Garden Oath", "Poison Arrow", "Rally the Troops", "Ravaging Horde", "Red Cliffs Armada", "Renegade Troops", "Rockslide Ambush", "Shu Elite Companions", "Shu General", "Shu Soldier-Farmers", "Spoils of Victory", "Stolen Grain", "Strategic Planning", "Taoist Hermit", "Trained Cheetah", "Trip Wire", "Vengeance", "Warrior's Stand", "Wei Assassins", "Wei Elite Companions", "Wei Night Raiders", "Wu Admiral", "Wu Longbowman", "Wu Spy", "Yuan Shao's Infantry", "Zodiac Horse", "Zodiac Ox", "Zodiac Pig", "Zodiac Tiger");
		this.addCards(Rarity.RARE, "Ambition's Cost", "Balance of Power", "Borrowing the East Wind", "Burning of Xinye", "Cao Cao, Lord of Wei", "Cao Ren, Wei Commander", "Capture of Jingzhou", "Diaochan, Artful Beauty", "Dong Zhou, the Tyrant", "Eightfold Maze", "Exhaustion", "Guan Yu's 1,000-Li March", "Guan Yu, Sainted Warrior", "Hua Tuo, Honored Physician", "Huang Zhong, Shu General", "Imperial Seal", "Kongming's Contraptions", "Kongming, \"Sleeping Dragon\"", "Lady Sun", "Lady Zhurong, Warrior Queen", "Liu Bei, Lord of Shu", "Lu Bu, Master-at-Arms", "Lu Meng, Wu General", "Lu Su, Wu Advisor", "Lu Xun, Scholar General", "Ma Chao, Western Warrior", "Marshaling the Troops", "Meng Huo, Barbarian King", "Overwhelming Forces", "Pang Tong, \"Young Phoenix\"", "Ravages of War", "Relentless Assault", "Riding the Dilu Horse", "Rolling Earthquake", "Sima Yi, Wei Field Marshal", "Slashing Tiger", "Stone Catapult", "Sun Ce, Young Conquerer", "Sun Quan, Lord of Wu", "Taoist Mystic", "Taunting Challenge", "Warrior's Oath", "Wolf Pack", "Xiahou Dun, the One-Eyed", "Xun Yu, Wei Advisor", "Yellow Scarves General", "Yuan Shao, the Indecisive", "Zhang Fei, Fierce Warrior", "Zhang He, Wei General", "Zhang Liao, Hero of Hefei", "Zhao Zilong, Tiger General", "Zhou Yu, Chief Commander", "Zhuge Jin, Wu Strategist", "Zodiac Dragon", "Zuo Ci, the Mocking Sage");
	}
}
