package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Ravnica: City of Guilds")
public final class RavnicaCityOfGuilds extends SimpleExpansion
{
	public RavnicaCityOfGuilds()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Barbarian Riftcutter", "Benevolent Ancestor", "Boros Fury-Shield", "Boros Garrison", "Boros Recruit", "Boros Signet", "Brainspoil", "Bramble Elemental", "Caregiver", "Centaur Safeguard", "Civic Wayfinder", "Clinging Darkness", "Coalhauler Swine", "Compulsive Research", "Conclave Equenaut", "Conclave's Blessing", "Consult the Necrosages", "Convolute", "Courier Hawk", "Dimir Aqueduct", "Dimir House Guard", "Dimir Infiltrator", "Dimir Signet", "Disembowel", "Dizzy Spell", "Dogpile", "Drake Familiar", "Drift of Phantasms", "Dromad Purebred", "Dryad's Caress", "Elves of Deep Shadow", "Elvish Skysweeper", "Faith's Fetters", "Farseek", "Fiery Conclusion", "Fists of Ironwood", "Flight of Fancy", "Galvanic Arc", "Gate Hound", "Gather Courage", "Gaze of the Gorgon", "Goblin Fire Fiend", "Goblin Spelunkers", "Golgari Brownscale", "Golgari Rot Farm", "Golgari Rotwurm", "Golgari Signet", "Grayscaled Gharial", "Greater Mossdog", "Guardian of Vitu-Ghazi", "Incite Hysteria", "Induce Paranoia", "Infectious Host", "Last Gasp", "Leave No Trace", "Lurking Informant", "Mortipede", "Muddle the Mixture", "Necromantic Thirst", "Nightguard Patrol", "Ordruun Commando", "Peel from Reality", "Perplex", "Quickchange", "Rain of Embers", "Rally the Righteous", "Roofstalker Wight", "Sabertooth Alley Cat", "Sadistic Augermage", "Scatter the Seeds", "Screeching Griffin", "Seeds of Strength", "Seismic Spike", "Selesnya Evangel", "Selesnya Sanctuary", "Selesnya Signet", "Sell-Sword Brute", "Sewerdreg", "Shambling Shell", "Shred Memory", "Siege Wurm", "Skyknight Legionnaire", "Smash", "Snapping Drake", "Sparkmage Apprentice", "Stasis Cell", "Stinkweed Imp", "Stone-Seeder Hierophant", "Strands of Undeath", "Sundering Vitae", "Surge of Zeal", "Surveilling Sprite", "Tattered Drake", "Terraformer", "Terrarion", "Thoughtpicker Witch", "Thundersong Trumpeter", "Tidewater Minion", "Torpid Moloch", "Transluminant", "Vedalken Dismisser", "Vedalken Entrancer", "Veteran Armorer", "Viashino Fangtail", "Viashino Slasher", "Votary of the Conclave", "War-Torch Goblin", "Wojek Siren", "Woodwraith Strangler", "Zephyr Spirit");
		this.addCards(Rarity.UNCOMMON, "Auratouched Mage", "Bathe in Light", "Belltower Sphinx", "Blockbuster", "Boros Guildmage", "Boros Swiftblade", "Carrion Howler", "Carven Caryatid", "Chant of Vitu-Ghazi", "Cleansing Beam", "Clutch of the Undercity", "Conclave Phalanx", "Congregation at Dawn", "Cyclopean Snare", "Dark Heart of the Wood", "Darkblast", "Devouring Light", "Dimir Guildmage", "Dimir Machinations", "Divebomber Griffin", "Dowsing Shaman", "Drooling Groodion", "Duskmantle, House of Shadow", "Ethereal Usher", "Festival of the Guildpact", "Flame-Kin Zealot", "Flash Conscription", "Flow of Ideas", "Frenzied Goblin", "Glass Golem", "Golgari Germination", "Golgari Guildmage", "Golgari Thug", "Goliath Spider", "Greater Forgeling", "Grifter's Blade", "Halcyon Glaze", "Indentured Oaf", "Instill Furor", "Ivy Dancer", "Junktroller", "Keening Banshee", "Leashling", "Lightning Helix", "Lore Broker", "Mark of Eviction", "Mausoleum Turnkey", "Mnemonic Nexus", "Moldervine Cloak", "Moroii", "Netherborn Phalanx", "Nightmare Void", "Nullmage Shepherd", "Oathsworn Giant", "Overwhelm", "Peregrine Mask", "Perilous Forays", "Pollenbright Wings", "Psychic Drain", "Putrefy", "Recollect", "Remand", "Reroute", "Ribbons of Night", "Rolling Spoil", "Root-Kin Ally", "Sandsower", "Seed Spark", "Selesnya Guildmage", "Selesnya Sagittars", "Spectral Searchlight", "Stoneshaker Shaman", "Sunhome Enforcer", "Sunhome, Fortress of the Legion", "Suppression Field", "Svogthos, the Restless Tomb", "Telling Time", "Trophy Hunter", "Twisted Justice", "Undercity Shade", "Vigor Mortis", "Vindictive Mob", "Vitu-Ghazi, the City-Tree", "Voyager Staff", "Watchwolf", "Wizened Snitches", "Wojek Apothecary", "Wojek Embermage");
		this.addCards(Rarity.RARE, "Agrus Kos, Wojek Veteran", "Autochthon Wurm", "Birds of Paradise", "Blazing Archon", "Blood Funnel", "Bloodbond March", "Bloodletter Quill", "Bottled Cloister", "Breath of Fury", "Brightflame", "Cerulean Sphinx", "Char", "Chord of Calling", "Chorus of the Conclave", "Circu, Dimir Lobotomist", "Cloudstone Curio", "Concerted Effort", "Copy Enchantment", "Crown of Convergence", "Dark Confidant", "Dimir Cutpurse", "Dimir Doppelganger", "Doubling Season", "Dream Leash", "Empty the Catacombs", "Excruciator", "Eye of the Storm", "Firemane Angel", "Flame Fusillade", "Flickerform", "Followed Footsteps", "Ghosts of the Innocent", "Glare of Subdual", "Gleancrawler", "Glimpse the Unthinkable", "Golgari Grave-Troll", "Grave-Shell Scarab", "Grozoth", "Hammerfist Giant", "Helldozer", "Hex", "Hour of Reckoning", "Hunted Dragon", "Hunted Horror", "Hunted Lammasu", "Hunted Phantasm", "Hunted Troll", "Life from the Loam", "Light of Sanction", "Loxodon Gatekeeper", "Loxodon Hierarch", "Master Warcraft", "Mindleech Mass", "Mindmoil", "Molten Sentry", "Moonlight Bargain", "Necroplasm", "Nullstone Gargoyle", "Overgrown Tomb", "Pariah's Shield", "Phytohydra", "Plague Boiler", "Primordial Sage", "Privileged Position", "Razia's Purification", "Razia, Boros Archangel", "Sacred Foundry", "Savra, Queen of the Golgari", "Scion of the Wild", "Searing Meditation", "Shadow of Doubt", "Sins of the Past", "Sisters of Stone Death", "Spawnbroker", "Sunforger", "Szadek, Lord of Secrets", "Temple Garden", "Three Dreams", "Tolsimir Wolfblood", "Tunnel Vision", "Twilight Drover", "Ursapine", "Vinelasher Kudzu", "Vulturous Zombie", "Warp World", "Watery Grave", "Woebringer Demon", "Woodwraith Corrupter");
	}
}
