package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Return to Ravnica")
public final class ReturnToRavnica extends SimpleExpansion
{
	public ReturnToRavnica()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "Aerial Predation", "Annihilating Fire", "Armory Guard", "Auger Spree", "Avenging Arrow", "Axebane Guardian", "Axebane Stag", "Azorius Arrester", "Azorius Guildgate", "Batterhorn", "Bellows Lizard", "Cancel", "Catacomb Slug", "Centaur Healer", "Centaur's Herald", "Chemister's Trick", "Chorus of Might", "Chronic Flooding", "Cobblebrute", "Common Bond", "Concordia Pegasus", "Coursers' Accord", "Cremate", "Crosstown Courier", "Daggerdrome Imp", "Dead Reveler", "Destroy the Evidence", "Deviant Glee", "Dispel", "Doorkeeper", "Downsize", "Drainpipe Vermin", "Dramatic Rescue", "Drudge Beetle", "Druid's Deliverance", "Dynacharge", "Electrickery", "Essence Backlash", "Ethereal Armor", "Explosive Impact", "Eyes in the Skies", "Frostburn Weird", "Gatecreeper Vine", "Giant Growth", "Goblin Electromancer", "Golgari Guildgate", "Golgari Longlegs", "Gore-House Chainwalker", "Grim Roustabout", "Grisly Salvage", "Horncaller's Chant", "Hussar Patrol", "Inaction Injunction", "Inspiration", "Isperia's Skywatch", "Izzet Guildgate", "Keening Apparition", "Knightly Valor", "Korozda Monitor", "Launch Party", "Lobber Crew", "Mind Rot", "Mizzium Skin", "Ogre Jailbreaker", "Paralyzing Grasp", "Perilous Shadow", "Pursuit of Flight", "Rakdos Guildgate", "Rakdos Shred-Freak", "Rootborn Defenses", "Rubbleback Rhino", "Runewing", "Search Warrant", "Selesnya Guildgate", "Selesnya Sentry", "Seller of Songbirds", "Sewer Shambler", "Skull Rend", "Sluiceway Scorpion", "Spawn of Rix Maadi", "Splatter Thug", "Stab Wound", "Stealer of Secrets", "Stonefare Crocodile", "Sundering Growth", "Sunspire Griffin", "Survey the Wreckage", "Swift Justice", "Tenement Crasher", "Terrus Wurm", "Tower Drake", "Towering Indrik", "Trained Caracal", "Traitorous Instinct", "Transguild Promenade", "Trestle Troll", "Trostani's Judgment", "Urban Burgeoning", "Vassal Soul", "Viashino Racketeer", "Voidwielder");
		this.addCards(Rarity.UNCOMMON, "Aquus Steed", "Archweaver", "Arrest", "Assassin's Strike", "Azorius Charm", "Azorius Justiciar", "Azorius Keyrune", "Bazaar Krovod", "Blistercoil Weird", "Bloodfray Giant", "Blustersquall", "Brushstrider", "Call of the Conclave", "Civic Saber", "Codex Shredder", "Dark Revenant", "Dreg Mangler", "Dryad Militant", "Faerie Impostor", "Fall of the Gavel", "Fencing Ace", "Gobbling Ooze", "Goblin Rally", "Golgari Charm", "Golgari Decoy", "Golgari Keyrune", "Guttersnipe", "Hellhole Flailer", "Heroes' Reunion", "Hover Barrier", "Izzet Charm", "Izzet Keyrune", "Izzet Staticaster", "Judge's Familiar", "Korozda Guildmage", "Lyev Skyknight", "Minotaur Aggressor", "New Prahv Guildmage", "Nivix Guildmage", "Oak Street Innkeeper", "Phantom General", "Psychic Spiral", "Pyroconvergence", "Racecourse Fury", "Rakdos Cackler", "Rakdos Charm", "Rakdos Keyrune", "Rakdos Ragemutt", "Rakdos Ringleader", "Risen Sanctuary", "Rites of Reaping", "Rix Maadi Guildmage", "Rogue's Passage", "Savage Surge", "Security Blockade", "Seek the Horizon", "Selesnya Charm", "Selesnya Keyrune", "Shrieking Affliction", "Skyline Predator", "Skymark Roc", "Slime Molding", "Slitherhead", "Slum Reaper", "Soul Tithe", "Soulsworn Spirit", "Sphere of Safety", "Street Spasm", "Street Sweeper", "Syncopate", "Tablet of the Guilds", "Tavern Swindler", "Teleportal", "Thoughtflare", "Thrill-Kill Assassin", "Treasured Find", "Ultimate Price", "Vandalblast", "Vitu-Ghazi Guildmage", "Zanikev Locust");
		this.addCards(Rarity.RARE, "Abrupt Decay", "Archon of the Triumvirate", "Ash Zealot", "Azor's Elocutors", "Blood Crypt", "Carnival Hellsteed", "Chaos Imps", "Chromatic Lantern", "Collective Blessing", "Conjured Currency", "Corpsejack Menace", "Counterflux", "Cryptborn Horror", "Cyclonic Rift", "Deadbridge Goliath", "Death's Presence", "Deathrite Shaman", "Desecration Demon", "Detention Sphere", "Dreadbore", "Firemind's Foresight", "Grave Betrayal", "Grove of the Guardian", "Growing Ranks", "Guild Feud", "Hallowed Fountain", "Havoc Festival", "Hypersonic Dragon", "Jarad's Orders", "Lotleth Troll", "Loxodon Smiter", "Mana Bloom", "Martial Law", "Mercurial Chemister", "Mizzium Mortars", "Nivmagus Elemental", "Overgrown Tomb", "Pack Rat", "Palisade Giant", "Pithing Needle", "Precinct Captain", "Rest in Peace", "Righteous Authority", "Search the City", "Slaughter Games", "Sphinx of the Chimes", "Steam Vents", "Supreme Verdict", "Temple Garden", "Underworld Connections", "Volatile Rig", "Wayfaring Temple", "Wild Beastmaster");
		this.addCards(Rarity.MYTHIC, "Angel of Serenity", "Armada Wurm", "Epic Experiment", "Isperia, Supreme Judge", "Jace, Architect of Thought", "Jarad, Golgari Lich Lord", "Necropolis Regent", "Niv-Mizzet, Dracogenius", "Rakdos's Return", "Rakdos, Lord of Riots", "Sphinx's Revelation", "Trostani, Selesnya's Voice", "Utvara Hellkite", "Vraska the Unseen", "Worldspine Wurm");
	}
}
