package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Revised Edition")
public final class RevisedEdition extends SimpleExpansion
{
	public RevisedEdition()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "Atog", "Benalish Hero", "Blue Elemental Blast", "Circle of Protection: Black", "Circle of Protection: Blue", "Circle of Protection: Green", "Circle of Protection: Red", "Circle of Protection: White", "Craw Wurm", "Creature Bond", "Dark Ritual", "Death Ward", "Disenchant", "Disintegrate", "Drain Life", "Drudge Skeletons", "Dwarven Warriors", "Earthbind", "Erg Raiders", "Fear", "Fireball", "Firebreathing", "Flight", "Fog", "Frozen Shade", "Giant Growth", "Giant Spider", "Gray Ogre", "Grizzly Bears", "Guardian Angel", "Healing Salve", "Hill Giant", "Holy Armor", "Holy Strength", "Howl from Beyond", "Hurloon Minotaur", "Ironroot Treefolk", "Jump", "Kird Ape", "Lightning Bolt", "Llanowar Elves", "Merfolk of the Pearl Trident", "Mesa Pegasus", "Mons's Goblin Raiders", "Paralyze", "Pearled Unicorn", "Pestilence", "Phantasmal Terrain", "Plague Rats", "Power Leak", "Power Sink", "Prodigal Sorcerer", "Psychic Venom", "Raise Dead", "Reconstruction", "Red Elemental Blast", "Regeneration", "Samite Healer", "Scathe Zombies", "Scryb Sprites", "Sea Serpent", "Shanodin Dryads", "Shatter", "Spell Blast", "Stone Rain", "Stream of Life", "Terror", "Tranquility", "Unholy Strength", "Unstable Mutation", "Unsummon", "Wall of Wood", "War Mammoth", "Weakness", "Wild Growth");
		this.addCards(Rarity.UNCOMMON, "Air Elemental", "Animate Artifact", "Animate Dead", "Basalt Monolith", "Black Knight", "Black Vise", "Black Ward", "Blue Ward", "Bog Wraith", "Brass Man", "Burrowing", "Castle", "Celestial Prism", "Channel", "Clone", "Conservator", "Control Magic", "Conversion", "Counterspell", "Crumble", "Crystal Rod", "Cursed Land", "Deathgrip", "Demonic Tutor", "Desert Twister", "Dragon Whelp", "Dwarven Weaponsmith", "Earth Elemental", "Energy Flux", "Evil Presence", "Feedback", "Fire Elemental", "Flashfires", "Glasses of Urza", "Gloom", "Goblin Balloon Brigade", "Green Ward", "Hurricane", "Hypnotic Specter", "Instill Energy", "Iron Star", "Ivory Cup", "Juggernaut", "Karma", "Keldon Warlord", "Lance", "Ley Druid", "Library of Leng", "Lifeforce", "Lifetap", "Living Wall", "Lure", "Nettling Imp", "Obsianus Golem", "Orcish Artillery", "Orcish Oriflamme", "Ornithopter", "Phantasmal Forces", "Phantom Monster", "Red Ward", "Regrowth", "Resurrection", "Reverse Polarity", "Rod of Ruin", "Sacrifice", "Scavenging Ghoul", "Sengir Vampire", "Serra Angel", "Shatterstorm", "Simulacrum", "Siren's Call", "Sol Ring", "Soul Net", "Steal Artifact", "Stone Giant", "Swords to Plowshares", "The Rack", "Thicket Basilisk", "Throne of Bone", "Tsunami", "Tunnel", "Uthden Troll", "Wall of Air", "Wall of Bone", "Wall of Brambles", "Wall of Fire", "Wall of Ice", "Wall of Stone", "Wall of Swords", "Wall of Water", "Wanderlust", "Water Elemental", "White Knight", "White Ward", "Wooden Sphere");
		this.addCards(Rarity.RARE, "Aladdin's Lamp", "Aladdin's Ring", "Animate Wall", "Ankh of Mishra", "Armageddon", "Armageddon Clock", "Aspect of Wolf", "Bad Moon", "Badlands", "Balance", "Bayou", "Birds of Paradise", "Blessing", "Bottle of Suleiman", "Braingeyser", "Chaoslace", "Clockwork Beast", "Cockatrice", "Contract from Below", "Copy Artifact", "Crusade", "Dancing Scimitar", "Darkpact", "Deathlace", "Demonic Attorney", "Demonic Hordes", "Dingus Egg", "Disrupting Scepter", "Dragon Engine", "Drain Power", "Earthquake", "Ebony Horse", "El-Hajjâj", "Elvish Archers", "Eye for an Eye", "Farmstead", "Fastbond", "Flying Carpet", "Force of Nature", "Fork", "Fungusaur", "Gaea's Liege", "Goblin King", "Granite Gargoyle", "Helm of Chatzuk", "Howling Mine", "Hurkyl's Recall", "Island Fish Jasconius", "Island Sanctuary", "Ivory Tower", "Jade Monolith", "Jandor's Ring", "Jandor's Saddlebags", "Jayemdae Tome", "Kormus Bell", "Kudzu", "Lifelace", "Living Artifact", "Living Lands", "Lord of Atlantis", "Lord of the Pit", "Magical Hack", "Magnetic Mountain", "Mahamoti Djinn", "Mana Flare", "Mana Short", "Mana Vault", "Manabarbs", "Meekstone", "Mijae Djinn", "Millstone", "Mind Twist", "Mishra's War Machine", "Nether Shadow", "Nevinyrral's Disk", "Nightmare", "Northern Paladin", "Onulet", "Personal Incarnation", "Pirate Ship", "Plateau", "Power Surge", "Primal Clay", "Purelace", "Reverse Damage", "Righteousness", "Roc of Kher Ridges", "Rock Hydra", "Rocket Launcher", "Royal Assassin", "Savannah", "Savannah Lions", "Scrubland", "Sedge Troll", "Serendib Efreet", "Shivan Dragon", "Sleight of Mind", "Smoke", "Sorceress Queen", "Stasis", "Sunglasses of Urza", "Taiga", "The Hive", "Thoughtlace", "Timber Wolves", "Titania's Song", "Tropical Island", "Tundra", "Underground Sea", "Verduran Enchantress", "Vesuvan Doppelganger", "Veteran Bodyguard", "Volcanic Eruption", "Volcanic Island", "Warp Artifact", "Web", "Wheel of Fortune", "Will-o'-the-Wisp", "Winter Orb", "Wrath of God", "Zombie Master");
	}
}
