package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Rise of the Eldrazi")
public final class RiseOfTheEldrazi extends SimpleExpansion
{
	public RiseOfTheEldrazi()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Ancient Stirrings", "Aura Finesse", "Aura Gnarlid", "Bala Ged Scorpion", "Battle Rampart", "Battle-Rattle Shaman", "Bloodrite Invoker", "Bloodthrone Vampire", "Brood Birthing", "Cadaver Imp", "Caravan Escort", "Champion's Drake", "Contaminated Ground", "Daggerback Basilisk", "Dawnglare Invoker", "Death Cultist", "Demonic Appetite", "Demystify", "Deprive", "Distortion Strike", "Dread Drone", "Eel Umbra", "Eland Umbra", "Emrakul's Hatcher", "Essence Feed", "Evolving Wilds", "Fissure Vent", "Flame Slash", "Fleeting Distraction", "Frostwind Invoker", "Gloomhunter", "Glory Seeker", "Goblin Arsonist", "Goblin Tunneler", "Grotag Siege-Runner", "Growth Spasm", "Guard Duty", "Halimar Wavewatch", "Hand of Emrakul", "Harmless Assault", "Haze Frog", "Heat Ray", "Hyena Umbra", "Ikiral Outrider", "Induce Despair", "Jwari Scuttler", "Kiln Fiend", "Knight of Cliffhaven", "Kor Line-Slinger", "Kozilek's Predator", "Lagac Lizard", "Last Kiss", "Lavafume Invoker", "Lay Bare", "Leaf Arrow", "Living Destiny", "Lone Missionary", "Makindi Griffin", "Merfolk Observer", "Might of the Masses", "Mnemonic Wall", "Narcolepsy", "Naturalize", "Nema Siltlurker", "Nest Invader", "Nighthaze", "Null Champion", "Ogre Sentry", "Ondu Giant", "Overgrown Battlement", "Perish the Thought", "Prophetic Prism", "Puncturing Light", "Raid Bombardment", "Regress", "Reinforced Bulwark", "Repel the Darkness", "Sea Gate Oracle", "See Beyond", "Shared Discovery", "Shrivel", "Skywatcher Adept", "Smite", "Snake Umbra", "Soul's Attendant", "Spawning Breath", "Spider Umbra", "Sporecap Spider", "Staggershock", "Stalwart Shield-Bearers", "Stomper Cub", "Totem-Guide Hartebeest", "Ulamog's Crusher", "Vendetta", "Venerated Teacher", "Vent Sentinel", "Wildheart Invoker", "Wrap in Flames", "Zof Shade", "Zulaport Enforcer");
		this.addCards(Rarity.UNCOMMON, "Affa Guard Hound", "Akoum Boulderfoot", "Arrogant Bloodlord", "Artisan of Kozilek", "Beastbreaker of Bala Ged", "Boar Umbra", "Bramblesnap", "Brimstone Mage", "Broodwarden", "Corpsehatch", "Crab Umbra", "Curse of Wizardry", "Domestication", "Drake Umbra", "Dreamstone Hedron", "Emerge Unscathed", "Enatu Golem", "Enclave Cryptologist", "Escaped Null", "Explosive Revelation", "Forked Bolt", "Gravity Well", "Guard Gomazoa", "Hada Spy Patrol", "Inquisition of Kozilek", "Irresistible Prey", "Jaddi Lifestrider", "Joraga Treespeaker", "Kabira Vindicator", "Luminous Wake", "Lust for War", "Mammoth Umbra", "Merfolk Skyscout", "Nirkana Cutthroat", "Not of This World", "Ogre's Cleaver", "Oust", "Pathrazer of Ulamog", "Pawn of Ulamog", "Pelakka Wurm", "Pennon Blade", "Phantasmal Abomination", "Prey's Vengeance", "Rapacious One", "Reality Spasm", "Runed Servitor", "Skeletal Wurm", "Skittering Invasion", "Soulbound Guardians", "Soulsurge Elemental", "Suffer the Past", "Surreal Memoir", "Survival Cache", "Time of Heroes", "Traitorous Instinct", "Unified Will", "Valakut Fireboar", "Virulent Swipe", "Wall of Omens", "Warmonger's Chariot");
		this.addCards(Rarity.RARE, "Angelheart Vial", "Awakening Zone", "Baneful Omen", "Bear Umbra", "Conquering Manticore", "Consume the Meek", "Consuming Vapors", "Coralhelm Commander", "Deathless Angel", "Devastating Summons", "Disaster Radius", "Dormant Gomazoa", "Drana, Kalastria Bloodchief", "Echo Mage", "Eldrazi Conscription", "Eldrazi Temple", "Gelatinous Genesis", "Gigantomancer", "Gravitational Shift", "Guul Draz Assassin", "Hedron Matrix", "Hedron-Field Purists", "Hellion Eruption", "It That Betrays", "Kazandu Tuskcaller", "Keening Stone", "Kor Spiritdancer", "Lightmine Field", "Lord of Shatterskull Pass", "Magmaw", "Momentous Fall", "Mortician Beetle", "Mul Daya Channelers", "Near-Death Experience", "Nomads' Assembly", "Pestilence Demon", "Rage Nimbus", "Realms Uncharted", "Recurring Insight", "Renegade Doppelganger", "Repay in Kind", "Spawnsire of Ulamog", "Sphinx of Magosi", "Sphinx-Bone Wand", "Splinter Twin", "Student of Warfare", "Surrakar Spellblade", "Tajuru Preserver", "Thought Gorger", "Training Grounds", "Tuktuk the Explorer", "Umbra Mystic", "World at War");
		this.addCards(Rarity.MYTHIC, "All Is Dust", "Cast Through Time", "Emrakul, the Aeons Torn", "Gideon Jura", "Hellcarver Demon", "Kargan Dragonlord", "Khalni Hydra", "Kozilek, Butcher of Truth", "Lighthouse Chronologist", "Linvala, Keeper of Silence", "Nirkana Revenant", "Sarkhan the Mad", "Transcendent Master", "Ulamog, the Infinite Gyre", "Vengevine");
	}
}
