package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Saviors of Kamigawa")
public final class SaviorsOfKamigawa extends SimpleExpansion
{
	public SaviorsOfKamigawa()
	{
		super();

		this.addCards(Rarity.COMMON, "Akki Drillmaster", "Akki Underling", "Araba Mothrider", "Barrel Down Sokenzan", "Cowed by Wisdom", "Curtain of Light", "Cut the Earthly Bond", "Death Denied", "Death of a Thousand Stings", "Deathknell Kami", "Deathmask Nezumi", "Descendant of Soramaro", "Dosan's Oldest Chant", "Dreamcatcher", "Elder Pine of Jukai", "Fiddlehead Kami", "Freed from the Real", "Glitterfang", "Gnat Miser", "Ideas Unbound", "Inner Calm, Outer Strength", "Inner Fire", "Into the Fray", "Kagemaro's Clutch", "Kami of Empty Graves", "Kitsune Bonesetter", "Kitsune Dawnblade", "Kitsune Loreweaver", "Kuro's Taken", "Matsu-Tribe Birdstalker", "Minamo Scrollkeeper", "Moonbow Illusionist", "Moonwing Moth", "Murmurs from Beyond", "Nightsoil Kami", "Oboro Breezecaller", "Okina Nightwatch", "Oppressive Will", "Path of Anger's Flame", "Plow Through Reito", "Promised Kannushi", "Raving Oni-Slave", "Rending Vines", "Ronin Cavekeeper", "Sakura-Tribe Scout", "Shinen of Fear's Chill", "Shinen of Flight's Wings", "Shinen of Fury's Fire", "Shinen of Life's Roar", "Shinen of Stars' Light", "Sink into Takenuma", "Sokenzan Spellblade", "Spiraling Embers", "Spiritual Visit", "Torii Watchward");
		this.addCards(Rarity.UNCOMMON, "AEther Shockwave", "Briarknit Kami", "Burning-Eye Zubera", "Captive Flame", "Charge Across the Araba", "Dense Canopy", "Descendant of Kiyomaro", "Descendant of Masumaro", "Ebony Owl Netsuke", "Eiganjo Free-Riders", "Evermind", "Exile into Darkness", "Feral Lightning", "Footsteps of the Goryo", "Gaze of Adamaro", "Ghost-Lit Nourisher", "Ghost-Lit Raider", "Ghost-Lit Redeemer", "Ghost-Lit Stalker", "Ghost-Lit Warder", "Godo's Irregulars", "Hail of Arrows", "Hand of Cruelty", "Hand of Honor", "Haru-Onna", "Inner-Chamber Guard", "Ivory Crane Netsuke", "Kami of the Tended Garden", "Kashi-Tribe Elite", "Kemuri-Onna", "Kiku's Shadow", "Kiri-Onna", "Locust Miser", "Manriki-Gusari", "Measure of Wickedness", "Molting Skin", "Nikko-Onna", "O-Naginata", "Oboro Envoy", "Oni of Wild Places", "Overwhelming Intellect", "Presence of the Wise", "Razorjaw Oni", "Rushing-Tide Zubera", "Secretkeeper", "Seek the Horizon", "Shape Stealer", "Shifting Borders", "Skull Collector", "Sokenzan Renegade", "Soratami Cloud Chariot", "Stampeding Serow", "Sunder from Within", "Trusted Advisor", "Yuki-Onna");
		this.addCards(Rarity.RARE, "Adamaro, First to Desire", "Akuta, Born of Ash", "Arashi, the Sky Asunder", "Ashes of the Fallen", "Ayumi, the Last Visitor", "Blood Clock", "Bounteous Kirin", "Celestial Kirin", "Choice of Damnations", "Cloudhoof Kirin", "Endless Swarm", "Enduring Ideal", "Erayo, Soratami Ascendant", "Eternal Dominion", "Hidetsugu's Second Rite", "Homura, Human Ascendant", "Iizuka the Ruthless", "Iname as One", "Infernal Kirin", "Jiwari, the Earth Aflame", "Kagemaro, First to Suffer", "Kaho, Minamo Historian", "Kami of the Crescent Moon", "Kataki, War's Wage", "Kiyomaro, First to Stand", "Kuon, Ogre Ascendant", "Maga, Traitor to Mortals", "Masumaro, First to Live", "Meishin, the Mind Cage", "Michiko Konda, Truth Seeker", "Mikokoro, Center of the Sea", "Miren, the Moaning Well", "Neverending Torment", "Oboro, Palace in the Clouds", "One with Nothing", "Pain's Reward", "Pithing Needle", "Promise of Bunrei", "Pure Intentions", "Rally the Horde", "Reki, the History of Kamigawa", "Reverence", "Rune-Tail, Kitsune Ascendant", "Sakashima the Impostor", "Sasaya, Orochi Ascendant", "Scroll of Origins", "Seed the Land", "Sekki, Seasons' Guide", "Skyfire Kirin", "Soramaro, First to Dream", "Thoughts of Ruin", "Tomb of Urami", "Twincast", "Undying Flames", "Wine of Blood and Iron");
	}
}
