package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Scars of Mirrodin")
public final class ScarsOfMirrodin extends SimpleExpansion
{
	public ScarsOfMirrodin()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "Accorder's Shield", "Alpha Tyrranax", "Arrest", "Assault Strobe", "Auriok Replica", "Auriok Sunchaser", "Blackcleave Goblin", "Blade-Tribe Berserkers", "Bladed Pinions", "Bleak Coven Vampires", "Blight Mamba", "Blistergrub", "Blunt the Assault", "Bonds of Quicksilver", "Carapace Forger", "Chrome Steed", "Contagious Nim", "Copper Myr", "Copperhorn Scout", "Corpse Cur", "Cystbearer", "Disperse", "Dross Hopper", "Echo Circlet", "Ezuri's Archers", "Ferrovore", "Flameborn Hellion", "Flight Spellbomb", "Fulgent Distraction", "Fume Spitter", "Galvanic Blast", "Ghalma's Warden", "Glimmerpost", "Glint Hawk", "Glint Hawk Idol", "Goblin Gaveleer", "Gold Myr", "Golden Urn", "Golem Foundry", "Grasp of Darkness", "Horizon Spellbomb", "Ichorclaw Myr", "Instill Infection", "Iron Myr", "Kemba's Skyguard", "Kuldotha Rebirth", "Leaden Myr", "Loxodon Wayfarer", "Lumengrid Drake", "Melt Terrain", "Molder Beast", "Moriok Reaver", "Moriok Replica", "Necrogen Censer", "Neurok Invisimancer", "Neurok Replica", "Nihil Spellbomb", "Origin Spellbomb", "Oxidda Daredevil", "Panic Spellbomb", "Perilous Myr", "Plague Stinger", "Plated Seastrider", "Psychic Miasma", "Razorfield Thresher", "Relic Putrescence", "Revoke Existence", "Saberclaw Golem", "Salvage Scout", "Scoria Elemental", "Scrapdiver Serpent", "Screeching Silcaw", "Seize the Initiative", "Shatter", "Silver Myr", "Sky-Eel School", "Snapsail Glider", "Soliton", "Soul Parry", "Steady Progress", "Stoic Rebuttal", "Strider Harness", "Sunspear Shikari", "Sylvok Lifestaff", "Sylvok Replica", "Tainted Strike", "Tel-Jilad Defiance", "Tel-Jilad Fallen", "Tumble Magnet", "Turn Aside", "Turn to Slag", "Untamed Might", "Vault Skyward", "Vector Asp", "Vedalken Certarch", "Vulshok Heartstoker", "Vulshok Replica", "Wall of Tanglecord", "Whitesun's Passage", "Wing Puncture", "Withstand Death");
		this.addCards(Rarity.UNCOMMON, "Abuna Acolyte", "Acid Web Spider", "Arc Trail", "Auriok Edgewright", "Barbed Battlegear", "Barrage Ogre", "Bellowing Tanglewurm", "Bloodshot Trainee", "Carrion Call", "Clone Shell", "Contagion Clasp", "Corrupted Harvester", "Culling Dais", "Darkslick Drake", "Darksteel Axe", "Darksteel Myr", "Darksteel Sentinel", "Dispense Justice", "Embersmith", "Exsanguinate", "Flesh Allergy", "Furnace Celebration", "Glimmerpoint Stag", "Golem Artisan", "Golem's Heart", "Grafted Exoskeleton", "Halt Order", "Heavy Arbalest", "Ichor Rats", "Infiltration Lens", "Lifesmith", "Liquimetal Coating", "Memnite", "Myr Galvanizer", "Myrsmith", "Necrogen Scudder", "Necropede", "Ogre Geargrabber", "Oxidda Scrapmelter", "Painsmith", "Palladium Myr", "Razor Hippogriff", "Riddlesmith", "Rust Tick", "Rusted Relic", "Skinrender", "Slice in Twain", "Tangle Angler", "Throne of Geth", "Thrummingbird", "Trigon of Corruption", "Trigon of Infestation", "Trigon of Mending", "Trigon of Rage", "Trigon of Thought", "Trinket Mage", "Twisted Image", "Vigil for the Lost", "Viridian Revel", "Volition Reins");
		this.addCards(Rarity.RARE, "Argent Sphinx", "Argentum Armor", "Asceticism", "Blackcleave Cliffs", "Carnifex Demon", "Cerebral Eruption", "Chimeric Mass", "Contagion Engine", "Copperline Gorge", "Darkslick Shores", "Darksteel Juggernaut", "Dissipation Field", "Engulfing Slagwurm", "Etched Champion", "Ezuri's Brigade", "Ezuri, Renegade Leader", "Genesis Wave", "Grand Architect", "Grindclock", "Hand of the Praetors", "Hoard-Smelter Dragon", "Inexorable Tide", "Kemba, Kha Regent", "Kuldotha Forgemaster", "Kuldotha Phoenix", "Leonin Arbiter", "Livewire Lash", "Memoricide", "Mimic Vat", "Molten Psyche", "Myr Battlesphere", "Myr Propagator", "Myr Reservoir", "Necrotic Ooze", "Nim Deathmantle", "Painful Quandary", "Precursor Golem", "Prototype Portal", "Putrefax", "Ratchet Bomb", "Razorverge Thicket", "Seachrome Coast", "Semblance Anvil", "Shape Anew", "Spikeshot Elder", "Steel Hellkite", "Strata Scythe", "Sunblast Angel", "Tempered Steel", "Tower of Calamities", "True Conviction", "Tunnel Ignus", "Venser's Journal");
		this.addCards(Rarity.MYTHIC, "Elspeth Tirel", "Geth, Lord of the Vault", "Indomitable Archangel", "Koth of the Hammer", "Liege of the Tangle", "Lux Cannon", "Mindslaver", "Molten-Tail Masticore", "Mox Opal", "Platinum Emperion", "Quicksilver Gargantuan", "Skithiryx, the Blight Dragon", "Sword of Body and Mind", "Venser, the Sojourner", "Wurmcoil Engine");
	}
}
