package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Seventh Edition")
public final class SeventhEdition extends SimpleExpansion
{
	public SeventhEdition()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Angelic Page", "Balduvian Barbarians", "Blood Pet", "Bog Imp", "Boomerang", "Canopy Spider", "Circle of Protection: Black", "Circle of Protection: Blue", "Circle of Protection: Green", "Circle of Protection: Red", "Circle of Protection: White", "Cloudchaser Eagle", "Coral Merfolk", "Corrupt", "Counterspell", "Crossbow Infantry", "Dark Banishing", "Disenchant", "Drudge Skeletons", "Duress", "Eager Cadet", "Fear", "Flight", "Fog", "Force Spike", "Giant Cockroach", "Giant Growth", "Giant Octopus", "Giant Spider", "Goblin Chariot", "Goblin Digging Team", "Goblin Elite Infantry", "Goblin Gardener", "Goblin Raider", "Goblin Spelunkers", "Gorilla Chieftain", "Granite Grip", "Gravedigger", "Grizzly Bears", "Healing Salve", "Hill Giant", "Hollow Dogs", "Holy Strength", "Honor Guard", "Horned Turtle", "Howl from Beyond", "Inspiration", "Knight Errant", "Lava Axe", "Lightning Blast", "Lightning Elemental", "Llanowar Elves", "Lone Wolf", "Looming Shade", "Memory Lapse", "Merfolk of the Pearl Trident", "Mind Rot", "Monstrous Growth", "Nausea", "Ostracize", "Pacifism", "Plague Beetle", "Prodigal Sorcerer", "Pygmy Pyrosaur", "Raging Goblin", "Raise Dead", "Rampant Growth", "Razorfoot Griffin", "Razortooth Rats", "Reclaim", "Redwood Treefolk", "Reflexes", "Regeneration", "Remove Soul", "Sabretooth Tiger", "Sacred Nectar", "Sage Owl", "Samite Healer", "Scathe Zombies", "Sea Monster", "Seeker of Skybreak", "Serpent Warrior", "Shanodin Dryads", "Shatter", "Shield Wall", "Shock", "Skyshroud Falcon", "Sleight of Hand", "Spined Wurm", "Spineless Thug", "Spitting Earth", "Squall", "Standing Troops", "Stone Rain", "Storm Crow", "Stream of Life", "Telepathic Spies", "Tolarian Winds", "Trained Armodon", "Tranquility", "Tremor", "Twiddle", "Unholy Strength", "Unsummon", "Venerable Monk", "Vigilant Drake", "Volcanic Hammer", "Wild Growth", "Wind Drake", "Wood Elves");
		this.addCards(Rarity.UNCOMMON, "AEther Flash", "Abyssal Specter", "Agonizing Memories", "Air Elemental", "Anaconda", "Arcane Laboratory", "Ardent Militia", "Baleful Stare", "Befoul", "Bereavement", "Blanchwood Armor", "Blaze", "Bog Wraith", "Boil", "Breath of Life", "Bull Hippo", "Caltrops", "Castle", "Charcoal Diamond", "Compost", "Confiscate", "Creeping Mold", "Crypt Rats", "Crystal Rod", "Dakmor Lancer", "Disorder", "Elvish Lyrist", "Engineered Plague", "Familiar Ground", "Femeref Archers", "Fighting Drake", "Fire Diamond", "Fire Elemental", "Foul Imp", "Fugue", "Fyndhorn Elder", "Gang of Elk", "Gerrard's Wisdom", "Ghitu Fire-Eater", "Glacial Wall", "Goblin Glider", "Goblin Matron", "Goblin War Drums", "Grapeshot Catapult", "Heavy Ballista", "Hibernation", "Iron Star", "Ivory Cup", "Knighthood", "Leshrac's Rite", "Levitation", "Longbow Archer", "Lure", "Mana Breach", "Marble Diamond", "Megrim", "Merfolk Looter", "Moss Diamond", "Necrologia", "Nocturnal Raid", "Ogre Taskmaster", "Opportunity", "Orcish Artillery", "Orcish Oriflamme", "Patagia Golem", "Phantom Warrior", "Phyrexian Hulk", "Pillage", "Pit Trap", "Pride of Lions", "Pyroclasm", "Pyrotechnics", "Reprisal", "Rod of Ruin", "Sanctimony", "Scavenger Folk", "Seasoned Marshal", "Serra Advocate", "Serra's Embrace", "Sisay's Ring", "Sky Diamond", "Soul Feast", "Soul Net", "Spellbook", "Spirit Link", "Starlight", "Staunch Defenders", "Steal Artifact", "Storm Shaman", "Strands of Night", "Sudden Impact", "Sustainer of the Realm", "Telepathy", "Thieving Magpie", "Thoughtleech", "Throne of Bone", "Treasure Trove", "Treefolk Seedlings", "Untamed Wilds", "Vengeance", "Wall of Air", "Wall of Bone", "Wall of Fire", "Wall of Spears", "Wall of Swords", "Wind Dancer", "Wing Snare", "Wooden Sphere", "Yavimaya Enchantress", "Yawgmoth's Edict");
		this.addCards(Rarity.RARE, "Abyssal Horror", "Adarkar Wastes", "Aladdin's Ring", "Ancestral Memories", "Ancient Silverback", "Archivist", "Beast of Burden", "Bedlam", "Bellowing Fiend", "Benthic Behemoth", "Birds of Paradise", "Blessed Reversal", "Bloodshot Cyclops", "Brushland", "City of Brass", "Coat of Arms", "Crimson Hellkite", "Daring Apprentice", "Darkest Hour", "Deflection", "Delusions of Mediocrity", "Dingus Egg", "Disrupting Scepter", "Dregs of Sorrow", "Early Harvest", "Earthquake", "Eastern Paladin", "Elder Druid", "Elite Archers", "Elvish Archers", "Elvish Champion", "Elvish Piper", "Ensnaring Bridge", "Equilibrium", "Evacuation", "Fallen Angel", "Feroz's Ban", "Fervor", "Final Fortune", "Fleeting Image", "Flying Carpet", "Glorious Anthem", "Goblin King", "Grafted Skullcap", "Greed", "Howling Mine", "Hurricane", "Impatience", "Infernal Contract", "Inferno", "Intrepid Hero", "Jalum Tome", "Jandor's Saddlebags", "Jayemdae Tome", "Karplusan Forest", "Kjeldoran Royal Guard", "Lord of Atlantis", "Mahamoti Djinn", "Mana Clash", "Mana Short", "Maro", "Master Healer", "Mawcor", "Meekstone", "Might of Oaks", "Millstone", "Nature's Resurgence", "Nature's Revolt", "Nightmare", "Northern Paladin", "Okk", "Opposition", "Oppression", "Pariah", "Persecute", "Phyrexian Colossus", "Purify", "Rag Man", "Reckless Embermage", "Relentless Assault", "Reprocess", "Revenant", "Reverse Damage", "Rolling Stones", "Rowen", "Sacred Ground", "Seismic Assault", "Serra Angel", "Shivan Dragon", "Southern Paladin", "Static Orb", "Storm Cauldron", "Stronghold Assassin", "Sulfurous Springs", "Sunweb", "Tainted AEther", "Teferi's Puzzle Box", "Temporal Adept", "Thorn Elemental", "Trained Orgg", "Uktabi Wildcats", "Underground River", "Verduran Enchantress", "Vernal Bloom", "Vizzerdrix", "Wall of Wonder", "Western Paladin", "Wildfire", "Worship", "Wrath of God");
	}
}
