package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Shards of Alara")
public final class ShardsOfAlara extends SimpleExpansion
{
	public ShardsOfAlara()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "Agony Warp", "Akrasan Squire", "Angelsong", "Banewasp Affliction", "Bant Panorama", "Blightning", "Blister Beetle", "Bloodpyre Elemental", "Bloodthorn Taunter", "Bone Splinters", "Branching Bolt", "Call to Heel", "Cancel", "Carrion Thrash", "Cathartic Adept", "Cavern Thoctar", "Cloudheath Drake", "Coma Veil", "Courier's Capsule", "Court Archers", "Cylian Elf", "Deathgreeter", "Deft Duelist", "Dispeller's Capsule", "Dragon Fodder", "Dreg Reaver", "Dregscape Zombie", "Druid of the Anima", "Elvish Visionary", "Esper Panorama", "Etherium Sculptor", "Excommunicate", "Executioner's Capsule", "Gift of the Gargantuan", "Glaze Fiend", "Goblin Deathraiders", "Goblin Mountaineer", "Godtoucher", "Grixis Panorama", "Guardians of Akrasa", "Gustrider Exuberant", "Hindering Light", "Hissing Iguanar", "Incurable Ogre", "Jhessian Lookout", "Jund Panorama", "Jungle Weaver", "Kathari Screecher", "Kederekt Creeper", "Knight of the Skyward Eye", "Lightning Talons", "Lush Growth", "Magma Spray", "Marble Chalice", "Mosstodon", "Naturalize", "Naya Panorama", "Obelisk of Bant", "Obelisk of Esper", "Obelisk of Grixis", "Obelisk of Jund", "Obelisk of Naya", "Oblivion Ring", "Onyx Goblet", "Outrider of Jhess", "Rakeclaw Gargantuan", "Relic of Progenitus", "Resounding Roar", "Resounding Scream", "Resounding Silence", "Resounding Thunder", "Resounding Wave", "Ridge Rannet", "Rip-Clan Crasher", "Sanctum Gargoyle", "Savage Hunger", "Shadowfeed", "Shore Snapper", "Sighted-Caste Sorcerer", "Sigil Blessing", "Skeletal Kathari", "Soul's Fire", "Soul's Grace", "Soul's Might", "Spell Snip", "Steelclad Serpent", "Steward of Valeron", "Thorn-Thrash Viashino", "Tidehollow Strix", "Tortoise Formation", "Undead Leotau", "Vectis Silencers", "Viashino Skeleton", "Viscera Dragger", "Vithian Stinger", "Volcanic Submersion", "Waveskimmer Aven", "Welkin Guide", "Wild Nacatl", "Windwright Mage", "Yoked Plowbeast");
		this.addCards(Rarity.UNCOMMON, "Algae Gharial", "Angel's Herald", "Angelic Benediction", "Arcane Sanctum", "Bant Battlemage", "Bant Charm", "Behemoth's Herald", "Blood Cultist", "Bull Cerodon", "Corpse Connoisseur", "Crumbling Necropolis", "Dawnray Archer", "Demon's Herald", "Dragon's Herald", "Drumhunter", "Esper Battlemage", "Esper Charm", "Etherium Astrolabe", "Exuberant Firestoker", "Fatestitcher", "Filigree Sages", "Fire-Field Ogre", "Fleshbag Marauder", "Grixis Battlemage", "Grixis Charm", "Infest", "Jhessian Infiltrator", "Jund Battlemage", "Jund Charm", "Jungle Shrine", "Kiss of the Amesha", "Metallurgeon", "Mighty Emergence", "Naya Battlemage", "Naya Charm", "Necrogenesis", "Protomatter Powder", "Puppet Conjurer", "Qasali Ambusher", "Rhox Charger", "Rhox War Monk", "Rockcaster Platoon", "Rockslide Elemental", "Sangrite Surge", "Savage Lands", "Scavenger Drake", "Scourge Devil", "Seaside Citadel", "Sigiled Paladin", "Skeletonize", "Sphinx's Herald", "Sprouting Thrinax", "Sunseed Nurturer", "Swerve", "Thoughtcutter Agent", "Thunder-Thrash Elder", "Tidehollow Sculler", "Topan Ascetic", "Tower Gargoyle", "Woolly Thoctar");
		this.addCards(Rarity.RARE, "Ad Nauseam", "Archdemon of Unx", "Battlegrace Angel", "Brilliant Ultimatum", "Broodmate Dragon", "Caldera Hellion", "Clarion Ultimatum", "Covenant of Minds", "Cradle of Vitality", "Crucible of Fire", "Cruel Ultimatum", "Cunning Lethemancer", "Death Baron", "Ethersworn Canonist", "Feral Hydra", "Flameblast Dragon", "Gather Specimens", "Goblin Assault", "Hell's Thunder", "Immortal Coil", "Invincible Hymn", "Kederekt Leviathan", "Keeper of Progenitus", "Knight of the White Orchid", "Knight-Captain of Eos", "Manaplasm", "Master of Etherium", "Memory Erosion", "Mindlock Orb", "Minion Reflector", "Mycoloth", "Ooze Garden", "Predator Dragon", "Punish Ignorance", "Quietus Spike", "Ranger of Eos", "Realm Razer", "Sacellum Godspeaker", "Salvage Titan", "Scourglass", "Sedraxis Specter", "Sharding Sphinx", "Sigil of Distinction", "Skill Borrower", "Skullmulcher", "Spearbreaker Behemoth", "Stoic Angel", "Tar Fiend", "Titanic Ultimatum", "Vein Drinker", "Vicious Shadows", "Violent Ultimatum", "Where Ancients Tread");
		this.addCards(Rarity.MYTHIC, "Ajani Vengeant", "Elspeth, Knight-Errant", "Empyrial Archangel", "Godsire", "Hellkite Overlord", "Kresh the Bloodbraided", "Lich's Mirror", "Mayael the Anima", "Prince of Thralls", "Rafiq of the Many", "Sarkhan Vol", "Sedris, the Traitor King", "Sharuum the Hegemon", "Sphinx Sovereign", "Tezzeret the Seeker");
	}
}
