package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Tempest")
public final class Tempest extends SimpleExpansion
{
	public Tempest()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "Advance Scout", "Aftershock", "Anoint", "Armored Pegasus", "Bayou Dragonfly", "Blood Frenzy", "Blood Pet", "Broken Fall", "Canopy Spider", "Canyon Wildcat", "Capsize", "Circle of Protection: Black", "Circle of Protection: Blue", "Circle of Protection: Green", "Circle of Protection: Red", "Circle of Protection: Shadow", "Circle of Protection: White", "Clergy en-Vec", "Clot Sliver", "Cloudchaser Eagle", "Coercion", "Coiled Tinviper", "Counterspell", "Crown of Flames", "Dark Banishing", "Dark Ritual", "Darkling Stalker", "Dauthi Horror", "Dauthi Marauder", "Dauthi Slayer", "Diabolic Edict", "Disenchant", "Disturbed Burial", "Dream Cache", "Elite Javelineer", "Elvish Fury", "Endless Scream", "Enfeeblement", "Evincar's Justice", "Fireslinger", "Flowstone Giant", "Frog Tongue", "Gaseous Form", "Giant Crab", "Giant Strength", "Gravedigger", "Heart Sliver", "Heartwood Dryad", "Hero's Resolve", "Horned Turtle", "Kindle", "Lightning Blast", "Lightning Elemental", "Lotus Petal", "Lowland Giant", "Manakin", "Manta Riders", "Marsh Lurker", "Master Decoy", "Metallic Sliver", "Mogg Conscripts", "Mogg Fanatic", "Mogg Raider", "Mounted Archers", "Muscle Sliver", "Natural Spring", "Pacifism", "Pincher Beetles", "Pit Imp", "Power Sink", "Rampant Growth", "Rats of Rath", "Reality Anchor", "Respite", "Rolling Thunder", "Rootbreaker Wurm", "Rootwalla", "Rootwater Hunter", "Sadistic Glee", "Sandstone Warrior", "Sea Monster", "Seeker of Skybreak", "Servant of Volrath", "Shadow Rift", "Shatter", "Shimmering Wings", "Skyshroud Elf", "Skyshroud Ranger", "Skyshroud Troll", "Soltari Foot Soldier", "Soltari Lancer", "Soltari Trooper", "Spell Blast", "Spike Drone", "Spinal Graft", "Squee's Toy", "Stone Rain", "Stun", "Talon Sliver", "Thalakos Mistfolk", "Thalakos Seer", "Thalakos Sentry", "Time Ebb", "Trained Armodon", "Tranquility", "Twitch", "Volrath's Curse", "Wall of Diffusion", "Wind Drake", "Winged Sliver");
		this.addCards(Rarity.UNCOMMON, "Abandon Hope", "Ancient Runes", "Ancient Tomb", "Angelic Protector", "Apes of Rath", "Armor Sliver", "Barbed Sliver", "Boil", "Bottle Gnomes", "Charging Rhino", "Chill", "Choke", "Cinder Marsh", "Dauthi Embrace", "Dauthi Ghoul", "Dauthi Mercenary", "Dauthi Mindripper", "Dismiss", "Dread of Night", "Enraging Licid", "Essence Bottle", "Excavator", "Fighting Drake", "Firefly", "Flailing Drake", "Flickering Ward", "Flowstone Salamander", "Fylamarid", "Gallantry", "Ghost Town", "Goblin Bombardment", "Harrow", "Havoc", "Heartwood Treefolk", "Horned Sliver", "Imps' Taunt", "Insight", "Interdict", "Invulnerability", "Jackal Pup", "Knight of Dawn", "Knight of Dusk", "Krakilin", "Leeching Licid", "Legacy's Allure", "Legerdemain", "Light of Day", "Lobotomy", "Maze of Shadows", "Mindwhip Sliver", "Mnemonic Sliver", "Mogg Cannon", "Mogg Hollows", "Mogg Squad", "Needle Storm", "Nurturing Licid", "Opportunist", "Orim's Prayer", "Overrun", "Patchwork Gnomes", "Perish", "Phyrexian Hulk", "Phyrexian Splicer", "Propaganda", "Puppet Strings", "Quickening Licid", "Rain of Tears", "Ranger en-Vec", "Reanimate", "Reap", "Reckless Spite", "Renegade Warlord", "Repentance", "Rootwater Depths", "Rootwater Diver", "Scragnoth", "Screeching Harpy", "Searing Touch", "Segmented Wurm", "Serene Offering", "Shadowstorm", "Sky Spirit", "Skyshroud Condor", "Skyshroud Vampire", "Soltari Crusader", "Soltari Monk", "Soltari Priest", "Souldrinker", "Spontaneous Combustion", "Stalking Stones", "Staunch Defenders", "Steal Enchantment", "Stinging Licid", "Storm Front", "Sudden Impact", "Tahngarth's Rage", "Telethopter", "Thalakos Dreamsower", "Thalakos Lowlands", "Trumpeting Armodon", "Vec Townships", "Verdigris", "Warmth", "Wasteland", "Watchdog", "Whispers of the Muse", "Wild Wurm", "Wind Dancer", "Winter's Grasp", "Worthy Cause");
		this.addCards(Rarity.RARE, "Altar of Dementia", "Aluren", "Apocalypse", "Auratog", "Avenging Angel", "Bellowing Fiend", "Benthic Behemoth", "Booby Trap", "Bounty Hunter", "Caldera Lake", "Canyon Drake", "Carrionette", "Chaotic Goo", "Coffin Queen", "Cold Storage", "Commander Greven il-Vec", "Corpse Dance", "Crazed Armodon", "Cursed Scroll", "Deadshot", "Death Pits of Rath", "Dirtcowl Wurm", "Dracoplasm", "Dregs of Sorrow", "Duplicity", "Earthcraft", "Echo Chamber", "Eladamri's Vineyard", "Eladamri, Lord of Leaves", "Elven Warhounds", "Emerald Medallion", "Emmessi Tome", "Energizer", "Ertai's Meddling", "Escaped Shapeshifter", "Extinction", "Fevered Convulsions", "Field of Souls", "Flowstone Sculpture", "Flowstone Wyvern", "Fool's Tome", "Fugitive Druid", "Furnace of Rath", "Gerrard's Battle Cry", "Grindstone", "Hand to Hand", "Hanna's Custody", "Heartwood Giant", "Helm of Possession", "Humility", "Intuition", "Jet Medallion", "Jinxed Idol", "Kezzerdrix", "Living Death", "Maddening Imp", "Magmasaur", "Magnetic Web", "Mana Severance", "Marble Titan", "Mawcor", "Meditate", "Minion of the Wastes", "Mirri's Guile", "Mongrel Pack", "Nature's Revolt", "No Quarter", "Oracle en-Vec", "Orim, Samite Healer", "Pallimud", "Pearl Medallion", "Pegasus Refuge", "Phyrexian Grimoire", "Pine Barrens", "Precognition", "Rathi Dragon", "Recycle", "Reflecting Pool", "Root Maze", "Rootwater Matriarch", "Rootwater Shaman", "Ruby Medallion", "Sacred Guide", "Safeguard", "Salt Flats", "Sapphire Medallion", "Sarcomancy", "Scabland", "Scalding Tongs", "Scorched Earth", "Scroll Rack", "Selenia, Dark Angel", "Shocker", "Skyshroud Forest", "Soltari Emissary", "Soltari Guerrillas", "Spirit Mirror", "Starke of Rath", "Static Orb", "Thumbscrews", "Time Warp", "Tooth and Claw", "Torture Chamber", "Tradewind Rider", "Unstable Shapeshifter", "Verdant Force", "Vhati il-Dal", "Whim of Volrath", "Winds of Rath", "Wood Sage");
	}
}
