package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Tenth Edition")
public final class TenthEdition extends SimpleExpansion
{
	public TenthEdition()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Afflict", "Aggressive Urge", "Anaba Bodyguard", "Angelic Blessing", "Angelic Wall", "Assassinate", "Aven Cloudchaser", "Aven Fisher", "Aven Windreader", "Bandage", "Benalish Knight", "Bloodrock Cyclops", "Bogardan Firefiend", "Boomerang", "Cancel", "Canopy Spider", "Civic Wayfinder", "Cloud Elemental", "Cloud Sprite", "Commune with Nature", "Contaminated Bond", "Counsel of the Soratami", "Crafty Pathmage", "Craw Wurm", "Dehydration", "Demolish", "Demystify", "Distress", "Dross Crocodile", "Duct Crawler", "Dusk Imp", "Elvish Berserker", "Essence Drain", "Fear", "Festering Goblin", "Firebreathing", "Fists of the Anvil", "Fugitive Wizard", "Ghost Warden", "Giant Growth", "Giant Spider", "Goblin Elite Infantry", "Goblin Piker", "Goblin Sky Raider", "Gravedigger", "Grizzly Bears", "Heart of Light", "Highway Robber", "Hill Giant", "Holy Day", "Holy Strength", "Honor Guard", "Horseshoe Crab", "Incinerate", "Kavu Climber", "Lava Axe", "Lightning Elemental", "Llanowar Elves", "Llanowar Sentinel", "Looming Shade", "Loxodon Mystic", "Lumengrid Warden", "Mass of Ghouls", "Merfolk Looter", "Mind Rot", "Natural Spring", "Naturalize", "Overgrowth", "Pacifism", "Peek", "Phyrexian Rager", "Pincher Beetles", "Plague Beetle", "Prodigal Pyromancer", "Raging Goblin", "Rampant Growth", "Ravenous Rats", "Recover", "Remove Soul", "Reviving Dose", "Robe of Mirrors", "Rock Badger", "Rootwalla", "Rootwater Commando", "Rushwood Dryad", "Sage Owl", "Samite Healer", "Scathe Zombies", "Sea Monster", "Severed Legion", "Shimmering Wings", "Shock", "Sift", "Skyhunter Patrol", "Skyhunter Prowler", "Skyshroud Ranger", "Smash", "Snapping Drake", "Spined Wurm", "Spineless Thug", "Spitting Earth", "Stalking Tiger", "Steadfast Guard", "Stun", "Suntail Hawk", "Terramorphic Expanse", "Terror", "Treetop Bracers", "Tundra Wolves", "Twitch", "Uncontrollable Anger", "Unholy Strength", "Unsummon", "Vampire Bats", "Venerable Monk", "Viashino Runner", "Viashino Sandscout", "Wall of Wood", "Warrior's Honor", "Wild Griffin", "Youthful Knight");
		this.addCards(Rarity.UNCOMMON, "Academy Researchers", "Agonizing Memories", "Air Elemental", "Ancestor's Chosen", "Angel of Mercy", "Angel's Feather", "Arcane Teachings", "Aura Graft", "Aura of Silence", "Ballista Squad", "Blanchwood Armor", "Blaze", "Bog Wraith", "Bottle Gnomes", "Chromatic Star", "Composite Golem", "Condemn", "Cone of Flame", "Consume Spirit", "Creeping Mold", "Cruel Edict", "Cryoclasm", "Deathmark", "Deluge", "Demon's Horn", "Diabolic Tutor", "Discombobulate", "Dragon's Claw", "Drudge Skeletons", "Earth Elemental", "Elven Riders", "Enormous Baloth", "Faerie Conclave", "Femeref Archers", "Flamewave Invoker", "Flashfreeze", "Fog Elemental", "Forbidding Watchtower", "Fountain of Youth", "Furnace Whelp", "Ghitu Encampment", "Goblin Lore", "Guerrilla Tactics", "Hail of Arrows", "Hate Weaver", "Hidden Horror", "High Ground", "Hunted Wumpus", "Icatian Priest", "Icy Manipulator", "Juggernaut", "Karplusan Strider", "Knight of Dusk", "Kraken's Eye", "Leonin Scimitar", "Luminesce", "Lure", "Mantis Engine", "Megrim", "Might Weaver", "Mind Stone", "Mogg Fanatic", "Nantuko Husk", "Nekrataal", "No Rest for the Wicked", "Orcish Artillery", "Ornithopter", "Overrun", "Persuasion", "Phantom Warrior", "Phyrexian Vault", "Primal Rage", "Puppeteer", "Pyroclasm", "Quicksand", "Rage Weaver", "Rain of Tears", "Recollect", "Regeneration", "Relentless Rats", "Reminisce", "Rod of Ruin", "Rule of Law", "Serra's Embrace", "Shatterstorm", "Sky Weaver", "Skyhunter Skirmisher", "Soul Feast", "Soul Warden", "Spark Elemental", "Spawning Pool", "Spellbook", "Spiketail Hatchling", "Spirit Link", "Spirit Weaver", "Stampeding Wildebeests", "Starlight Invoker", "Steel Golem", "Stronghold Discipline", "Sudden Impact", "Sylvan Basilisk", "Sylvan Scrying", "Tangle Spider", "Telepathy", "Telling Time", "Tempest of Light", "Thieving Magpie", "Threaten", "Thrull Surgeon", "Thundering Giant", "Tidings", "Treasure Hunter", "Treetop Village", "Vedalken Mastermind", "Viridian Shaman", "Wall of Air", "Wall of Fire", "Wall of Swords", "Whispersilk Cloak", "Wurm's Tooth", "Yavimaya Enchantress");
		this.addCards(Rarity.RARE, "Abundance", "Adarkar Wastes", "Ambassador Laquatus", "Angelic Chorus", "Arcanis the Omnipotent", "Ascendant Evincar", "Avatar of Might", "Battlefield Forge", "Beacon of Destruction", "Beacon of Immortality", "Beacon of Unrest", "Birds of Paradise", "Bloodfire Colossus", "Brushland", "Caves of Koilos", "Cephalid Constable", "Chimeric Staff", "Cho-Manno, Revolutionary", "Citanul Flute", "Clone", "Coat of Arms", "Colossus of Sardia", "Crucible of Worlds", "Denizen of the Deep", "Doomed Necromancer", "Doubling Cube", "Dragon Roost", "Dreamborn Muse", "Elvish Champion", "Elvish Piper", "Evacuation", "Field Marshal", "Flowstone Slide", "Furnace of Rath", "Gaea's Herald", "Glorious Anthem", "Goblin King", "Grave Pact", "Graveborn Muse", "Head Games", "Howling Mine", "Hurkyl's Recall", "Hurricane", "Hypnotic Specter", "Jayemdae Tome", "Joiner Adept", "Kamahl, Pit Fighter", "Karplusan Forest", "Kjeldoran Royal Guard", "Lavaborn Muse", "Legacy Weapon", "Llanowar Wastes", "Lord of the Pit", "Lord of the Undead", "Loxodon Warhammer", "Loyal Sentry", "Mahamoti Djinn", "Manabarbs", "March of the Machines", "Midnight Ritual", "Might of Oaks", "Millstone", "Mind Bend", "Mirri, Cat Warrior", "Mobilization", "Molimo, Maro-Sorcerer", "Mortal Combat", "Mortivore", "Nightmare", "Nomad Mythmaker", "Paladin en-Vec", "Pariah", "Phage the Untouchable", "Pithing Needle", "Plagiarize", "Plague Wind", "Platinum Angel", "Quirion Dryad", "Razormane Masticore", "Relentless Assault", "Reya Dawnbringer", "Rhox", "Righteousness", "Root Maze", "Rootwater Matriarch", "Royal Assassin", "Scalpelexis", "Scion of the Wild", "Scoria Wurm", "Sculpting Steel", "Seedborn Muse", "Seismic Assault", "Sengir Vampire", "Serra Angel", "Shivan Dragon", "Shivan Hellkite", "Shivan Reef", "Shunt", "Siege-Gang Commander", "Sleeper Agent", "Soulblast", "Squee, Goblin Nabob", "Story Circle", "Sulfurous Springs", "Sunken Hope", "The Hive", "Time Stop", "Time Stretch", "Traumatize", "Troll Ascetic", "True Believer", "Twincast", "Underground River", "Underworld Dreams", "Upwelling", "Verdant Force", "Voice of All", "Warp World", "Windborn Muse", "Wrath of God", "Yavimaya Coast");
	}
}
