package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Time Spiral")
public final class TimeSpiral extends SimpleExpansion
{
	public TimeSpiral()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "AEther Web", "AEtherflame Wall", "Amrou Scout", "Amrou Seekers", "Ancient Grudge", "Ashcoat Bear", "Assassinate", "Basal Sliver", "Benalish Cavalry", "Bewilder", "Blazing Blade Askari", "Bogardan Rager", "Bonesplitter Sliver", "Brass Gnat", "Call to the Netherworld", "Cancel", "Castle Raptors", "Chameleon Blur", "Children of Korlis", "Chromatic Star", "Clockspinning", "Cloudchaser Kestrel", "Coal Stoker", "Coral Trickster", "Corpulent Corpse", "Crookclaw Transmuter", "Cyclopean Giant", "D'Avenant Healer", "Dark Withering", "Deathspore Thallid", "Detainment Spell", "Divine Congregation", "Dream Stalker", "Drifter il-Dal", "Drudge Reavers", "Durkwood Baloth", "Empty the Warrens", "Errant Doomsayers", "Errant Ephemeron", "Eternity Snare", "Fathom Seer", "Feebleness", "Flamecore Elemental", "Flickering Spirit", "Flowstone Channeler", "Foriysian Interceptor", "Fortify", "Gaze of Justice", "Gemhide Sliver", "Ghitu Firebreathing", "Glass Asp", "Goblin Skycutter", "Gorgon Recluse", "Grapeshot", "Greenseeker", "Ground Rift", "Havenwood Wurm", "Herd Gnarr", "Icatian Crier", "Ironclaw Buzzardiers", "Ivory Giant", "Jedit's Dragoons", "Jhoira's Timebug", "Keldon Halberdier", "Lightning Axe", "Looter il-Kor", "Mana Skimmer", "Mindlash Sliver", "Mindstab", "Mogg War Marshal", "Molder", "Momentary Blink", "Mwonvuli Acid-Moss", "Mystical Teachings", "Nantuko Shaman", "Ophidian Eye", "Orcish Cannonade", "Pentarch Ward", "Penumbra Spider", "Pit Keeper", "Plunder", "Prismatic Lens", "Psychotic Episode", "Rift Bolt", "Sage of Epityr", "Sangrophage", "Savage Thallid", "Scarwood Treefolk", "Screeching Sliver", "Search for Tomorrow", "Shadow Sliver", "Sidewinder Sliver", "Skulking Knight", "Slipstream Serpent", "Snapback", "Spiketail Drakeling", "Spinneret Sliver", "Sprout", "Strangling Soot", "Strength in Numbers", "Subterranean Shambler", "Temporal Eddy", "Temporal Isolation", "Tendrils of Corruption", "Terramorphic Expanse", "Thallid Germinator", "Thallid Shell-Dweller", "Think Twice", "Thrill of the Hunt", "Tolarian Sentinel", "Traitor's Clutch", "Trespasser il-Vec", "Two-Headed Sliver", "Urborg Syphon-Mage", "Venser's Sliver", "Viashino Bladescout", "Viscerid Deepwalker", "Viscid Lemures", "Watcher Sliver", "Wormwood Dryad", "Zealot il-Vec");
		this.addCards(Rarity.UNCOMMON, "Aspect of Mongoose", "Assembly-Worker", "Barbed Shocker", "Basalt Gargoyle", "Brine Elemental", "Calciform Pools", "Careful Consideration", "Cavalry Master", "Celestial Crusader", "Chronatog Totem", "Clockwork Hydra", "Conflagrate", "Dementia Sliver", "Dread Return", "Dreadship Reef", "Durkwood Tracker", "Duskrider Peregrine", "Evil Eye of Urborg", "Faceless Devourer", "Fallen Ideal", "Firemaw Kavu", "Firewake Sliver", "Fledgling Mawcor", "Fool's Demise", "Foriysian Totem", "Fungal Reaches", "Fury Sliver", "Ghostflame Sliver", "Griffin Guide", "Gustcloak Cavalier", "Harmonic Sliver", "Haunting Hymn", "Ignite Memories", "Knight of the Holy Nimbus", "Krosan Grip", "Locket of Yesterdays", "Might Sliver", "Might of Old Krosa", "Molten Slagheap", "Nightshade Assassin", "Opaline Sliver", "Outrider en-Kor", "Paradise Plume", "Paradox Haze", "Pendelhaven Elder", "Phantom Wurm", "Phthisis", "Phyrexian Totem", "Plated Pegasus", "Premature Burial", "Primal Forcemage", "Pull from Eternity", "Quilled Sliver", "Return to Dust", "Riftwing Cloudskate", "Saltcrusted Steppe", "Scryb Ranger", "Skittering Monstrosity", "Smallpox", "Spell Burst", "Spirit Loop", "Sporesower Thallid", "Stormcloud Djinn", "Sudden Death", "Sudden Shock", "Sulfurous Blast", "Tectonic Fiend", "Telekinetic Sliver", "Thick-Skinned Goblin", "Thunder Totem", "Tromp the Domains", "Truth or Tale", "Undying Rage", "Urza's Factory", "Vampiric Sliver", "Voidmage Husher", "Volcanic Awakening", "Weatherseed Totem", "Wipe Away", "Yavimaya Dryad");
		this.addCards(Rarity.RARE, "Academy Ruins", "Ancestral Vision", "Angel's Grace", "Bogardan Hellkite", "Candles of Leng", "Chronosavant", "Curse of the Cabal", "Deep-Sea Kraken", "Demonic Collusion", "Draining Whelk", "Dralnu, Lich Lord", "Endrek Sahr, Master Breeder", "Evangelize", "Flagstones of Trokair", "Fortune Thief", "Fungus Sliver", "Gauntlet of Power", "Gemstone Caverns", "Greater Gargadon", "Hivestone", "Hypergenesis", "Ib Halfheart, Goblin Tactician", "Ith, High Arcanist", "Ixidron", "Jaya Ballard, Task Mage", "Kaervek the Merciless", "Kher Keep", "Liege of the Pit", "Lim-Dûl the Necromancer", "Living End", "Lotus Bloom", "Magus of the Candelabra", "Magus of the Disk", "Magus of the Jar", "Magus of the Mirror", "Magus of the Scroll", "Mangara of Corondor", "Mishra, Artificer Prodigy", "Moonlace", "Nether Traitor", "Norin the Wary", "Opal Guardian", "Pardic Dragon", "Pentarch Paladin", "Plague Sliver", "Psionic Sliver", "Pulmonic Sliver", "Reiterate", "Restore Balance", "Saffi Eriksdotter", "Sarpadian Empires, Vol. VII", "Scion of the Ur-Dragon", "Sedge Sliver", "Sengir Nosferatu", "Serra Avenger", "Spectral Force", "Spike Tiller", "Sprite Noble", "Squall Line", "Stonebrow, Krosan Hero", "Stonewood Invocation", "Stronghold Overseer", "Stuffy Doll", "Sudden Spoiling", "Swarmyard", "Teferi, Mage of Zhalfir", "Thelon of Havenwood", "Thelonite Hermit", "Tivadar of Thorn", "Trickbind", "Triskelavus", "Unyaro Bees", "Verdant Embrace", "Vesuva", "Vesuvan Shapeshifter", "Walk the Aeons", "Weathered Bodyguards", "Wheel of Fate", "Word of Seizing", "Wurmcalling");
	}
}
