package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Urza's Saga")
public final class UrzasSaga extends SimpleExpansion
{
	public UrzasSaga()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Forest", "Forest", "Forest", "Island", "Island", "Island", "Island", "Mountain", "Mountain", "Mountain", "Mountain", "Plains", "Plains", "Plains", "Plains", "Swamp", "Swamp", "Swamp", "Swamp");
		this.addCards(Rarity.COMMON, "Acridian", "Angelic Page", "Annul", "Arc Lightning", "Argothian Swine", "Befoul", "Blanchwood Treefolk", "Blood Vassal", "Bog Raiders", "Bravado", "Breach", "Brilliant Halo", "Cackling Fiend", "Carrion Beetles", "Catalog", "Cave Tiger", "Cloak of Mists", "Congregate", "Coral Merfolk", "Corrupt", "Curfew", "Dark Ritual", "Despondency", "Disciple of Grace", "Disciple of Law", "Disenchant", "Disruptive Student", "Drifting Meadow", "Dromosaur", "Duress", "Elvish Herder", "Elvish Lyrist", "Exhume", "Expunge", "Falter", "Fertile Ground", "Fiery Mantle", "Fortitude", "Gaea's Bounty", "Goblin Matron", "Goblin Patrol", "Goblin Raider", "Goblin Spelunkers", "Goblin War Buggy", "Gorilla Warrior", "Headlong Rush", "Healing Salve", "Heat Ray", "Hermetic Study", "Hidden Spider", "Hollow Dogs", "Horseshoe Crab", "Hush", "Launch", "Lay Waste", "Looming Shade", "Lull", "Monk Realist", "Opal Caryatid", "Opal Gargoyle", "Pacifism", "Path of Peace", "Pegasus Charger", "Pendrell Drake", "Pendrell Flux", "Pestilence", "Phyrexian Ghoul", "Polluted Mire", "Pouncing Jaguar", "Power Sink", "Power Taint", "Priest of Titania", "Ravenous Skirge", "Raze", "Reflexes", "Rejuvenate", "Remote Isle", "Rescind", "Retromancer", "Rewind", "Rune of Protection: Black", "Rune of Protection: Blue", "Rune of Protection: Green", "Rune of Protection: Red", "Rune of Protection: White", "Sanctum Custodian", "Sandbar Merfolk", "Scrap", "Serra Zealot", "Shower of Sparks", "Sicken", "Silent Attendant", "Skittering Skirge", "Slippery Karst", "Smoldering Crater", "Spire Owl", "Symbiosis", "Tolarian Winds", "Treetop Rangers", "Unnerve", "Unworthy Dead", "Veil of Birds", "Veiled Serpent", "Venomous Fangs", "Viashino Outrider", "Viashino Runner", "Viashino Weaponsmith", "Wild Dogs", "Winding Wurm", "Wizard Mentor");
		this.addCards(Rarity.UNCOMMON, "Absolute Grace", "Absolute Law", "Academy Researchers", "Acidic Soil", "Albino Troll", "Anaconda", "Arcane Laboratory", "Argothian Elder", "Bereavement", "Blanchwood Armor", "Blasted Landscape", "Bull Hippo", "Carpet of Flowers", "Cathodion", "Claws of Gix", "Clear", "Confiscate", "Cradle Guard", "Crazed Skirge", "Crosswinds", "Crystal Chimes", "Defensive Formation", "Destructive Urge", "Diabolic Servitude", "Disorder", "Douse", "Dragon Blood", "Enchantment Alteration", "Endoskeleton", "Exhaustion", "Fecundity", "Fire Ants", "Flesh Reaver", "Fog Bank", "Gaea's Embrace", "Goblin Cadets", "Goblin Lackey", "Goblin Offensive", "Guma", "Hawkeater Moth", "Hibernation", "Hidden Ancients", "Hidden Guerrillas", "Hopping Automaton", "Humble", "Jagged Lightning", "Lilting Refrain", "Lingering Mirage", "Mana Leech", "Meltdown", "Mobile Fort", "Monk Idealist", "No Rest for the Wicked", "Opal Acrolith", "Order of Yawgmoth", "Outmaneuver", "Parasitic Bond", "Peregrine Drake", "Pit Trap", "Planar Void", "Presence of the Master", "Priest of Gix", "Rain of Filth", "Rain of Salt", "Reclusive Wight", "Redeem", "Retaliation", "Rune of Protection: Artifacts", "Sanctum Guardian", "Sandbar Serpent", "Sanguine Guard", "Scald", "Seasoned Marshal", "Serra's Embrace", "Serra's Hymn", "Shimmering Barrier", "Shiv's Embrace", "Shivan Raptor", "Skirge Familiar", "Songstitcher", "Spined Fluke", "Spreading Algae", "Steam Blast", "Stern Proctor", "Telepathy", "Thran Turbine", "Thundering Giant", "Titania's Boon", "Titania's Chosen", "Torch Song", "Treefolk Seedlings", "Turnabout", "Urza's Armor", "Vampiric Embrace", "Veiled Apparition", "Veiled Sentry", "Victimize", "Vile Requiem", "Voice of Grace", "Voice of Law", "Voltaic Key", "Vug Lizard", "Wall of Junk", "War Dance", "Waylay", "Windfall", "Wirecat", "Worn Powerstone", "Yawgmoth's Edict", "Zephid's Embrace");
		this.addCards(Rarity.RARE, "Abundance", "Abyssal Horror", "Angelic Chorus", "Antagonism", "Argothian Enchantress", "Argothian Wurm", "Attunement", "Back to Basics", "Barrin's Codex", "Barrin, Master Wizard", "Bedlam", "Brand", "Bulwark", "Catastrophe", "Child of Gaea", "Chimeric Staff", "Citanul Centaurs", "Citanul Flute", "Citanul Hierophants", "Contamination", "Copper Gnomes", "Crater Hellion", "Dark Hatchling", "Darkest Hour", "Discordant Dirge", "Drifting Djinn", "Eastern Paladin", "Electryte", "Elite Archers", "Endless Wurm", "Energy Field", "Exploration", "Faith Healer", "Fault Line", "Fluctuator", "Gaea's Cradle", "Gamble", "Gilded Drake", "Glorious Anthem", "Grafted Skullcap", "Great Whale", "Greater Good", "Greener Pastures", "Herald of Serra", "Hidden Herd", "Hidden Predators", "Hidden Stag", "Ill-Gotten Gains", "Imaginary Pet", "Intrepid Hero", "Karn, Silver Golem", "Lifeline", "Lightning Dragon", "Lotus Blossom", "Lurking Evil", "Metrognome", "Midsummer Revel", "Mishra's Helix", "Morphling", "Noetic Scales", "Okk", "Opal Archangel", "Opal Titan", "Oppression", "Pariah", "Persecute", "Phyrexian Colossus", "Phyrexian Processor", "Phyrexian Tower", "Planar Birth", "Purging Scythe", "Recantation", "Remembrance", "Reprocess", "Rumbling Crescendo", "Rune of Protection: Lands", "Scoria Wurm", "Serra Avatar", "Serra's Liturgy", "Serra's Sanctum", "Shivan Gorge", "Shivan Hellkite", "Show and Tell", "Sleeper Agent", "Smokestack", "Sneak Attack", "Somnophore", "Soul Sculptor", "Sporogenesis", "Stroke of Genius", "Sulfuric Vapors", "Sunder", "Tainted AEther", "Temporal Aperture", "Thran Quarry", "Time Spiral", "Tolarian Academy", "Umbilicus", "Vebulid", "Veiled Crocodile", "Vernal Bloom", "Viashino Sandswimmer", "Western Paladin", "Whetstone", "Whirlwind", "Wildfire", "Witch Engine", "Worship", "Yawgmoth's Will", "Zephid");
	}
}
