package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Vintage Masters")
public final class VintageMasters extends SimpleExpansion
{
	public VintageMasters()
	{
		super();

		this.addCards(Rarity.COMMON, "Addle", "Afterlife", "Aftershock", "Aquamoeba", "Armor of Thorns", "Arrogant Wurm", "Barren Moor", "Basking Rootwalla", "Battle Screech", "Beetleback Chief", "Benalish Trapper", "Benevolent Bodyguard", "Brainstorm", "Brilliant Halo", "Brindle Shoat", "Carnophage", "Chain Lightning", "Chainer's Edict", "Chartooth Cougar", "Choking Sands", "Choking Tethers", "Circular Logic", "Claws of Wirewood", "Counterspell", "Dark Ritual", "Dauthi Mercenary", "Death's-Head Buzzard", "Deep Analysis", "Deftblade Elite", "Elephant Guide", "Elvish Aberration", "Exile", "Expunge", "Fallen Askari", "Falter", "Fledgling Djinn", "Forgotten Cave", "Frantic Search", "Fyndhorn Elves", "Giant Mantis", "Giant Strength", "Gilded Light", "Goblin Commando", "Goblin General", "Goblin Matron", "Goblin Patrol", "Gustcloak Harrier", "Hulking Goblin", "Jungle Wurm", "Keeneye Aven", "Killer Whale", "Kindle", "Krosan Tusker", "Krosan Vorine", "Krovikan Sorcerer", "Lonely Sandbar", "Man-o'-War", "Mana Prism", "Mesmeric Fiend", "Mistmoon Griffin", "Nature's Lore", "Nightscape Familiar", "Noble Templar", "Obsessive Search", "Ophidian", "Orcish Lumberjack", "Owl Familiar", "Paralyze", "Phantom Nomad", "Predatory Nightstalker", "Provoke", "Putrid Imp", "Radiant's Judgment", "Reckless Charge", "Renewed Faith", "Repel", "Rescind", "Scrivener", "Seal of Cleansing", "Secluded Steppe", "Shelter", "Simian Grunts", "Skirge Familiar", "Skirk Drill Sergeant", "Skirk Prospector", "Skywing Aven", "Solar Blast", "Soltari Emissary", "Soltari Trooper", "Spark Spray", "Spinal Graft", "Sudden Strength", "Tangle", "Temporal Fissure", "Teroh's Faithful", "Tranquil Thicket", "Tribute to the Wild", "Tyrant's Choice", "Urborg Uprising", "Wall of Diffusion", "Wild Mongrel");
		this.addCards(Rarity.UNCOMMON, "AEther Mutation", "Akroma's Blessing", "Animate Dead", "Armadillo Cloak", "Astral Slide", "Bad River", "Blastoderm", "Blazing Specter", "Brain Freeze", "Breath of Life", "Cabal Ritual", "Caldera Lake", "Chimeric Idol", "Cloud Djinn", "Cloud of Faeries", "Dark Hatchling", "Death Grasp", "Deathreap Ritual", "Desert Twister", "Devout Witness", "Dreampod Druid", "Empyrial Armor", "Erhnam Djinn", "Fact or Fiction", "Famine", "Fireblast", "Fires of Yavimaya", "Flametongue Kavu", "Flood Plain", "Flowstone Hellion", "Gaea's Embrace", "Goblin Goon", "Goblin Ringleader", "Goblin Settler", "Goblin Trenches", "Goblin Warchief", "Grasslands", "Grizzly Fate", "Gush", "High Tide", "Hymn to Tourach", "Ivory Tower", "Kaervek's Torch", "Kezzerdrix", "Lightning Rift", "Lurking Evil", "Mountain Valley", "Mystic Zealot", "Nostalgic Dreams", "Penumbra Wurm", "Phyrexian Defiler", "Pianna, Nomad Captain", "Pillaging Horde", "Pine Barrens", "Power Sink", "Prophetic Bolt", "Psychatog", "Radiant, Archangel", "Reanimate", "Reviving Vapors", "Rites of Initiation", "Roar of the Wurm", "Rocky Tar Pit", "Salt Flats", "Sarcomancy", "Scabland", "Serendib Efreet", "Sidar Jabari", "Skyshroud Forest", "Stoic Champion", "Su-Chi", "Swords to Plowshares", "Symbiotic Wurm", "Tendrils of Agony", "Thalakos Drifters", "Thopter Squadron", "Triangle of War", "Turnabout", "Waterfront Bouncer", "Yavimaya Elder");
		this.addCards(Rarity.RARE, "Academy Elite", "Ancient Tomb", "Ankh of Mishra", "Badlands", "Baleful Force", "Baleful Strix", "Basandra, Battle Seraph", "Bayou", "Berserk", "Brago, King Eternal", "Burning Wish", "Burning of Xinye", "Chaos Warp", "Clickslither", "Control Magic", "Council's Judgment", "Crater Hellion", "Crescendo of War", "Crovax the Cursed", "Cruel Bargain", "Cursed Scroll", "Dack's Duplicate", "Decree of Justice", "Deranged Hermit", "Drakestown Forgotten", "Edric, Spymaster of Trest", "Ephemeron", "Eternal Dragon", "Flowstone Sculpture", "Flusterstorm", "Force of Will", "Future Sight", "Gamble", "Genesis", "Gerrard's Battle Cry", "Gigapede", "Goblin Lackey", "Goblin Piledriver", "Grand Coliseum", "Grenzo, Dungeon Warden", "Hermit Druid", "Ichorid", "Jareth, Leonine Titan", "Karmic Guide", "Karn, Silver Golem", "Keldon Necropolis", "Kjeldoran Outpost", "Kongming, \"Sleeping Dragon\"", "Lake of the Dead", "Laquatus's Champion", "Lightning Dragon", "Living Death", "Magister of Worth", "Mana Vault", "Masticore", "Mind's Desire", "Nature's Ruin", "Necropotence", "Nevinyrral's Disk", "Norwood Priestess", "Null Rod", "Palinchron", "Parallax Wave", "Plateau", "Plea for Power", "Predator, Flagship", "Realm Seekers", "Recurring Nightmare", "Regrowth", "Reign of the Pit", "Ring of Gix", "Rofellos, Llanowar Emissary", "Rorix Bladewing", "Saproling Burst", "Savannah", "Scrubland", "Sea Drake", "Selvala, Explorer Returned", "Shivan Wurm", "Silvos, Rogue Elemental", "Smokestack", "Sphere of Resistance", "Spirit Cairn", "Spirit Mirror", "Spiritmonger", "Starstorm", "Strip Mine", "Stroke of Genius", "Sulfuric Vortex", "Survival of the Fittest", "Sylvan Library", "Taiga", "Thawing Glaciers", "Tradewind Rider", "Tropical Island", "Tundra", "Underground Sea", "Vampiric Tutor", "Visara the Dreadful", "Volcanic Island", "Volrath's Shapeshifter", "Winds of Rath", "Worldgorger Dragon", "Yavimaya Hollow", "Zhalfirin Crusader");
		this.addCards(Rarity.MYTHIC, "Armageddon", "Balance", "Bazaar of Baghdad", "Channel", "City in a Bottle", "Coercive Portal", "Dack Fayden", "Demonic Tutor", "Eureka", "Fastbond", "Jace, the Mind Sculptor", "Library of Alexandria", "Lion's Eye Diamond", "Mana Crypt", "Mana Drain", "Marchesa, the Black Rose", "Memory Jar", "Mishra's Workshop", "Morphling", "Muzzio, Visionary Architect", "Oath of Druids", "Scourge of the Throne", "Skullclamp", "Sol Ring", "Time Vault", "Tolarian Academy", "Upheaval", "Wheel of Fortune", "Yawgmoth's Bargain", "Yawgmoth's Will");
		this.addCards(Rarity.SPECIAL, "Ancestral Recall", "Black Lotus", "Mox Emerald", "Mox Jet", "Mox Pearl", "Mox Ruby", "Mox Sapphire", "Time Walk", "Timetwister");
	}
}
