package org.rnd.jmagic.expansions;

import org.rnd.jmagic.engine.*;

@Name("Zendikar")
public final class Zendikar extends SimpleExpansion
{
	public Zendikar()
	{
		super();

		this.addCards(Rarity.LAND, "Forest", "Island", "Mountain", "Plains", "Swamp");
		this.addCards(Rarity.COMMON, "Adventuring Gear", "Beast Hunt", "Bladetusk Boar", "Blood Seeker", "Bog Tatters", "Bold Defense", "Burst Lightning", "Caller of Gales", "Cancel", "Caravan Hurda", "Cliff Threader", "Crypt Ripper", "Demolish", "Desecrated Earth", "Disfigure", "Expedition Map", "Explorer's Scope", "Giant Scorpion", "Goblin Bushwhacker", "Goblin Shortcutter", "Goblin War Paint", "Grazing Gladehart", "Grim Discovery", "Guul Draz Vampire", "Hagra Crocodile", "Harrow", "Heartstabber Mosquito", "Hedron Scrabbler", "Hideous End", "Highland Berserker", "Into the Roil", "Ior Ruin Expedition", "Joraga Bard", "Journey to Nowhere", "Kabira Crossroads", "Khalni Heart Expedition", "Kor Cartographer", "Kor Hookmaster", "Kor Outfitter", "Kor Sanctifiers", "Kor Skyfisher", "Kraken Hatchling", "Lethargy Trap", "Magma Rift", "Makindi Shieldmate", "Mindless Null", "Mire Blight", "Mold Shambler", "Molten Ravager", "Narrow Escape", "Nimana Sell-Sword", "Nimbus Wings", "Nissa's Chosen", "Noble Vestige", "Ondu Cleric", "Oran-Rief Recluse", "Oran-Rief Survivalist", "Paralyzing Grasp", "Pillarfield Ox", "Piranha Marsh", "Plated Geopede", "Reckless Scholar", "Relic Crush", "Ruinous Minotaur", "Savage Silhouette", "Scythe Tiger", "Seismic Shudder", "Shatterskull Giant", "Shieldmate's Blessing", "Shoal Serpent", "Sky Ruin Drake", "Slaughter Cry", "Soaring Seacliff", "Soul Stair Expedition", "Spell Pierce", "Spidersilk Net", "Spire Barrage", "Spreading Seas", "Steppe Lynx", "Stonework Puma", "Sunspring Expedition", "Surrakar Marauder", "Tanglesap", "Teetering Peaks", "Tempest Owl", "Territorial Baloth", "Timbermaw Larva", "Torch Slinger", "Trapfinder's Trick", "Tuktuk Grunts", "Turntimber Grove", "Umara Raptor", "Vampire Lacerator", "Vampire's Bite", "Vastwood Gorger", "Vines of Vastwood", "Welkin Tern", "Whiplash Trap", "Windrider Eel", "Zektar Shrine Expedition", "Zendikar Farguide");
		this.addCards(Rarity.UNCOMMON, "AEther Figment", "Akoum Refuge", "Arrow Volley Trap", "Baloth Cage Trap", "Baloth Woodcrasher", "Blazing Torch", "Brave the Elements", "Carnage Altar", "Cobra Trap", "Feast of Blood", "Frontier Guide", "Gatekeeper of Malakir", "Geyser Glider", "Goblin Ruinblaster", "Gomazoa", "Graypelt Refuge", "Greenweaver Druid", "Hagra Diabolist", "Hedron Crab", "Hellfire Mongrel", "Inferno Trap", "Jwar Isle Refuge", "Kazandu Blademaster", "Kazandu Refuge", "Khalni Gem", "Kor Aeronaut", "Kor Duelist", "Landbind Ritual", "Living Tsunami", "Mark of Mutiny", "Marsh Casualties", "Merfolk Seastalkers", "Merfolk Wayfinder", "Mind Sludge", "Murasa Pyromancer", "Needlebite Trap", "Pitfall Trap", "Primal Bellow", "Punishing Fire", "Quest for Ancient Secrets", "Quest for Pure Flame", "Quest for the Gemblades", "Quest for the Gravelord", "Quest for the Holy Relic", "Ravenous Trap", "River Boa", "Runeflare Trap", "Seascape Aerialist", "Sejiri Refuge", "Shepherd of the Lost", "Summoner's Bane", "Tajuru Archer", "Trailblazer's Boots", "Trapmaker's Snare", "Trusty Machete", "Turntimber Basilisk", "Unstable Footing", "Vampire Hexmage", "Vampire Nighthawk", "Windborne Charge");
		this.addCards(Rarity.RARE, "Archive Trap", "Archmage Ascension", "Arid Mesa", "Armament Master", "Bala Ged Thief", "Beastmaster Ascension", "Blade of the Bloodchief", "Blood Tribute", "Bloodchief Ascension", "Bloodghast", "Celestial Mantle", "Conqueror's Pledge", "Cosi's Trickster", "Crypt of Agadeem", "Day of Judgment", "Devout Lightcaster", "Electropotence", "Elemental Appeal", "Emeria Angel", "Emeria, the Sky Ruin", "Gigantiform", "Goblin Guide", "Grappling Hook", "Guul Draz Specter", "Halo Hunter", "Hellkite Charger", "Kabira Evangel", "Kazuul Warlord", "Lavaball Trap", "Lullmage Mentor", "Luminarch Ascension", "Magosi, the Waterveil", "Malakir Bloodwitch", "Marsh Flats", "Misty Rainforest", "Oracle of Mul Daya", "Oran-Rief, the Vastwood", "Predatory Urge", "Pyromancer Ascension", "Rite of Replication", "Roil Elemental", "Sadistic Sacrament", "Scalding Tarn", "Scute Mob", "Sea Gate Loremaster", "Sphinx of Jwar Isle", "Sphinx of Lost Truths", "Summoning Trap", "Terra Stomper", "Turntimber Ranger", "Valakut, the Molten Pinnacle", "Verdant Catacombs", "World Queller");
		this.addCards(Rarity.MYTHIC, "Chandra Ablaze", "Eldrazi Monument", "Eternity Vessel", "Felidar Sovereign", "Iona, Shield of Emeria", "Kalitas, Bloodchief of Ghet", "Lorthos, the Tidemaker", "Lotus Cobra", "Mindbreak Trap", "Nissa Revane", "Ob Nixilis, the Fallen", "Obsidian Fireheart", "Rampaging Baloths", "Sorin Markov", "Warren Instigator");
	}
}
